// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "CconLayer.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic CconLayer::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic CconLayer::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<38> CconLayer::ap_ST_fsm_state1 = "1";
const sc_lv<38> CconLayer::ap_ST_fsm_state2 = "10";
const sc_lv<38> CconLayer::ap_ST_fsm_state3 = "100";
const sc_lv<38> CconLayer::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<38> CconLayer::ap_ST_fsm_state6 = "10000";
const sc_lv<38> CconLayer::ap_ST_fsm_state7 = "100000";
const sc_lv<38> CconLayer::ap_ST_fsm_state8 = "1000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state9 = "10000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state10 = "100000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state11 = "1000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state12 = "10000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state13 = "100000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state14 = "1000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state15 = "10000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state16 = "100000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state17 = "1000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state18 = "10000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state19 = "100000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state20 = "1000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state21 = "10000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state22 = "100000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state23 = "1000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state24 = "10000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state25 = "100000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state26 = "1000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state27 = "10000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state28 = "100000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state29 = "1000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state30 = "10000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state31 = "100000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state32 = "1000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state33 = "10000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state34 = "100000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state35 = "1000000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state36 = "10000000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state37 = "100000000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state38 = "1000000000000000000000000000000000000";
const sc_lv<38> CconLayer::ap_ST_fsm_state39 = "10000000000000000000000000000000000000";
const bool CconLayer::ap_const_boolean_1 = true;
const sc_lv<32> CconLayer::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_2 = "10";
const sc_lv<1> CconLayer::ap_const_lv1_0 = "0";
const sc_lv<32> CconLayer::ap_const_lv32_3 = "11";
const bool CconLayer::ap_const_boolean_0 = false;
const sc_lv<32> CconLayer::ap_const_lv32_4 = "100";
const sc_lv<32> CconLayer::ap_const_lv32_5 = "101";
const sc_lv<32> CconLayer::ap_const_lv32_6 = "110";
const sc_lv<32> CconLayer::ap_const_lv32_7 = "111";
const sc_lv<32> CconLayer::ap_const_lv32_9 = "1001";
const sc_lv<32> CconLayer::ap_const_lv32_A = "1010";
const sc_lv<32> CconLayer::ap_const_lv32_F = "1111";
const sc_lv<32> CconLayer::ap_const_lv32_10 = "10000";
const sc_lv<32> CconLayer::ap_const_lv32_14 = "10100";
const sc_lv<32> CconLayer::ap_const_lv32_23 = "100011";
const sc_lv<32> CconLayer::ap_const_lv32_24 = "100100";
const sc_lv<1> CconLayer::ap_const_lv1_1 = "1";
const sc_lv<4> CconLayer::ap_const_lv4_0 = "0000";
const sc_lv<32> CconLayer::ap_const_lv32_1 = "1";
const sc_lv<32> CconLayer::ap_const_lv32_25 = "100101";
const sc_lv<8> CconLayer::ap_const_lv8_0 = "00000000";
const sc_lv<32> CconLayer::ap_const_lv32_8 = "1000";
const sc_lv<32> CconLayer::ap_const_lv32_B = "1011";
const sc_lv<64> CconLayer::ap_const_lv64_3FF0000000000000 = "11111111110000000000000000000000000000000000000000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_11 = "10001";
const sc_lv<32> CconLayer::ap_const_lv32_15 = "10101";
const sc_lv<4> CconLayer::ap_const_lv4_A = "1010";
const sc_lv<4> CconLayer::ap_const_lv4_1 = "1";
const sc_lv<6> CconLayer::ap_const_lv6_0 = "000000";
const sc_lv<8> CconLayer::ap_const_lv8_C0 = "11000000";
const sc_lv<8> CconLayer::ap_const_lv8_1 = "1";
const sc_lv<16> CconLayer::ap_const_lv16_0 = "0000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_2F = "101111";
const sc_lv<33> CconLayer::ap_const_lv33_0 = "000000000000000000000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_20 = "100000";
const sc_lv<31> CconLayer::ap_const_lv31_7FFFFFFF = "1111111111111111111111111111111";
const sc_lv<32> CconLayer::ap_const_lv32_1F = "11111";
const sc_lv<31> CconLayer::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_1E = "11110";
const sc_lv<26> CconLayer::ap_const_lv26_0 = "00000000000000000000000000";
const sc_lv<31> CconLayer::ap_const_lv31_1F = "11111";
const sc_lv<6> CconLayer::ap_const_lv6_21 = "100001";
const sc_lv<6> CconLayer::ap_const_lv6_3F = "111111";
const sc_lv<32> CconLayer::ap_const_lv32_17 = "10111";
const sc_lv<8> CconLayer::ap_const_lv8_9E = "10011110";
const sc_lv<8> CconLayer::ap_const_lv8_70 = "1110000";
const sc_lv<8> CconLayer::ap_const_lv8_6F = "1101111";
const sc_lv<32> CconLayer::ap_const_lv32_80000000 = "10000000000000000000000000000000";
const sc_lv<32> CconLayer::ap_const_lv32_3F = "111111";
const sc_lv<32> CconLayer::ap_const_lv32_34 = "110100";
const sc_lv<32> CconLayer::ap_const_lv32_3E = "111110";
const sc_lv<63> CconLayer::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> CconLayer::ap_const_lv12_433 = "10000110011";
const sc_lv<12> CconLayer::ap_const_lv12_10 = "10000";
const sc_lv<12> CconLayer::ap_const_lv12_FF0 = "111111110000";
const sc_lv<54> CconLayer::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<12> CconLayer::ap_const_lv12_36 = "110110";
const sc_lv<7> CconLayer::ap_const_lv7_0 = "0000000";
const sc_lv<32> CconLayer::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";

CconLayer::CconLayer(sc_module_name name) : sc_module(name), mVcdFile(0) {
    cconlayer_k_V_U = new CconLayer_cconlayLf8("cconlayer_k_V_U");
    cconlayer_k_V_U->clk(ap_clk);
    cconlayer_k_V_U->reset(ap_rst);
    cconlayer_k_V_U->address0(cconlayer_k_V_address0);
    cconlayer_k_V_U->ce0(cconlayer_k_V_ce0);
    cconlayer_k_V_U->q0(cconlayer_k_V_q0);
    cconlayer_b_V_U = new CconLayer_cconlayMgi("cconlayer_b_V_U");
    cconlayer_b_V_U->clk(ap_clk);
    cconlayer_b_V_U->reset(ap_rst);
    cconlayer_b_V_U->address0(cconlayer_b_V_address0);
    cconlayer_b_V_U->ce0(cconlayer_b_V_ce0);
    cconlayer_b_V_U->q0(cconlayer_b_V_q0);
    p_temp_U = new CconLayer_p_temp("p_temp_U");
    p_temp_U->clk(ap_clk);
    p_temp_U->reset(ap_rst);
    p_temp_U->address0(p_temp_address0);
    p_temp_U->ce0(p_temp_ce0);
    p_temp_U->we0(p_temp_we0);
    p_temp_U->d0(grp_Reshape_fu_242_dst_V_d0);
    p_temp_U->q0(p_temp_q0);
    grp_Reshape_fu_242 = new Reshape("grp_Reshape_fu_242");
    grp_Reshape_fu_242->ap_clk(ap_clk);
    grp_Reshape_fu_242->ap_rst(ap_rst);
    grp_Reshape_fu_242->ap_start(grp_Reshape_fu_242_ap_start);
    grp_Reshape_fu_242->ap_done(grp_Reshape_fu_242_ap_done);
    grp_Reshape_fu_242->ap_idle(grp_Reshape_fu_242_ap_idle);
    grp_Reshape_fu_242->ap_ready(grp_Reshape_fu_242_ap_ready);
    grp_Reshape_fu_242->src_val_V_address0(grp_Reshape_fu_242_src_val_V_address0);
    grp_Reshape_fu_242->src_val_V_ce0(grp_Reshape_fu_242_src_val_V_ce0);
    grp_Reshape_fu_242->src_val_V_q0(input_val_V_q0);
    grp_Reshape_fu_242->dst_V_address0(grp_Reshape_fu_242_dst_V_address0);
    grp_Reshape_fu_242->dst_V_ce0(grp_Reshape_fu_242_dst_V_ce0);
    grp_Reshape_fu_242->dst_V_we0(grp_Reshape_fu_242_dst_V_we0);
    grp_Reshape_fu_242->dst_V_d0(grp_Reshape_fu_242_dst_V_d0);
    CNN_Core_uitofp_3qcK_U165 = new CNN_Core_uitofp_3qcK<1,2,32,32>("CNN_Core_uitofp_3qcK_U165");
    CNN_Core_uitofp_3qcK_U165->clk(ap_clk);
    CNN_Core_uitofp_3qcK_U165->reset(ap_rst);
    CNN_Core_uitofp_3qcK_U165->din0(tmp32_V_12_reg_1026);
    CNN_Core_uitofp_3qcK_U165->ce(ap_var_for_const0);
    CNN_Core_uitofp_3qcK_U165->dout(grp_fu_250_p1);
    CNN_Core_fptrunc_rcU_U166 = new CNN_Core_fptrunc_rcU<1,1,64,32>("CNN_Core_fptrunc_rcU_U166");
    CNN_Core_fptrunc_rcU_U166->din0(tmp_174_reg_1061);
    CNN_Core_fptrunc_rcU_U166->dout(res_fu_253_p1);
    CNN_Core_fpext_32sc4_U167 = new CNN_Core_fpext_32sc4<1,1,32,64>("CNN_Core_fpext_32sc4_U167");
    CNN_Core_fpext_32sc4_U167->din0(grp_fu_256_p0);
    CNN_Core_fpext_32sc4_U167->dout(grp_fu_256_p1);
    CNN_Core_fexp_32ntde_U168 = new CNN_Core_fexp_32ntde<1,5,32,32,32>("CNN_Core_fexp_32ntde_U168");
    CNN_Core_fexp_32ntde_U168->clk(ap_clk);
    CNN_Core_fexp_32ntde_U168->reset(ap_rst);
    CNN_Core_fexp_32ntde_U168->din0(ap_var_for_const1);
    CNN_Core_fexp_32ntde_U168->din1(x_assign_reg_1041);
    CNN_Core_fexp_32ntde_U168->ce(ap_var_for_const0);
    CNN_Core_fexp_32ntde_U168->dout(grp_fu_260_p2);
    CNN_Core_dadd_64nudo_U169 = new CNN_Core_dadd_64nudo<1,4,64,64,64>("CNN_Core_dadd_64nudo_U169");
    CNN_Core_dadd_64nudo_U169->clk(ap_clk);
    CNN_Core_dadd_64nudo_U169->reset(ap_rst);
    CNN_Core_dadd_64nudo_U169->din0(tmp_172_reg_1051);
    CNN_Core_dadd_64nudo_U169->din1(ap_var_for_const2);
    CNN_Core_dadd_64nudo_U169->ce(ap_var_for_const0);
    CNN_Core_dadd_64nudo_U169->dout(grp_fu_265_p2);
    CNN_Core_ddiv_64nvdy_U170 = new CNN_Core_ddiv_64nvdy<1,15,64,64,64>("CNN_Core_ddiv_64nvdy_U170");
    CNN_Core_ddiv_64nvdy_U170->clk(ap_clk);
    CNN_Core_ddiv_64nvdy_U170->reset(ap_rst);
    CNN_Core_ddiv_64nvdy_U170->din0(ap_var_for_const2);
    CNN_Core_ddiv_64nvdy_U170->din1(tmp_173_reg_1056);
    CNN_Core_ddiv_64nvdy_U170->ce(ap_var_for_const0);
    CNN_Core_ddiv_64nvdy_U170->dout(grp_fu_270_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_fu_715_p2);
    sensitive << ( tmp_176_fu_701_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state37);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state38);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state39);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( exitcond_fu_321_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond4_fu_275_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond4_fu_275_p2 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_cconlayer_b_V_address0);
    sensitive << ( tmp_s_fu_390_p1 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_cconlayer_b_V_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_cconlayer_k_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_191_fu_342_p1 );

    SC_METHOD(thread_cconlayer_k_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_cconlayer_output_V_address0);
    sensitive << ( tmp_s_reg_980 );
    sensitive << ( ap_CS_fsm_state39 );

    SC_METHOD(thread_cconlayer_output_V_ce0);
    sensitive << ( ap_CS_fsm_state39 );

    SC_METHOD(thread_cconlayer_output_V_d0);
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( or_cond6_fu_927_p2 );
    sensitive << ( newSel8_fu_919_p3 );

    SC_METHOD(thread_cconlayer_output_V_we0);
    sensitive << ( ap_CS_fsm_state39 );

    SC_METHOD(thread_exitcond4_fu_275_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_reg_207 );

    SC_METHOD(thread_exitcond_fu_321_p2);
    sensitive << ( j_reg_231 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exp_tmp_V_fu_691_p4);
    sensitive << ( ireg_V_fu_675_p1 );

    SC_METHOD(thread_grp_Reshape_fu_242_ap_start);
    sensitive << ( grp_Reshape_fu_242_ap_start_reg );

    SC_METHOD(thread_grp_fu_256_p0);
    sensitive << ( tmp_i_i_reg_1046 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( res_fu_253_p1 );

    SC_METHOD(thread_i_16_fu_281_p2);
    sensitive << ( i_reg_207 );

    SC_METHOD(thread_icmp4_fu_798_p2);
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( tmp_231_fu_788_p4 );

    SC_METHOD(thread_icmp_fu_516_p2);
    sensitive << ( tmp_163_reg_990 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_215_fu_506_p4 );

    SC_METHOD(thread_input_val_V_address0);
    sensitive << ( grp_Reshape_fu_242_src_val_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_input_val_V_ce0);
    sensitive << ( grp_Reshape_fu_242_src_val_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ireg_V_fu_675_p1);
    sensitive << ( grp_fu_256_p1 );

    SC_METHOD(thread_is_neg_fu_425_p3);
    sensitive << ( p_Val2_49_fu_407_p2 );

    SC_METHOD(thread_j_14_fu_327_p2);
    sensitive << ( j_reg_231 );

    SC_METHOD(thread_j_cast2_fu_317_p1);
    sensitive << ( j_reg_231 );

    SC_METHOD(thread_man_V_3_fu_756_p2);
    sensitive << ( p_Result_10_fu_752_p1 );

    SC_METHOD(thread_man_V_4_fu_762_p3);
    sensitive << ( isneg_reg_1066 );
    sensitive << ( p_Result_10_fu_752_p1 );
    sensitive << ( man_V_3_fu_756_p2 );

    SC_METHOD(thread_msb_idx_2_fu_498_p3);
    sensitive << ( tmp_214_fu_490_p3 );
    sensitive << ( tmp_213_fu_486_p1 );

    SC_METHOD(thread_msb_idx_fu_480_p2);
    sensitive << ( num_zeros_fu_476_p1 );

    SC_METHOD(thread_newSel7_fu_905_p3);
    sensitive << ( tmp_230_fu_778_p1 );
    sensitive << ( sel_tmp8_fu_856_p2 );
    sensitive << ( tmp_232_fu_814_p1 );

    SC_METHOD(thread_newSel8_fu_919_p3);
    sensitive << ( or_cond_fu_899_p2 );
    sensitive << ( newSel_fu_891_p3 );
    sensitive << ( newSel7_fu_905_p3 );

    SC_METHOD(thread_newSel_fu_891_p3);
    sensitive << ( sel_tmp3_fu_885_p2 );
    sensitive << ( tmp_189_fu_825_p2 );
    sensitive << ( this_assign_fu_818_p3 );

    SC_METHOD(thread_num_zeros_fu_476_p1);
    sensitive << ( tmp_164_fu_468_p3 );

    SC_METHOD(thread_or_cond5_fu_913_p2);
    sensitive << ( sel_tmp8_fu_856_p2 );
    sensitive << ( sel_tmp2_fu_836_p2 );

    SC_METHOD(thread_or_cond6_fu_927_p2);
    sensitive << ( or_cond_fu_899_p2 );
    sensitive << ( or_cond5_fu_913_p2 );

    SC_METHOD(thread_or_cond_fu_899_p2);
    sensitive << ( sel_tmp3_fu_885_p2 );
    sensitive << ( sel_tmp5_fu_868_p2 );

    SC_METHOD(thread_p_Repl2_5_trunc_fu_634_p2);
    sensitive << ( tmp24_cast_cast_fu_626_p3 );
    sensitive << ( tmp_226_fu_623_p1 );

    SC_METHOD(thread_p_Result_10_fu_752_p1);
    sensitive << ( tmp_177_fu_745_p3 );

    SC_METHOD(thread_p_Result_16_op_fu_658_p2);
    sensitive << ( p_Result_9_fu_647_p5 );

    SC_METHOD(thread_p_Result_8_fu_460_p3);
    sensitive << ( p_Result_s_fu_450_p4 );

    SC_METHOD(thread_p_Result_9_fu_647_p5);
    sensitive << ( tmp32_V_15_reg_1031 );
    sensitive << ( tmp_171_fu_640_p3 );

    SC_METHOD(thread_p_Result_s_fu_450_p4);
    sensitive << ( p_Val2_48_cast_fu_447_p1 );

    SC_METHOD(thread_p_Val2_17_fu_360_p0);
    sensitive << ( cconlayer_k_V_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_17_fu_360_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( p_temp_q0 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_p_Val2_17_fu_360_p2);
    sensitive << ( p_Val2_17_fu_360_p0 );
    sensitive << ( p_Val2_17_fu_360_p1 );

    SC_METHOD(thread_p_Val2_18_fu_374_p2);
    sensitive << ( tmp_193_fu_366_p3 );
    sensitive << ( p_Val2_17_fu_360_p2 );

    SC_METHOD(thread_p_Val2_46_cast_fu_413_p2);
    sensitive << ( p_Val2_s_reg_219 );
    sensitive << ( tmp_75_fu_403_p1 );

    SC_METHOD(thread_p_Val2_48_cast_fu_447_p1);
    sensitive << ( p_Val2_52_reg_1000 );

    SC_METHOD(thread_p_Val2_49_fu_407_p2);
    sensitive << ( tmp_161_fu_395_p1 );
    sensitive << ( tmp_162_fu_399_p1 );

    SC_METHOD(thread_p_Val2_52_fu_439_p3);
    sensitive << ( is_neg_fu_425_p3 );
    sensitive << ( p_Val2_46_cast_fu_413_p2 );
    sensitive << ( tmp_239_cast_fu_433_p2 );

    SC_METHOD(thread_p_shl2_cast_fu_307_p1);
    sensitive << ( p_shl2_fu_299_p3 );

    SC_METHOD(thread_p_shl2_fu_299_p3);
    sensitive << ( i_reg_207 );

    SC_METHOD(thread_p_shl_cast_fu_295_p1);
    sensitive << ( p_shl_fu_287_p3 );

    SC_METHOD(thread_p_shl_fu_287_p3);
    sensitive << ( i_reg_207 );

    SC_METHOD(thread_p_temp_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_Reshape_fu_242_dst_V_address0 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_192_fu_347_p1 );

    SC_METHOD(thread_p_temp_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( grp_Reshape_fu_242_dst_V_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_p_temp_we0);
    sensitive << ( grp_Reshape_fu_242_dst_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_sel_tmp1_fu_831_p2);
    sensitive << ( tmp_178_reg_1077 );

    SC_METHOD(thread_sel_tmp21_demorgan_fu_874_p2);
    sensitive << ( tmp_179_reg_1083 );
    sensitive << ( sel_tmp6_demorgan_fu_841_p2 );

    SC_METHOD(thread_sel_tmp2_fu_836_p2);
    sensitive << ( tmp_182_reg_1100 );
    sensitive << ( sel_tmp1_fu_831_p2 );

    SC_METHOD(thread_sel_tmp3_fu_885_p2);
    sensitive << ( icmp4_fu_798_p2 );
    sensitive << ( sel_tmp9_fu_879_p2 );

    SC_METHOD(thread_sel_tmp5_fu_868_p2);
    sensitive << ( sel_tmp7_fu_851_p2 );
    sensitive << ( sel_tmp_fu_862_p2 );

    SC_METHOD(thread_sel_tmp6_demorgan_fu_841_p2);
    sensitive << ( tmp_178_reg_1077 );
    sensitive << ( tmp_182_reg_1100 );

    SC_METHOD(thread_sel_tmp6_fu_845_p2);
    sensitive << ( sel_tmp6_demorgan_fu_841_p2 );

    SC_METHOD(thread_sel_tmp7_fu_851_p2);
    sensitive << ( tmp_179_reg_1083 );
    sensitive << ( sel_tmp6_fu_845_p2 );

    SC_METHOD(thread_sel_tmp8_fu_856_p2);
    sensitive << ( sel_tmp7_fu_851_p2 );
    sensitive << ( tmp_184_fu_782_p2 );

    SC_METHOD(thread_sel_tmp9_fu_879_p2);
    sensitive << ( sel_tmp21_demorgan_fu_874_p2 );

    SC_METHOD(thread_sel_tmp_fu_862_p2);
    sensitive << ( tmp_184_fu_782_p2 );

    SC_METHOD(thread_sh_amt_cast_fu_774_p1);
    sensitive << ( sh_amt_fu_769_p3 );

    SC_METHOD(thread_sh_amt_fu_769_p3);
    sensitive << ( tmp_179_reg_1083 );
    sensitive << ( tmp_180_reg_1090 );
    sensitive << ( tmp_181_reg_1095 );

    SC_METHOD(thread_this_assign_fu_818_p3);
    sensitive << ( isneg_reg_1066 );

    SC_METHOD(thread_tmp24_cast_cast_fu_626_p3);
    sensitive << ( tmp_169_fu_618_p2 );

    SC_METHOD(thread_tmp32_V_12_fu_598_p3);
    sensitive << ( icmp_reg_1016 );
    sensitive << ( tmp32_V_reg_1021 );
    sensitive << ( tmp32_V_9_fu_593_p2 );

    SC_METHOD(thread_tmp32_V_15_fu_604_p1);
    sensitive << ( grp_fu_250_p1 );

    SC_METHOD(thread_tmp32_V_9_fu_593_p2);
    sensitive << ( p_Val2_52_reg_1000 );
    sensitive << ( tmp_243_cast_fu_589_p1 );

    SC_METHOD(thread_tmp32_V_fu_580_p1);
    sensitive << ( tmp_224_fu_574_p2 );

    SC_METHOD(thread_tmp_161_fu_395_p1);
    sensitive << ( p_Val2_s_reg_219 );

    SC_METHOD(thread_tmp_162_fu_399_p0);
    sensitive << ( cconlayer_b_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_162_fu_399_p1);
    sensitive << ( tmp_162_fu_399_p0 );

    SC_METHOD(thread_tmp_163_fu_419_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_Val2_49_fu_407_p2 );

    SC_METHOD(thread_tmp_164_fu_468_p3);
    sensitive << ( p_Result_8_fu_460_p3 );

    SC_METHOD(thread_tmp_167_fu_584_p2);
    sensitive << ( msb_idx_2_reg_1011 );

    SC_METHOD(thread_tmp_169_fu_618_p2);
    sensitive << ( tmp_163_reg_990 );
    sensitive << ( p_Result_s_206_reg_1036 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_tmp_171_fu_640_p3);
    sensitive << ( is_neg_reg_995 );
    sensitive << ( p_Repl2_5_trunc_fu_634_p2 );

    SC_METHOD(thread_tmp_176_fu_701_p1);
    sensitive << ( exp_tmp_V_fu_691_p4 );

    SC_METHOD(thread_tmp_177_fu_745_p3);
    sensitive << ( tmp_229_reg_1072 );

    SC_METHOD(thread_tmp_178_fu_709_p2);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( tmp_227_fu_679_p1 );

    SC_METHOD(thread_tmp_179_fu_721_p2);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( F2_fu_715_p2 );

    SC_METHOD(thread_tmp_180_fu_727_p2);
    sensitive << ( F2_fu_715_p2 );

    SC_METHOD(thread_tmp_181_fu_733_p2);
    sensitive << ( F2_fu_715_p2 );

    SC_METHOD(thread_tmp_182_fu_739_p2);
    sensitive << ( ap_CS_fsm_state38 );
    sensitive << ( F2_fu_715_p2 );

    SC_METHOD(thread_tmp_184_fu_782_p2);
    sensitive << ( ap_CS_fsm_state39 );
    sensitive << ( sh_amt_fu_769_p3 );

    SC_METHOD(thread_tmp_186_fu_804_p1);
    sensitive << ( sh_amt_cast_fu_774_p1 );

    SC_METHOD(thread_tmp_187_fu_808_p2);
    sensitive << ( man_V_4_fu_762_p3 );
    sensitive << ( tmp_186_fu_804_p1 );

    SC_METHOD(thread_tmp_189_fu_825_p2);
    sensitive << ( sh_amt_cast_fu_774_p1 );
    sensitive << ( tmp_230_fu_778_p1 );

    SC_METHOD(thread_tmp_190_fu_333_p2);
    sensitive << ( tmp_reg_951 );
    sensitive << ( j_cast2_fu_317_p1 );

    SC_METHOD(thread_tmp_191_fu_342_p1);
    sensitive << ( tmp_232_cast_fu_338_p1 );

    SC_METHOD(thread_tmp_192_fu_347_p1);
    sensitive << ( j_reg_231 );

    SC_METHOD(thread_tmp_193_fu_366_p3);
    sensitive << ( p_Val2_s_reg_219 );

    SC_METHOD(thread_tmp_213_fu_486_p1);
    sensitive << ( msb_idx_fu_480_p2 );

    SC_METHOD(thread_tmp_214_fu_490_p3);
    sensitive << ( msb_idx_fu_480_p2 );

    SC_METHOD(thread_tmp_215_fu_506_p4);
    sensitive << ( msb_idx_2_fu_498_p3 );

    SC_METHOD(thread_tmp_216_fu_522_p1);
    sensitive << ( msb_idx_2_fu_498_p3 );

    SC_METHOD(thread_tmp_217_fu_526_p2);
    sensitive << ( tmp_163_reg_990 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( msb_idx_2_fu_498_p3 );

    SC_METHOD(thread_tmp_218_fu_532_p2);
    sensitive << ( tmp_216_fu_522_p1 );

    SC_METHOD(thread_tmp_219_fu_538_p4);
    sensitive << ( p_Val2_48_cast_fu_447_p1 );

    SC_METHOD(thread_tmp_220_fu_548_p2);
    sensitive << ( tmp_216_fu_522_p1 );

    SC_METHOD(thread_tmp_221_fu_554_p3);
    sensitive << ( p_Val2_48_cast_fu_447_p1 );
    sensitive << ( tmp_217_fu_526_p2 );
    sensitive << ( tmp_219_fu_538_p4 );

    SC_METHOD(thread_tmp_222_fu_562_p3);
    sensitive << ( tmp_217_fu_526_p2 );
    sensitive << ( tmp_220_fu_548_p2 );
    sensitive << ( tmp_218_fu_532_p2 );

    SC_METHOD(thread_tmp_223_fu_570_p1);
    sensitive << ( tmp_222_fu_562_p3 );

    SC_METHOD(thread_tmp_224_fu_574_p2);
    sensitive << ( tmp_221_fu_554_p3 );
    sensitive << ( tmp_223_fu_570_p1 );

    SC_METHOD(thread_tmp_226_fu_623_p1);
    sensitive << ( msb_idx_reg_1006 );

    SC_METHOD(thread_tmp_227_fu_679_p1);
    sensitive << ( ireg_V_fu_675_p1 );

    SC_METHOD(thread_tmp_229_fu_705_p1);
    sensitive << ( ireg_V_fu_675_p1 );

    SC_METHOD(thread_tmp_230_fu_778_p1);
    sensitive << ( man_V_4_fu_762_p3 );

    SC_METHOD(thread_tmp_231_fu_788_p4);
    sensitive << ( sh_amt_fu_769_p3 );

    SC_METHOD(thread_tmp_232_cast_fu_338_p1);
    sensitive << ( tmp_190_fu_333_p2 );

    SC_METHOD(thread_tmp_232_fu_814_p1);
    sensitive << ( tmp_187_fu_808_p2 );

    SC_METHOD(thread_tmp_239_cast_fu_433_p2);
    sensitive << ( p_Val2_46_cast_fu_413_p2 );

    SC_METHOD(thread_tmp_243_cast_fu_589_p1);
    sensitive << ( tmp_167_fu_584_p2 );

    SC_METHOD(thread_tmp_75_fu_403_p0);
    sensitive << ( cconlayer_b_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_75_fu_403_p1);
    sensitive << ( tmp_75_fu_403_p0 );

    SC_METHOD(thread_tmp_76_fu_664_p1);
    sensitive << ( p_Result_16_op_fu_658_p2 );

    SC_METHOD(thread_tmp_fu_311_p2);
    sensitive << ( p_shl_cast_fu_295_p1 );
    sensitive << ( p_shl2_cast_fu_307_p1 );

    SC_METHOD(thread_tmp_s_fu_390_p1);
    sensitive << ( i_reg_207 );

    SC_METHOD(thread_x_assign_fu_668_p3);
    sensitive << ( tmp_163_reg_990 );
    sensitive << ( tmp_76_fu_664_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( exitcond4_fu_275_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond_fu_321_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( grp_Reshape_fu_242_ap_done );
    sensitive << ( ap_CS_fsm_state2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const2);

    ap_CS_fsm = "00000000000000000000000000000000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    grp_Reshape_fu_242_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "CconLayer_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_val_V_address0, "(port)input_val_V_address0");
    sc_trace(mVcdFile, input_val_V_ce0, "(port)input_val_V_ce0");
    sc_trace(mVcdFile, input_val_V_q0, "(port)input_val_V_q0");
    sc_trace(mVcdFile, cconlayer_output_V_address0, "(port)cconlayer_output_V_address0");
    sc_trace(mVcdFile, cconlayer_output_V_ce0, "(port)cconlayer_output_V_ce0");
    sc_trace(mVcdFile, cconlayer_output_V_we0, "(port)cconlayer_output_V_we0");
    sc_trace(mVcdFile, cconlayer_output_V_d0, "(port)cconlayer_output_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, cconlayer_k_V_address0, "cconlayer_k_V_address0");
    sc_trace(mVcdFile, cconlayer_k_V_ce0, "cconlayer_k_V_ce0");
    sc_trace(mVcdFile, cconlayer_k_V_q0, "cconlayer_k_V_q0");
    sc_trace(mVcdFile, cconlayer_b_V_address0, "cconlayer_b_V_address0");
    sc_trace(mVcdFile, cconlayer_b_V_ce0, "cconlayer_b_V_ce0");
    sc_trace(mVcdFile, cconlayer_b_V_q0, "cconlayer_b_V_q0");
    sc_trace(mVcdFile, p_Val2_s_reg_219, "p_Val2_s_reg_219");
    sc_trace(mVcdFile, j_reg_231, "j_reg_231");
    sc_trace(mVcdFile, exitcond4_fu_275_p2, "exitcond4_fu_275_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_16_fu_281_p2, "i_16_fu_281_p2");
    sc_trace(mVcdFile, i_16_reg_946, "i_16_reg_946");
    sc_trace(mVcdFile, tmp_fu_311_p2, "tmp_fu_311_p2");
    sc_trace(mVcdFile, tmp_reg_951, "tmp_reg_951");
    sc_trace(mVcdFile, exitcond_fu_321_p2, "exitcond_fu_321_p2");
    sc_trace(mVcdFile, exitcond_reg_956, "exitcond_reg_956");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_14_fu_327_p2, "j_14_fu_327_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, tmp_s_fu_390_p1, "tmp_s_fu_390_p1");
    sc_trace(mVcdFile, tmp_s_reg_980, "tmp_s_reg_980");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_163_fu_419_p2, "tmp_163_fu_419_p2");
    sc_trace(mVcdFile, tmp_163_reg_990, "tmp_163_reg_990");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, is_neg_fu_425_p3, "is_neg_fu_425_p3");
    sc_trace(mVcdFile, is_neg_reg_995, "is_neg_reg_995");
    sc_trace(mVcdFile, p_Val2_52_fu_439_p3, "p_Val2_52_fu_439_p3");
    sc_trace(mVcdFile, p_Val2_52_reg_1000, "p_Val2_52_reg_1000");
    sc_trace(mVcdFile, msb_idx_fu_480_p2, "msb_idx_fu_480_p2");
    sc_trace(mVcdFile, msb_idx_reg_1006, "msb_idx_reg_1006");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, msb_idx_2_fu_498_p3, "msb_idx_2_fu_498_p3");
    sc_trace(mVcdFile, msb_idx_2_reg_1011, "msb_idx_2_reg_1011");
    sc_trace(mVcdFile, icmp_fu_516_p2, "icmp_fu_516_p2");
    sc_trace(mVcdFile, icmp_reg_1016, "icmp_reg_1016");
    sc_trace(mVcdFile, tmp32_V_fu_580_p1, "tmp32_V_fu_580_p1");
    sc_trace(mVcdFile, tmp32_V_reg_1021, "tmp32_V_reg_1021");
    sc_trace(mVcdFile, tmp32_V_12_fu_598_p3, "tmp32_V_12_fu_598_p3");
    sc_trace(mVcdFile, tmp32_V_12_reg_1026, "tmp32_V_12_reg_1026");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp32_V_15_fu_604_p1, "tmp32_V_15_fu_604_p1");
    sc_trace(mVcdFile, tmp32_V_15_reg_1031, "tmp32_V_15_reg_1031");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, p_Result_s_206_reg_1036, "p_Result_s_206_reg_1036");
    sc_trace(mVcdFile, x_assign_fu_668_p3, "x_assign_fu_668_p3");
    sc_trace(mVcdFile, x_assign_reg_1041, "x_assign_reg_1041");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_260_p2, "grp_fu_260_p2");
    sc_trace(mVcdFile, tmp_i_i_reg_1046, "tmp_i_i_reg_1046");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_256_p1, "grp_fu_256_p1");
    sc_trace(mVcdFile, tmp_172_reg_1051, "tmp_172_reg_1051");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, grp_fu_265_p2, "grp_fu_265_p2");
    sc_trace(mVcdFile, tmp_173_reg_1056, "tmp_173_reg_1056");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, grp_fu_270_p2, "grp_fu_270_p2");
    sc_trace(mVcdFile, tmp_174_reg_1061, "tmp_174_reg_1061");
    sc_trace(mVcdFile, ap_CS_fsm_state37, "ap_CS_fsm_state37");
    sc_trace(mVcdFile, isneg_reg_1066, "isneg_reg_1066");
    sc_trace(mVcdFile, ap_CS_fsm_state38, "ap_CS_fsm_state38");
    sc_trace(mVcdFile, tmp_229_fu_705_p1, "tmp_229_fu_705_p1");
    sc_trace(mVcdFile, tmp_229_reg_1072, "tmp_229_reg_1072");
    sc_trace(mVcdFile, tmp_178_fu_709_p2, "tmp_178_fu_709_p2");
    sc_trace(mVcdFile, tmp_178_reg_1077, "tmp_178_reg_1077");
    sc_trace(mVcdFile, tmp_179_fu_721_p2, "tmp_179_fu_721_p2");
    sc_trace(mVcdFile, tmp_179_reg_1083, "tmp_179_reg_1083");
    sc_trace(mVcdFile, tmp_180_fu_727_p2, "tmp_180_fu_727_p2");
    sc_trace(mVcdFile, tmp_180_reg_1090, "tmp_180_reg_1090");
    sc_trace(mVcdFile, tmp_181_fu_733_p2, "tmp_181_fu_733_p2");
    sc_trace(mVcdFile, tmp_181_reg_1095, "tmp_181_reg_1095");
    sc_trace(mVcdFile, tmp_182_fu_739_p2, "tmp_182_fu_739_p2");
    sc_trace(mVcdFile, tmp_182_reg_1100, "tmp_182_reg_1100");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, p_temp_address0, "p_temp_address0");
    sc_trace(mVcdFile, p_temp_ce0, "p_temp_ce0");
    sc_trace(mVcdFile, p_temp_we0, "p_temp_we0");
    sc_trace(mVcdFile, p_temp_q0, "p_temp_q0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_ap_start, "grp_Reshape_fu_242_ap_start");
    sc_trace(mVcdFile, grp_Reshape_fu_242_ap_done, "grp_Reshape_fu_242_ap_done");
    sc_trace(mVcdFile, grp_Reshape_fu_242_ap_idle, "grp_Reshape_fu_242_ap_idle");
    sc_trace(mVcdFile, grp_Reshape_fu_242_ap_ready, "grp_Reshape_fu_242_ap_ready");
    sc_trace(mVcdFile, grp_Reshape_fu_242_src_val_V_address0, "grp_Reshape_fu_242_src_val_V_address0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_src_val_V_ce0, "grp_Reshape_fu_242_src_val_V_ce0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_dst_V_address0, "grp_Reshape_fu_242_dst_V_address0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_dst_V_ce0, "grp_Reshape_fu_242_dst_V_ce0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_dst_V_we0, "grp_Reshape_fu_242_dst_V_we0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_dst_V_d0, "grp_Reshape_fu_242_dst_V_d0");
    sc_trace(mVcdFile, i_reg_207, "i_reg_207");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state39, "ap_CS_fsm_state39");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, grp_Reshape_fu_242_ap_start_reg, "grp_Reshape_fu_242_ap_start_reg");
    sc_trace(mVcdFile, tmp_191_fu_342_p1, "tmp_191_fu_342_p1");
    sc_trace(mVcdFile, tmp_192_fu_347_p1, "tmp_192_fu_347_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_256_p0, "grp_fu_256_p0");
    sc_trace(mVcdFile, res_fu_253_p1, "res_fu_253_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, p_shl_fu_287_p3, "p_shl_fu_287_p3");
    sc_trace(mVcdFile, p_shl2_fu_299_p3, "p_shl2_fu_299_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_295_p1, "p_shl_cast_fu_295_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_307_p1, "p_shl2_cast_fu_307_p1");
    sc_trace(mVcdFile, j_cast2_fu_317_p1, "j_cast2_fu_317_p1");
    sc_trace(mVcdFile, tmp_190_fu_333_p2, "tmp_190_fu_333_p2");
    sc_trace(mVcdFile, tmp_232_cast_fu_338_p1, "tmp_232_cast_fu_338_p1");
    sc_trace(mVcdFile, p_Val2_17_fu_360_p0, "p_Val2_17_fu_360_p0");
    sc_trace(mVcdFile, p_Val2_17_fu_360_p1, "p_Val2_17_fu_360_p1");
    sc_trace(mVcdFile, tmp_193_fu_366_p3, "tmp_193_fu_366_p3");
    sc_trace(mVcdFile, p_Val2_17_fu_360_p2, "p_Val2_17_fu_360_p2");
    sc_trace(mVcdFile, p_Val2_18_fu_374_p2, "p_Val2_18_fu_374_p2");
    sc_trace(mVcdFile, tmp_162_fu_399_p0, "tmp_162_fu_399_p0");
    sc_trace(mVcdFile, tmp_75_fu_403_p0, "tmp_75_fu_403_p0");
    sc_trace(mVcdFile, tmp_161_fu_395_p1, "tmp_161_fu_395_p1");
    sc_trace(mVcdFile, tmp_162_fu_399_p1, "tmp_162_fu_399_p1");
    sc_trace(mVcdFile, tmp_75_fu_403_p1, "tmp_75_fu_403_p1");
    sc_trace(mVcdFile, p_Val2_49_fu_407_p2, "p_Val2_49_fu_407_p2");
    sc_trace(mVcdFile, p_Val2_46_cast_fu_413_p2, "p_Val2_46_cast_fu_413_p2");
    sc_trace(mVcdFile, tmp_239_cast_fu_433_p2, "tmp_239_cast_fu_433_p2");
    sc_trace(mVcdFile, p_Val2_48_cast_fu_447_p1, "p_Val2_48_cast_fu_447_p1");
    sc_trace(mVcdFile, p_Result_s_fu_450_p4, "p_Result_s_fu_450_p4");
    sc_trace(mVcdFile, p_Result_8_fu_460_p3, "p_Result_8_fu_460_p3");
    sc_trace(mVcdFile, tmp_164_fu_468_p3, "tmp_164_fu_468_p3");
    sc_trace(mVcdFile, num_zeros_fu_476_p1, "num_zeros_fu_476_p1");
    sc_trace(mVcdFile, tmp_214_fu_490_p3, "tmp_214_fu_490_p3");
    sc_trace(mVcdFile, tmp_213_fu_486_p1, "tmp_213_fu_486_p1");
    sc_trace(mVcdFile, tmp_215_fu_506_p4, "tmp_215_fu_506_p4");
    sc_trace(mVcdFile, tmp_216_fu_522_p1, "tmp_216_fu_522_p1");
    sc_trace(mVcdFile, tmp_217_fu_526_p2, "tmp_217_fu_526_p2");
    sc_trace(mVcdFile, tmp_219_fu_538_p4, "tmp_219_fu_538_p4");
    sc_trace(mVcdFile, tmp_220_fu_548_p2, "tmp_220_fu_548_p2");
    sc_trace(mVcdFile, tmp_218_fu_532_p2, "tmp_218_fu_532_p2");
    sc_trace(mVcdFile, tmp_222_fu_562_p3, "tmp_222_fu_562_p3");
    sc_trace(mVcdFile, tmp_221_fu_554_p3, "tmp_221_fu_554_p3");
    sc_trace(mVcdFile, tmp_223_fu_570_p1, "tmp_223_fu_570_p1");
    sc_trace(mVcdFile, tmp_224_fu_574_p2, "tmp_224_fu_574_p2");
    sc_trace(mVcdFile, tmp_167_fu_584_p2, "tmp_167_fu_584_p2");
    sc_trace(mVcdFile, tmp_243_cast_fu_589_p1, "tmp_243_cast_fu_589_p1");
    sc_trace(mVcdFile, tmp32_V_9_fu_593_p2, "tmp32_V_9_fu_593_p2");
    sc_trace(mVcdFile, grp_fu_250_p1, "grp_fu_250_p1");
    sc_trace(mVcdFile, tmp_169_fu_618_p2, "tmp_169_fu_618_p2");
    sc_trace(mVcdFile, tmp24_cast_cast_fu_626_p3, "tmp24_cast_cast_fu_626_p3");
    sc_trace(mVcdFile, tmp_226_fu_623_p1, "tmp_226_fu_623_p1");
    sc_trace(mVcdFile, p_Repl2_5_trunc_fu_634_p2, "p_Repl2_5_trunc_fu_634_p2");
    sc_trace(mVcdFile, tmp_171_fu_640_p3, "tmp_171_fu_640_p3");
    sc_trace(mVcdFile, p_Result_9_fu_647_p5, "p_Result_9_fu_647_p5");
    sc_trace(mVcdFile, p_Result_16_op_fu_658_p2, "p_Result_16_op_fu_658_p2");
    sc_trace(mVcdFile, tmp_76_fu_664_p1, "tmp_76_fu_664_p1");
    sc_trace(mVcdFile, ireg_V_fu_675_p1, "ireg_V_fu_675_p1");
    sc_trace(mVcdFile, exp_tmp_V_fu_691_p4, "exp_tmp_V_fu_691_p4");
    sc_trace(mVcdFile, tmp_227_fu_679_p1, "tmp_227_fu_679_p1");
    sc_trace(mVcdFile, tmp_176_fu_701_p1, "tmp_176_fu_701_p1");
    sc_trace(mVcdFile, F2_fu_715_p2, "F2_fu_715_p2");
    sc_trace(mVcdFile, tmp_177_fu_745_p3, "tmp_177_fu_745_p3");
    sc_trace(mVcdFile, p_Result_10_fu_752_p1, "p_Result_10_fu_752_p1");
    sc_trace(mVcdFile, man_V_3_fu_756_p2, "man_V_3_fu_756_p2");
    sc_trace(mVcdFile, sh_amt_fu_769_p3, "sh_amt_fu_769_p3");
    sc_trace(mVcdFile, man_V_4_fu_762_p3, "man_V_4_fu_762_p3");
    sc_trace(mVcdFile, tmp_231_fu_788_p4, "tmp_231_fu_788_p4");
    sc_trace(mVcdFile, sh_amt_cast_fu_774_p1, "sh_amt_cast_fu_774_p1");
    sc_trace(mVcdFile, tmp_186_fu_804_p1, "tmp_186_fu_804_p1");
    sc_trace(mVcdFile, tmp_187_fu_808_p2, "tmp_187_fu_808_p2");
    sc_trace(mVcdFile, tmp_230_fu_778_p1, "tmp_230_fu_778_p1");
    sc_trace(mVcdFile, sel_tmp1_fu_831_p2, "sel_tmp1_fu_831_p2");
    sc_trace(mVcdFile, sel_tmp6_demorgan_fu_841_p2, "sel_tmp6_demorgan_fu_841_p2");
    sc_trace(mVcdFile, sel_tmp6_fu_845_p2, "sel_tmp6_fu_845_p2");
    sc_trace(mVcdFile, sel_tmp7_fu_851_p2, "sel_tmp7_fu_851_p2");
    sc_trace(mVcdFile, tmp_184_fu_782_p2, "tmp_184_fu_782_p2");
    sc_trace(mVcdFile, sel_tmp_fu_862_p2, "sel_tmp_fu_862_p2");
    sc_trace(mVcdFile, sel_tmp21_demorgan_fu_874_p2, "sel_tmp21_demorgan_fu_874_p2");
    sc_trace(mVcdFile, icmp4_fu_798_p2, "icmp4_fu_798_p2");
    sc_trace(mVcdFile, sel_tmp9_fu_879_p2, "sel_tmp9_fu_879_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_885_p2, "sel_tmp3_fu_885_p2");
    sc_trace(mVcdFile, tmp_189_fu_825_p2, "tmp_189_fu_825_p2");
    sc_trace(mVcdFile, this_assign_fu_818_p3, "this_assign_fu_818_p3");
    sc_trace(mVcdFile, sel_tmp5_fu_868_p2, "sel_tmp5_fu_868_p2");
    sc_trace(mVcdFile, sel_tmp8_fu_856_p2, "sel_tmp8_fu_856_p2");
    sc_trace(mVcdFile, tmp_232_fu_814_p1, "tmp_232_fu_814_p1");
    sc_trace(mVcdFile, sel_tmp2_fu_836_p2, "sel_tmp2_fu_836_p2");
    sc_trace(mVcdFile, or_cond_fu_899_p2, "or_cond_fu_899_p2");
    sc_trace(mVcdFile, newSel_fu_891_p3, "newSel_fu_891_p3");
    sc_trace(mVcdFile, newSel7_fu_905_p3, "newSel7_fu_905_p3");
    sc_trace(mVcdFile, or_cond5_fu_913_p2, "or_cond5_fu_913_p2");
    sc_trace(mVcdFile, or_cond6_fu_927_p2, "or_cond6_fu_927_p2");
    sc_trace(mVcdFile, newSel8_fu_919_p3, "newSel8_fu_919_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

CconLayer::~CconLayer() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete cconlayer_k_V_U;
    delete cconlayer_b_V_U;
    delete p_temp_U;
    delete grp_Reshape_fu_242;
    delete CNN_Core_uitofp_3qcK_U165;
    delete CNN_Core_fptrunc_rcU_U166;
    delete CNN_Core_fpext_32sc4_U167;
    delete CNN_Core_fexp_32ntde_U168;
    delete CNN_Core_dadd_64nudo_U169;
    delete CNN_Core_ddiv_64nvdy_U170;
}

void CconLayer::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void CconLayer::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv32_0;
}

void CconLayer::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv64_3FF0000000000000;
}

void CconLayer::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_0) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_Reshape_fu_242_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            grp_Reshape_fu_242_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_Reshape_fu_242_ap_ready.read())) {
            grp_Reshape_fu_242_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        i_reg_207 = i_16_reg_946.read();
    } else if ((esl_seteq<1,1,1>(grp_Reshape_fu_242_ap_done.read(), ap_const_logic_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        i_reg_207 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_321_p2.read()))) {
        j_reg_231 = j_14_fu_327_p2.read();
    } else if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        j_reg_231 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_reg_956.read()))) {
        p_Val2_s_reg_219 = p_Val2_18_fu_374_p2.read().range(47, 16);
    } else if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        p_Val2_s_reg_219 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_reg_956 = exitcond_fu_321_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_16_reg_946 = i_16_fu_281_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_163_reg_990.read()))) {
        icmp_reg_1016 = icmp_fu_516_p2.read();
        msb_idx_2_reg_1011 = msb_idx_2_fu_498_p3.read();
        msb_idx_reg_1006 = msb_idx_fu_480_p2.read();
        tmp32_V_reg_1021 = tmp32_V_fu_580_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        is_neg_reg_995 = p_Val2_49_fu_407_p2.read().range(32, 32);
        p_Val2_52_reg_1000 = p_Val2_52_fu_439_p3.read();
        tmp_163_reg_990 = tmp_163_fu_419_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        isneg_reg_1066 = ireg_V_fu_675_p1.read().range(63, 63);
        tmp_178_reg_1077 = tmp_178_fu_709_p2.read();
        tmp_179_reg_1083 = tmp_179_fu_721_p2.read();
        tmp_180_reg_1090 = tmp_180_fu_727_p2.read();
        tmp_181_reg_1095 = tmp_181_fu_733_p2.read();
        tmp_182_reg_1100 = tmp_182_fu_739_p2.read();
        tmp_229_reg_1072 = tmp_229_fu_705_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_163_reg_990.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        p_Result_s_206_reg_1036 = tmp32_V_15_fu_604_p1.read().range(30, 23);
        tmp32_V_15_reg_1031 = tmp32_V_15_fu_604_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, tmp_163_reg_990.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        tmp32_V_12_reg_1026 = tmp32_V_12_fu_598_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        tmp_172_reg_1051 = grp_fu_256_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        tmp_173_reg_1056 = grp_fu_265_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state37.read())) {
        tmp_174_reg_1061 = grp_fu_270_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        tmp_i_i_reg_1046 = grp_fu_260_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        tmp_reg_951 = tmp_fu_311_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_s_reg_980 = tmp_s_fu_390_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        x_assign_reg_1041 = x_assign_fu_668_p3.read();
    }
}

void CconLayer::thread_F2_fu_715_p2() {
    F2_fu_715_p2 = (!ap_const_lv12_433.is_01() || !tmp_176_fu_701_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(tmp_176_fu_701_p1.read()));
}

void CconLayer::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void CconLayer::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void CconLayer::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[8];
}

void CconLayer::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[9];
}

void CconLayer::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[10];
}

void CconLayer::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[11];
}

void CconLayer::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[15];
}

void CconLayer::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[16];
}

void CconLayer::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[17];
}

void CconLayer::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void CconLayer::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[20];
}

void CconLayer::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[21];
}

void CconLayer::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void CconLayer::thread_ap_CS_fsm_state37() {
    ap_CS_fsm_state37 = ap_CS_fsm.read()[35];
}

void CconLayer::thread_ap_CS_fsm_state38() {
    ap_CS_fsm_state38 = ap_CS_fsm.read()[36];
}

void CconLayer::thread_ap_CS_fsm_state39() {
    ap_CS_fsm_state39 = ap_CS_fsm.read()[37];
}

void CconLayer::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[4];
}

void CconLayer::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[5];
}

void CconLayer::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[6];
}

void CconLayer::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[7];
}

void CconLayer::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CconLayer::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CconLayer::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CconLayer::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CconLayer::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void CconLayer::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_fu_321_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void CconLayer::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_1) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void CconLayer::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void CconLayer::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void CconLayer::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void CconLayer::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void CconLayer::thread_cconlayer_b_V_address0() {
    cconlayer_b_V_address0 =  (sc_lv<4>) (tmp_s_fu_390_p1.read());
}

void CconLayer::thread_cconlayer_b_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        cconlayer_b_V_ce0 = ap_const_logic_1;
    } else {
        cconlayer_b_V_ce0 = ap_const_logic_0;
    }
}

void CconLayer::thread_cconlayer_k_V_address0() {
    cconlayer_k_V_address0 =  (sc_lv<11>) (tmp_191_fu_342_p1.read());
}

void CconLayer::thread_cconlayer_k_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        cconlayer_k_V_ce0 = ap_const_logic_1;
    } else {
        cconlayer_k_V_ce0 = ap_const_logic_0;
    }
}

void CconLayer::thread_cconlayer_output_V_address0() {
    cconlayer_output_V_address0 =  (sc_lv<4>) (tmp_s_reg_980.read());
}

void CconLayer::thread_cconlayer_output_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        cconlayer_output_V_ce0 = ap_const_logic_1;
    } else {
        cconlayer_output_V_ce0 = ap_const_logic_0;
    }
}

void CconLayer::thread_cconlayer_output_V_d0() {
    cconlayer_output_V_d0 = (!or_cond6_fu_927_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond6_fu_927_p2.read()[0].to_bool())? newSel8_fu_919_p3.read(): ap_const_lv32_0);
}

void CconLayer::thread_cconlayer_output_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state39.read())) {
        cconlayer_output_V_we0 = ap_const_logic_1;
    } else {
        cconlayer_output_V_we0 = ap_const_logic_0;
    }
}

void CconLayer::thread_exitcond4_fu_275_p2() {
    exitcond4_fu_275_p2 = (!i_reg_207.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_207.read() == ap_const_lv4_A);
}

void CconLayer::thread_exitcond_fu_321_p2() {
    exitcond_fu_321_p2 = (!j_reg_231.read().is_01() || !ap_const_lv8_C0.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_231.read() == ap_const_lv8_C0);
}

void CconLayer::thread_exp_tmp_V_fu_691_p4() {
    exp_tmp_V_fu_691_p4 = ireg_V_fu_675_p1.read().range(62, 52);
}

void CconLayer::thread_grp_Reshape_fu_242_ap_start() {
    grp_Reshape_fu_242_ap_start = grp_Reshape_fu_242_ap_start_reg.read();
}

void CconLayer::thread_grp_fu_256_p0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state38.read())) {
        grp_fu_256_p0 = res_fu_253_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        grp_fu_256_p0 = tmp_i_i_reg_1046.read();
    } else {
        grp_fu_256_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void CconLayer::thread_i_16_fu_281_p2() {
    i_16_fu_281_p2 = (!i_reg_207.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_207.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void CconLayer::thread_icmp4_fu_798_p2() {
    icmp4_fu_798_p2 = (!tmp_231_fu_788_p4.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_231_fu_788_p4.read() == ap_const_lv7_0);
}

void CconLayer::thread_icmp_fu_516_p2() {
    icmp_fu_516_p2 = (!tmp_215_fu_506_p4.read().is_01() || !ap_const_lv26_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_215_fu_506_p4.read() == ap_const_lv26_0);
}

void CconLayer::thread_input_val_V_address0() {
    input_val_V_address0 = grp_Reshape_fu_242_src_val_V_address0.read();
}

void CconLayer::thread_input_val_V_ce0() {
    input_val_V_ce0 = grp_Reshape_fu_242_src_val_V_ce0.read();
}

void CconLayer::thread_ireg_V_fu_675_p1() {
    ireg_V_fu_675_p1 = grp_fu_256_p1.read();
}

void CconLayer::thread_is_neg_fu_425_p3() {
    is_neg_fu_425_p3 = p_Val2_49_fu_407_p2.read().range(32, 32);
}

void CconLayer::thread_j_14_fu_327_p2() {
    j_14_fu_327_p2 = (!j_reg_231.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(j_reg_231.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void CconLayer::thread_j_cast2_fu_317_p1() {
    j_cast2_fu_317_p1 = esl_zext<13,8>(j_reg_231.read());
}

void CconLayer::thread_man_V_3_fu_756_p2() {
    man_V_3_fu_756_p2 = (!ap_const_lv54_0.is_01() || !p_Result_10_fu_752_p1.read().is_01())? sc_lv<54>(): (sc_biguint<54>(ap_const_lv54_0) - sc_biguint<54>(p_Result_10_fu_752_p1.read()));
}

void CconLayer::thread_man_V_4_fu_762_p3() {
    man_V_4_fu_762_p3 = (!isneg_reg_1066.read()[0].is_01())? sc_lv<54>(): ((isneg_reg_1066.read()[0].to_bool())? man_V_3_fu_756_p2.read(): p_Result_10_fu_752_p1.read());
}

void CconLayer::thread_msb_idx_2_fu_498_p3() {
    msb_idx_2_fu_498_p3 = (!tmp_214_fu_490_p3.read()[0].is_01())? sc_lv<31>(): ((tmp_214_fu_490_p3.read()[0].to_bool())? ap_const_lv31_0: tmp_213_fu_486_p1.read());
}

void CconLayer::thread_msb_idx_fu_480_p2() {
    msb_idx_fu_480_p2 = (!ap_const_lv32_20.is_01() || !num_zeros_fu_476_p1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_20) - sc_biguint<32>(num_zeros_fu_476_p1.read()));
}

void CconLayer::thread_newSel7_fu_905_p3() {
    newSel7_fu_905_p3 = (!sel_tmp8_fu_856_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp8_fu_856_p2.read()[0].to_bool())? tmp_232_fu_814_p1.read(): tmp_230_fu_778_p1.read());
}

void CconLayer::thread_newSel8_fu_919_p3() {
    newSel8_fu_919_p3 = (!or_cond_fu_899_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_fu_899_p2.read()[0].to_bool())? newSel_fu_891_p3.read(): newSel7_fu_905_p3.read());
}

void CconLayer::thread_newSel_fu_891_p3() {
    newSel_fu_891_p3 = (!sel_tmp3_fu_885_p2.read()[0].is_01())? sc_lv<32>(): ((sel_tmp3_fu_885_p2.read()[0].to_bool())? tmp_189_fu_825_p2.read(): this_assign_fu_818_p3.read());
}

void CconLayer::thread_num_zeros_fu_476_p1() {
    num_zeros_fu_476_p1 = tmp_164_fu_468_p3.read().range(32-1, 0);
}

void CconLayer::thread_or_cond5_fu_913_p2() {
    or_cond5_fu_913_p2 = (sel_tmp8_fu_856_p2.read() | sel_tmp2_fu_836_p2.read());
}

void CconLayer::thread_or_cond6_fu_927_p2() {
    or_cond6_fu_927_p2 = (or_cond_fu_899_p2.read() | or_cond5_fu_913_p2.read());
}

void CconLayer::thread_or_cond_fu_899_p2() {
    or_cond_fu_899_p2 = (sel_tmp3_fu_885_p2.read() | sel_tmp5_fu_868_p2.read());
}

void CconLayer::thread_p_Repl2_5_trunc_fu_634_p2() {
    p_Repl2_5_trunc_fu_634_p2 = (!tmp24_cast_cast_fu_626_p3.read().is_01() || !tmp_226_fu_623_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp24_cast_cast_fu_626_p3.read()) + sc_biguint<8>(tmp_226_fu_623_p1.read()));
}

void CconLayer::thread_p_Result_10_fu_752_p1() {
    p_Result_10_fu_752_p1 = esl_zext<54,53>(tmp_177_fu_745_p3.read());
}

void CconLayer::thread_p_Result_16_op_fu_658_p2() {
    p_Result_16_op_fu_658_p2 = (p_Result_9_fu_647_p5.read() ^ ap_const_lv32_80000000);
}

void CconLayer::thread_p_Result_8_fu_460_p3() {
    p_Result_8_fu_460_p3 = esl_concat<31,33>(ap_const_lv31_7FFFFFFF, p_Result_s_fu_450_p4.read());
}

void CconLayer::thread_p_Result_9_fu_647_p5() {
    p_Result_9_fu_647_p5 = esl_partset<32,32,9,32,32>(tmp32_V_15_reg_1031.read(), tmp_171_fu_640_p3.read(), ap_const_lv32_17, ap_const_lv32_1F);
}

void CconLayer::thread_p_Result_s_fu_450_p4() {
    p_Result_s_fu_450_p4 = p_Val2_48_cast_fu_447_p1.read().range(0, 32);
}

void CconLayer::thread_p_Val2_17_fu_360_p0() {
    p_Val2_17_fu_360_p0 = cconlayer_k_V_q0.read();
}

void CconLayer::thread_p_Val2_17_fu_360_p1() {
    p_Val2_17_fu_360_p1 = p_temp_q0.read();
}

void CconLayer::thread_p_Val2_17_fu_360_p2() {
    p_Val2_17_fu_360_p2 = (!p_Val2_17_fu_360_p0.read().is_01() || !p_Val2_17_fu_360_p1.read().is_01())? sc_lv<48>(): sc_bigint<19>(p_Val2_17_fu_360_p0.read()) * sc_bigint<32>(p_Val2_17_fu_360_p1.read());
}

void CconLayer::thread_p_Val2_18_fu_374_p2() {
    p_Val2_18_fu_374_p2 = (!tmp_193_fu_366_p3.read().is_01() || !p_Val2_17_fu_360_p2.read().is_01())? sc_lv<48>(): (sc_biguint<48>(tmp_193_fu_366_p3.read()) + sc_biguint<48>(p_Val2_17_fu_360_p2.read()));
}

void CconLayer::thread_p_Val2_46_cast_fu_413_p2() {
    p_Val2_46_cast_fu_413_p2 = (!p_Val2_s_reg_219.read().is_01() || !tmp_75_fu_403_p1.read().is_01())? sc_lv<32>(): (sc_bigint<32>(p_Val2_s_reg_219.read()) + sc_bigint<32>(tmp_75_fu_403_p1.read()));
}

void CconLayer::thread_p_Val2_48_cast_fu_447_p1() {
    p_Val2_48_cast_fu_447_p1 = esl_zext<33,32>(p_Val2_52_reg_1000.read());
}

void CconLayer::thread_p_Val2_49_fu_407_p2() {
    p_Val2_49_fu_407_p2 = (!tmp_161_fu_395_p1.read().is_01() || !tmp_162_fu_399_p1.read().is_01())? sc_lv<33>(): (sc_bigint<33>(tmp_161_fu_395_p1.read()) + sc_bigint<33>(tmp_162_fu_399_p1.read()));
}

void CconLayer::thread_p_Val2_52_fu_439_p3() {
    p_Val2_52_fu_439_p3 = (!is_neg_fu_425_p3.read()[0].is_01())? sc_lv<32>(): ((is_neg_fu_425_p3.read()[0].to_bool())? tmp_239_cast_fu_433_p2.read(): p_Val2_46_cast_fu_413_p2.read());
}

void CconLayer::thread_p_shl2_cast_fu_307_p1() {
    p_shl2_cast_fu_307_p1 = esl_zext<13,10>(p_shl2_fu_299_p3.read());
}

void CconLayer::thread_p_shl2_fu_299_p3() {
    p_shl2_fu_299_p3 = esl_concat<4,6>(i_reg_207.read(), ap_const_lv6_0);
}

void CconLayer::thread_p_shl_cast_fu_295_p1() {
    p_shl_cast_fu_295_p1 = esl_zext<13,12>(p_shl_fu_287_p3.read());
}

void CconLayer::thread_p_shl_fu_287_p3() {
    p_shl_fu_287_p3 = esl_concat<4,8>(i_reg_207.read(), ap_const_lv8_0);
}

void CconLayer::thread_p_temp_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        p_temp_address0 =  (sc_lv<8>) (tmp_192_fu_347_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_temp_address0 = grp_Reshape_fu_242_dst_V_address0.read();
    } else {
        p_temp_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void CconLayer::thread_p_temp_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        p_temp_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_temp_ce0 = grp_Reshape_fu_242_dst_V_ce0.read();
    } else {
        p_temp_ce0 = ap_const_logic_0;
    }
}

void CconLayer::thread_p_temp_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        p_temp_we0 = grp_Reshape_fu_242_dst_V_we0.read();
    } else {
        p_temp_we0 = ap_const_logic_0;
    }
}

void CconLayer::thread_sel_tmp1_fu_831_p2() {
    sel_tmp1_fu_831_p2 = (tmp_178_reg_1077.read() ^ ap_const_lv1_1);
}

void CconLayer::thread_sel_tmp21_demorgan_fu_874_p2() {
    sel_tmp21_demorgan_fu_874_p2 = (sel_tmp6_demorgan_fu_841_p2.read() | tmp_179_reg_1083.read());
}

void CconLayer::thread_sel_tmp2_fu_836_p2() {
    sel_tmp2_fu_836_p2 = (tmp_182_reg_1100.read() & sel_tmp1_fu_831_p2.read());
}

void CconLayer::thread_sel_tmp3_fu_885_p2() {
    sel_tmp3_fu_885_p2 = (icmp4_fu_798_p2.read() & sel_tmp9_fu_879_p2.read());
}

void CconLayer::thread_sel_tmp5_fu_868_p2() {
    sel_tmp5_fu_868_p2 = (sel_tmp7_fu_851_p2.read() & sel_tmp_fu_862_p2.read());
}

void CconLayer::thread_sel_tmp6_demorgan_fu_841_p2() {
    sel_tmp6_demorgan_fu_841_p2 = (tmp_178_reg_1077.read() | tmp_182_reg_1100.read());
}

void CconLayer::thread_sel_tmp6_fu_845_p2() {
    sel_tmp6_fu_845_p2 = (sel_tmp6_demorgan_fu_841_p2.read() ^ ap_const_lv1_1);
}

void CconLayer::thread_sel_tmp7_fu_851_p2() {
    sel_tmp7_fu_851_p2 = (tmp_179_reg_1083.read() & sel_tmp6_fu_845_p2.read());
}

void CconLayer::thread_sel_tmp8_fu_856_p2() {
    sel_tmp8_fu_856_p2 = (sel_tmp7_fu_851_p2.read() & tmp_184_fu_782_p2.read());
}

void CconLayer::thread_sel_tmp9_fu_879_p2() {
    sel_tmp9_fu_879_p2 = (sel_tmp21_demorgan_fu_874_p2.read() ^ ap_const_lv1_1);
}

void CconLayer::thread_sel_tmp_fu_862_p2() {
    sel_tmp_fu_862_p2 = (tmp_184_fu_782_p2.read() ^ ap_const_lv1_1);
}

void CconLayer::thread_sh_amt_cast_fu_774_p1() {
    sh_amt_cast_fu_774_p1 = esl_sext<32,12>(sh_amt_fu_769_p3.read());
}

void CconLayer::thread_sh_amt_fu_769_p3() {
    sh_amt_fu_769_p3 = (!tmp_179_reg_1083.read()[0].is_01())? sc_lv<12>(): ((tmp_179_reg_1083.read()[0].to_bool())? tmp_180_reg_1090.read(): tmp_181_reg_1095.read());
}

void CconLayer::thread_this_assign_fu_818_p3() {
    this_assign_fu_818_p3 = (!isneg_reg_1066.read()[0].is_01())? sc_lv<32>(): ((isneg_reg_1066.read()[0].to_bool())? ap_const_lv32_FFFFFFFF: ap_const_lv32_0);
}

void CconLayer::thread_tmp24_cast_cast_fu_626_p3() {
    tmp24_cast_cast_fu_626_p3 = (!tmp_169_fu_618_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_169_fu_618_p2.read()[0].to_bool())? ap_const_lv8_70: ap_const_lv8_6F);
}

void CconLayer::thread_tmp32_V_12_fu_598_p3() {
    tmp32_V_12_fu_598_p3 = (!icmp_reg_1016.read()[0].is_01())? sc_lv<32>(): ((icmp_reg_1016.read()[0].to_bool())? tmp32_V_9_fu_593_p2.read(): tmp32_V_reg_1021.read());
}

void CconLayer::thread_tmp32_V_15_fu_604_p1() {
    tmp32_V_15_fu_604_p1 = grp_fu_250_p1.read();
}

void CconLayer::thread_tmp32_V_9_fu_593_p2() {
    tmp32_V_9_fu_593_p2 = (!tmp_243_cast_fu_589_p1.read().is_01())? sc_lv<32>(): p_Val2_52_reg_1000.read() << (unsigned short)tmp_243_cast_fu_589_p1.read().to_uint();
}

void CconLayer::thread_tmp32_V_fu_580_p1() {
    tmp32_V_fu_580_p1 = tmp_224_fu_574_p2.read().range(32-1, 0);
}

void CconLayer::thread_tmp_161_fu_395_p1() {
    tmp_161_fu_395_p1 = esl_sext<33,32>(p_Val2_s_reg_219.read());
}

void CconLayer::thread_tmp_162_fu_399_p0() {
    tmp_162_fu_399_p0 = cconlayer_b_V_q0.read();
}

void CconLayer::thread_tmp_162_fu_399_p1() {
    tmp_162_fu_399_p1 = esl_sext<33,16>(tmp_162_fu_399_p0.read());
}

void CconLayer::thread_tmp_163_fu_419_p2() {
    tmp_163_fu_419_p2 = (!p_Val2_49_fu_407_p2.read().is_01() || !ap_const_lv33_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Val2_49_fu_407_p2.read() == ap_const_lv33_0);
}

void CconLayer::thread_tmp_164_fu_468_p3() {
    tmp_164_fu_468_p3 = esl_cttz<64,64>(p_Result_8_fu_460_p3.read());
}

void CconLayer::thread_tmp_167_fu_584_p2() {
    tmp_167_fu_584_p2 = (!ap_const_lv31_1F.is_01() || !msb_idx_2_reg_1011.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1F) - sc_biguint<31>(msb_idx_2_reg_1011.read()));
}

void CconLayer::thread_tmp_169_fu_618_p2() {
    tmp_169_fu_618_p2 = (!p_Result_s_206_reg_1036.read().is_01() || !ap_const_lv8_9E.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_s_206_reg_1036.read() != ap_const_lv8_9E);
}

void CconLayer::thread_tmp_171_fu_640_p3() {
    tmp_171_fu_640_p3 = esl_concat<1,8>(is_neg_reg_995.read(), p_Repl2_5_trunc_fu_634_p2.read());
}

void CconLayer::thread_tmp_176_fu_701_p1() {
    tmp_176_fu_701_p1 = esl_zext<12,11>(exp_tmp_V_fu_691_p4.read());
}

void CconLayer::thread_tmp_177_fu_745_p3() {
    tmp_177_fu_745_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_229_reg_1072.read());
}

void CconLayer::thread_tmp_178_fu_709_p2() {
    tmp_178_fu_709_p2 = (!tmp_227_fu_679_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_227_fu_679_p1.read() == ap_const_lv63_0);
}

void CconLayer::thread_tmp_179_fu_721_p2() {
    tmp_179_fu_721_p2 = (!F2_fu_715_p2.read().is_01() || !ap_const_lv12_10.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_fu_715_p2.read()) > sc_bigint<12>(ap_const_lv12_10));
}

void CconLayer::thread_tmp_180_fu_727_p2() {
    tmp_180_fu_727_p2 = (!ap_const_lv12_FF0.is_01() || !F2_fu_715_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FF0) + sc_biguint<12>(F2_fu_715_p2.read()));
}

void CconLayer::thread_tmp_181_fu_733_p2() {
    tmp_181_fu_733_p2 = (!ap_const_lv12_10.is_01() || !F2_fu_715_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_10) - sc_biguint<12>(F2_fu_715_p2.read()));
}

void CconLayer::thread_tmp_182_fu_739_p2() {
    tmp_182_fu_739_p2 = (!F2_fu_715_p2.read().is_01() || !ap_const_lv12_10.is_01())? sc_lv<1>(): sc_lv<1>(F2_fu_715_p2.read() == ap_const_lv12_10);
}

void CconLayer::thread_tmp_184_fu_782_p2() {
    tmp_184_fu_782_p2 = (!sh_amt_fu_769_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(sh_amt_fu_769_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void CconLayer::thread_tmp_186_fu_804_p1() {
    tmp_186_fu_804_p1 = esl_zext<54,32>(sh_amt_cast_fu_774_p1.read());
}

void CconLayer::thread_tmp_187_fu_808_p2() {
    tmp_187_fu_808_p2 = (!man_V_4_fu_762_p3.read().is_01() || !tmp_186_fu_804_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(man_V_4_fu_762_p3.read()) >> (unsigned short)tmp_186_fu_804_p1.read().to_uint();
}

void CconLayer::thread_tmp_189_fu_825_p2() {
    tmp_189_fu_825_p2 = (!sh_amt_cast_fu_774_p1.read().is_01())? sc_lv<32>(): tmp_230_fu_778_p1.read() << (unsigned short)sh_amt_cast_fu_774_p1.read().to_uint();
}

void CconLayer::thread_tmp_190_fu_333_p2() {
    tmp_190_fu_333_p2 = (!j_cast2_fu_317_p1.read().is_01() || !tmp_reg_951.read().is_01())? sc_lv<13>(): (sc_biguint<13>(j_cast2_fu_317_p1.read()) + sc_biguint<13>(tmp_reg_951.read()));
}

void CconLayer::thread_tmp_191_fu_342_p1() {
    tmp_191_fu_342_p1 = esl_zext<64,32>(tmp_232_cast_fu_338_p1.read());
}

void CconLayer::thread_tmp_192_fu_347_p1() {
    tmp_192_fu_347_p1 = esl_zext<64,8>(j_reg_231.read());
}

void CconLayer::thread_tmp_193_fu_366_p3() {
    tmp_193_fu_366_p3 = esl_concat<32,16>(p_Val2_s_reg_219.read(), ap_const_lv16_0);
}

void CconLayer::thread_tmp_213_fu_486_p1() {
    tmp_213_fu_486_p1 = msb_idx_fu_480_p2.read().range(31-1, 0);
}

void CconLayer::thread_tmp_214_fu_490_p3() {
    tmp_214_fu_490_p3 = msb_idx_fu_480_p2.read().range(31, 31);
}

void CconLayer::thread_tmp_215_fu_506_p4() {
    tmp_215_fu_506_p4 = msb_idx_2_fu_498_p3.read().range(30, 5);
}

void CconLayer::thread_tmp_216_fu_522_p1() {
    tmp_216_fu_522_p1 = msb_idx_2_fu_498_p3.read().range(6-1, 0);
}

void CconLayer::thread_tmp_217_fu_526_p2() {
    tmp_217_fu_526_p2 = (!msb_idx_2_fu_498_p3.read().is_01() || !ap_const_lv31_1F.is_01())? sc_lv<1>(): (sc_biguint<31>(msb_idx_2_fu_498_p3.read()) < sc_biguint<31>(ap_const_lv31_1F));
}

void CconLayer::thread_tmp_218_fu_532_p2() {
    tmp_218_fu_532_p2 = (!ap_const_lv6_21.is_01() || !tmp_216_fu_522_p1.read().is_01())? sc_lv<6>(): (sc_bigint<6>(ap_const_lv6_21) + sc_biguint<6>(tmp_216_fu_522_p1.read()));
}

void CconLayer::thread_tmp_219_fu_538_p4() {
    tmp_219_fu_538_p4 = p_Val2_48_cast_fu_447_p1.read().range(0, 32);
}

void CconLayer::thread_tmp_220_fu_548_p2() {
    tmp_220_fu_548_p2 = (tmp_216_fu_522_p1.read() ^ ap_const_lv6_3F);
}

void CconLayer::thread_tmp_221_fu_554_p3() {
    tmp_221_fu_554_p3 = (!tmp_217_fu_526_p2.read()[0].is_01())? sc_lv<33>(): ((tmp_217_fu_526_p2.read()[0].to_bool())? tmp_219_fu_538_p4.read(): p_Val2_48_cast_fu_447_p1.read());
}

void CconLayer::thread_tmp_222_fu_562_p3() {
    tmp_222_fu_562_p3 = (!tmp_217_fu_526_p2.read()[0].is_01())? sc_lv<6>(): ((tmp_217_fu_526_p2.read()[0].to_bool())? tmp_220_fu_548_p2.read(): tmp_218_fu_532_p2.read());
}

void CconLayer::thread_tmp_223_fu_570_p1() {
    tmp_223_fu_570_p1 = esl_zext<33,6>(tmp_222_fu_562_p3.read());
}

void CconLayer::thread_tmp_224_fu_574_p2() {
    tmp_224_fu_574_p2 = (!tmp_223_fu_570_p1.read().is_01())? sc_lv<33>(): tmp_221_fu_554_p3.read() >> (unsigned short)tmp_223_fu_570_p1.read().to_uint();
}

void CconLayer::thread_tmp_226_fu_623_p1() {
    tmp_226_fu_623_p1 = msb_idx_reg_1006.read().range(8-1, 0);
}

void CconLayer::thread_tmp_227_fu_679_p1() {
    tmp_227_fu_679_p1 = ireg_V_fu_675_p1.read().range(63-1, 0);
}

void CconLayer::thread_tmp_229_fu_705_p1() {
    tmp_229_fu_705_p1 = ireg_V_fu_675_p1.read().range(52-1, 0);
}

void CconLayer::thread_tmp_230_fu_778_p1() {
    tmp_230_fu_778_p1 = man_V_4_fu_762_p3.read().range(32-1, 0);
}

void CconLayer::thread_tmp_231_fu_788_p4() {
    tmp_231_fu_788_p4 = sh_amt_fu_769_p3.read().range(11, 5);
}

void CconLayer::thread_tmp_232_cast_fu_338_p1() {
    tmp_232_cast_fu_338_p1 = esl_sext<32,13>(tmp_190_fu_333_p2.read());
}

void CconLayer::thread_tmp_232_fu_814_p1() {
    tmp_232_fu_814_p1 = tmp_187_fu_808_p2.read().range(32-1, 0);
}

void CconLayer::thread_tmp_239_cast_fu_433_p2() {
    tmp_239_cast_fu_433_p2 = (!ap_const_lv32_0.is_01() || !p_Val2_46_cast_fu_413_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(p_Val2_46_cast_fu_413_p2.read()));
}

void CconLayer::thread_tmp_243_cast_fu_589_p1() {
    tmp_243_cast_fu_589_p1 = esl_zext<32,31>(tmp_167_fu_584_p2.read());
}

void CconLayer::thread_tmp_75_fu_403_p0() {
    tmp_75_fu_403_p0 = cconlayer_b_V_q0.read();
}

void CconLayer::thread_tmp_75_fu_403_p1() {
    tmp_75_fu_403_p1 = esl_sext<32,16>(tmp_75_fu_403_p0.read());
}

void CconLayer::thread_tmp_76_fu_664_p1() {
    tmp_76_fu_664_p1 = p_Result_16_op_fu_658_p2.read();
}

void CconLayer::thread_tmp_fu_311_p2() {
    tmp_fu_311_p2 = (!p_shl_cast_fu_295_p1.read().is_01() || !p_shl2_cast_fu_307_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(p_shl_cast_fu_295_p1.read()) - sc_biguint<13>(p_shl2_cast_fu_307_p1.read()));
}

void CconLayer::thread_tmp_s_fu_390_p1() {
    tmp_s_fu_390_p1 = esl_zext<64,4>(i_reg_207.read());
}

void CconLayer::thread_x_assign_fu_668_p3() {
    x_assign_fu_668_p3 = (!tmp_163_reg_990.read()[0].is_01())? sc_lv<32>(): ((tmp_163_reg_990.read()[0].to_bool())? ap_const_lv32_80000000: tmp_76_fu_664_p1.read());
}

void CconLayer::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(grp_Reshape_fu_242_ap_done.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(exitcond4_fu_275_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_fu_321_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(exitcond_fu_321_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state32;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state33;
            break;
        case 2147483648 : 
            ap_NS_fsm = ap_ST_fsm_state34;
            break;
        case 4294967296 : 
            ap_NS_fsm = ap_ST_fsm_state35;
            break;
        case 8589934592 : 
            ap_NS_fsm = ap_ST_fsm_state36;
            break;
        case 17179869184 : 
            ap_NS_fsm = ap_ST_fsm_state37;
            break;
        case 34359738368 : 
            ap_NS_fsm = ap_ST_fsm_state38;
            break;
        case 68719476736 : 
            ap_NS_fsm = ap_ST_fsm_state39;
            break;
        case 137438953472 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<38>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

