// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhaar_core.h"

extern XHaar_core_Config XHaar_core_ConfigTable[];

XHaar_core_Config *XHaar_core_LookupConfig(u16 DeviceId) {
	XHaar_core_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHAAR_CORE_NUM_INSTANCES; Index++) {
		if (XHaar_core_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHaar_core_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHaar_core_Initialize(XHaar_core *InstancePtr, u16 DeviceId) {
	XHaar_core_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHaar_core_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHaar_core_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

