<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>Mul185</name>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>5</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>src1_rows_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>src1.rows.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>src1_cols_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>src1.cols.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>src1_data_stream_V_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>src1.data_stream.V.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>15</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_4">
				<Value>
					<Obj>
						<type>1</type>
						<id>4</id>
						<name>src2_data_stream_V_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>src2.data_stream.V.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>15</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_5">
				<Value>
					<Obj>
						<type>1</type>
						<id>5</id>
						<name>dst_data_stream_V_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>dst.data_stream.V.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>35</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>22</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name>rows_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>832</lineNumber>
						<contextFuncName>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="10" tracking_level="0" version="0">
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second class_id="11" tracking_level="0" version="0">
									<count>1</count>
									<item_version>0</item_version>
									<item class_id="12" tracking_level="0" version="0">
										<first class_id="13" tracking_level="0" version="0">
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>832</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>dst.rows.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>60</item>
					<item>61</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>2.26</m_delay>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name>cols_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>832</lineNumber>
						<contextFuncName>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>832</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>dst.cols.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>62</item>
					<item>63</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>2.26</m_delay>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>13</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>354</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>354</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>64</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.97</m_delay>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>15</id>
						<name>t_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>66</item>
					<item>67</item>
					<item>68</item>
					<item>69</item>
				</oprand_edges>
				<opcode>phi</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>16</id>
						<name>exitcond7_i_i</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>354</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>354</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>70</item>
					<item>71</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>1.31</m_delay>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>18</id>
						<name>i_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>354</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>354</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>72</item>
					<item>74</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>1.57</m_delay>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>354</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>354</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>75</item>
					<item>76</item>
					<item>77</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>23</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>355</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>355</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>78</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.97</m_delay>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>25</id>
						<name>t_V_4</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>j.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>79</item>
					<item>80</item>
					<item>81</item>
					<item>82</item>
				</oprand_edges>
				<opcode>phi</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>26</id>
						<name>exitcond_i_i</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>355</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>355</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>83</item>
					<item>84</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>1.31</m_delay>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>j_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>355</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>355</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>j.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>85</item>
					<item>86</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>1.57</m_delay>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>355</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>355</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>87</item>
					<item>88</item>
					<item>89</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>36</id>
						<name>tmp_V_5</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>624</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>4</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>358</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>operator&amp;gt;&amp;gt;</second>
										</first>
										<second>656</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>read</second>
										</first>
										<second>624</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>tmp.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>15</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>91</item>
					<item>92</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>2.26</m_delay>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>40</id>
						<name>tmp_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>624</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>4</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>359</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>operator&amp;gt;&amp;gt;</second>
										</first>
										<second>656</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>read</second>
										</first>
										<second>624</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>tmp.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>15</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>93</item>
					<item>94</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>2.26</m_delay>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>43</id>
						<name>lhs_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>264</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>264</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>361</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>lhs.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>95</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>44</id>
						<name>rhs_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>264</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>264</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>361</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>rhs.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>96</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_22">
				<Value>
					<Obj>
						<type>0</type>
						<id>45</id>
						<name>r_V</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>264</lineNumber>
						<contextFuncName>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>264</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>361</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>r.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>30</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>97</item>
					<item>98</item>
				</oprand_edges>
				<opcode>mul</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>4.41</m_delay>
			</item>
			<item class_id_reference="9" object_id="_23">
				<Value>
					<Obj>
						<type>0</type>
						<id>46</id>
						<name>p_Val2_s</name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_types.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>341</lineNumber>
						<contextFuncName>operator()&amp;lt;30&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>5</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>apply&amp;lt;ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;15&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>266</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>361</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_types.h</first>
											<second>operator()&amp;lt;30&amp;gt;</second>
										</first>
										<second>341</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_types.h</first>
											<second>sr_cast&amp;lt;ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;30&amp;gt; &amp;gt;</second>
										</first>
										<second>500</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>__Val2__</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>35</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>99</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_24">
				<Value>
					<Obj>
						<type>0</type>
						<id>49</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>648</lineNumber>
						<contextFuncName>write</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>4</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>363</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>operator&amp;lt;&amp;lt;</second>
										</first>
										<second>662</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_core.h</first>
											<second>write</second>
										</first>
										<second>648</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>101</item>
					<item>102</item>
					<item>103</item>
				</oprand_edges>
				<opcode>write</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>2.26</m_delay>
			</item>
			<item class_id_reference="9" object_id="_25">
				<Value>
					<Obj>
						<type>0</type>
						<id>52</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>355</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>355</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>104</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_26">
				<Value>
					<Obj>
						<type>0</type>
						<id>55</id>
						<name></name>
						<fileName>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</fileName>
						<fileDirectory>F:\FPGA\project\HLS\Haaris</fileDirectory>
						<lineNumber>354</lineNumber>
						<contextFuncName>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>F:\FPGA\project\HLS\Haaris</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>Mul&amp;lt;256, 256, 27, 27, 47&amp;gt;</second>
										</first>
										<second>835</second>
									</item>
									<item>
										<first>
											<first>E:/Xilinx/Vivado/2018.2/common/technology/autopilot/hls/hls_video_arithm.h</first>
											<second>arithm_pro&amp;lt;hls::kernel_mul2, 256, 256, 27, 27, 47, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt;, ap_int&amp;lt;35&amp;gt; &amp;gt;</second>
										</first>
										<second>354</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>105</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
			<item class_id_reference="9" object_id="_27">
				<Value>
					<Obj>
						<type>0</type>
						<id>57</id>
						<name></name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_delay>0.00</m_delay>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>2</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_28">
				<Value>
					<Obj>
						<type>2</type>
						<id>65</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_29">
				<Value>
					<Obj>
						<type>2</type>
						<id>73</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>32</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>7</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_30">
				<Obj>
					<type>3</type>
					<id>14</id>
					<name>entry</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>3</count>
					<item_version>0</item_version>
					<item>11</item>
					<item>12</item>
					<item>13</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_31">
				<Obj>
					<type>3</type>
					<id>20</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>15</item>
					<item>16</item>
					<item>18</item>
					<item>19</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_32">
				<Obj>
					<type>3</type>
					<id>24</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>23</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_33">
				<Obj>
					<type>3</type>
					<id>30</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>25</item>
					<item>26</item>
					<item>28</item>
					<item>29</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_34">
				<Obj>
					<type>3</type>
					<id>53</id>
					<name>.critedge.i.i</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>8</count>
					<item_version>0</item_version>
					<item>36</item>
					<item>40</item>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
					<item>49</item>
					<item>52</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_35">
				<Obj>
					<type>3</type>
					<id>56</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>55</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_36">
				<Obj>
					<type>3</type>
					<id>58</id>
					<name>.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>57</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>45</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_37">
				<id>61</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_38">
				<id>63</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_39">
				<id>64</id>
				<edge_type>2</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>13</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_40">
				<id>66</id>
				<edge_type>1</edge_type>
				<source_obj>65</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>67</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>69</id>
				<edge_type>2</edge_type>
				<source_obj>56</source_obj>
				<sink_obj>15</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>70</id>
				<edge_type>1</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>16</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>71</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>16</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>72</id>
				<edge_type>1</edge_type>
				<source_obj>15</source_obj>
				<sink_obj>18</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>73</source_obj>
				<sink_obj>18</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>75</id>
				<edge_type>1</edge_type>
				<source_obj>16</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>76</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>77</id>
				<edge_type>2</edge_type>
				<source_obj>58</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>78</id>
				<edge_type>2</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>65</source_obj>
				<sink_obj>25</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>80</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>25</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>81</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>25</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>82</id>
				<edge_type>2</edge_type>
				<source_obj>53</source_obj>
				<sink_obj>25</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>26</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>84</id>
				<edge_type>1</edge_type>
				<source_obj>12</source_obj>
				<sink_obj>26</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>85</id>
				<edge_type>1</edge_type>
				<source_obj>25</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>86</id>
				<edge_type>1</edge_type>
				<source_obj>73</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>87</id>
				<edge_type>1</edge_type>
				<source_obj>26</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>88</id>
				<edge_type>2</edge_type>
				<source_obj>53</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>89</id>
				<edge_type>2</edge_type>
				<source_obj>56</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>92</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>36</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>94</id>
				<edge_type>1</edge_type>
				<source_obj>4</source_obj>
				<sink_obj>40</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>95</id>
				<edge_type>1</edge_type>
				<source_obj>36</source_obj>
				<sink_obj>43</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>96</id>
				<edge_type>1</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>44</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>97</id>
				<edge_type>1</edge_type>
				<source_obj>44</source_obj>
				<sink_obj>45</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>98</id>
				<edge_type>1</edge_type>
				<source_obj>43</source_obj>
				<sink_obj>45</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>99</id>
				<edge_type>1</edge_type>
				<source_obj>45</source_obj>
				<sink_obj>46</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>102</id>
				<edge_type>1</edge_type>
				<source_obj>5</source_obj>
				<sink_obj>49</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>103</id>
				<edge_type>1</edge_type>
				<source_obj>46</source_obj>
				<sink_obj>49</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>104</id>
				<edge_type>2</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>52</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>105</id>
				<edge_type>2</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>55</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>263</id>
				<edge_type>2</edge_type>
				<source_obj>14</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>264</id>
				<edge_type>2</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>58</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_76">
				<id>265</id>
				<edge_type>2</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>24</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_77">
				<id>266</id>
				<edge_type>2</edge_type>
				<source_obj>24</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_78">
				<id>267</id>
				<edge_type>2</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>56</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_79">
				<id>268</id>
				<edge_type>2</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>53</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_80">
				<id>269</id>
				<edge_type>2</edge_type>
				<source_obj>53</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_81">
				<id>270</id>
				<edge_type>2</edge_type>
				<source_obj>56</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_82">
			<mId>1</mId>
			<mTag>Mul185</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>7</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>1</mMinLatency>
			<mMaxLatency>66561</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_83">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>14</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_84">
			<mId>3</mId>
			<mTag>loop_height</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>4</item>
				<item>5</item>
				<item>6</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>0</mMinTripCount>
			<mMaxTripCount>256</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>66560</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_85">
			<mId>4</mId>
			<mTag>Region 1</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>20</item>
				<item>24</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_86">
			<mId>5</mId>
			<mTag>loop_width</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>30</item>
				<item>53</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>3</mDepth>
			<mMinTripCount>0</mMinTripCount>
			<mMaxTripCount>256</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>257</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_87">
			<mId>6</mId>
			<mTag>Region 2</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>56</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_88">
			<mId>7</mId>
			<mTag>Return</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>58</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>22</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>11</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>15</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>16</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>25</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>26</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>36</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>43</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>44</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>45</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>46</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>49</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>52</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>55</first>
			<second>
				<first>5</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>57</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>14</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>24</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>53</first>
			<second>
				<first>3</first>
				<second>4</second>
			</second>
		</item>
		<item>
			<first>56</first>
			<second>
				<first>3</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>58</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>2</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_89">
			<region_name>loop_width</region_name>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>30</item>
				<item>53</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>3</pipe_depth>
		</item>
		<item class_id_reference="33" object_id="_90">
			<region_name>hls_label_26</region_name>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>53</item>
			</basic_blocks>
			<nodes>
				<count>4</count>
				<item_version>0</item_version>
				<item>47</item>
				<item>48</item>
				<item>49</item>
				<item>50</item>
			</nodes>
			<anchor_node>47</anchor_node>
			<region_type>1</region_type>
			<interval>0</interval>
			<pipe_depth>0</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

