-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Block_Mat_exit412_pr is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    rows0 : IN STD_LOGIC_VECTOR (31 downto 0);
    cols0 : IN STD_LOGIC_VECTOR (31 downto 0);
    rows1 : IN STD_LOGIC_VECTOR (31 downto 0);
    cols1 : IN STD_LOGIC_VECTOR (31 downto 0);
    thresh : IN STD_LOGIC_VECTOR (31 downto 0);
    p_src0_rows_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_src0_rows_V_out_full_n : IN STD_LOGIC;
    p_src0_rows_V_out_write : OUT STD_LOGIC;
    p_src0_cols_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_src0_cols_V_out_full_n : IN STD_LOGIC;
    p_src0_cols_V_out_write : OUT STD_LOGIC;
    p_src1_rows_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_src1_rows_V_out_full_n : IN STD_LOGIC;
    p_src1_rows_V_out_write : OUT STD_LOGIC;
    p_src1_cols_V_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    p_src1_cols_V_out_full_n : IN STD_LOGIC;
    p_src1_cols_V_out_write : OUT STD_LOGIC;
    src1_rows_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    src1_rows_out_full_n : IN STD_LOGIC;
    src1_rows_out_write : OUT STD_LOGIC;
    src1_cols_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    src1_cols_out_full_n : IN STD_LOGIC;
    src1_cols_out_write : OUT STD_LOGIC;
    descriptors0_length_out_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    descriptors0_length_out_full_n : IN STD_LOGIC;
    descriptors0_length_out_write : OUT STD_LOGIC;
    descriptors1_length_out_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    descriptors1_length_out_full_n : IN STD_LOGIC;
    descriptors1_length_out_write : OUT STD_LOGIC;
    matches_length_out_din : OUT STD_LOGIC_VECTOR (0 downto 0);
    matches_length_out_full_n : IN STD_LOGIC;
    matches_length_out_write : OUT STD_LOGIC;
    thresh_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    thresh_out_full_n : IN STD_LOGIC;
    thresh_out_write : OUT STD_LOGIC );
end;


architecture behav of Block_Mat_exit412_pr is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src0_rows_V_out_blk_n : STD_LOGIC;
    signal p_src0_cols_V_out_blk_n : STD_LOGIC;
    signal p_src1_rows_V_out_blk_n : STD_LOGIC;
    signal p_src1_cols_V_out_blk_n : STD_LOGIC;
    signal src1_rows_out_blk_n : STD_LOGIC;
    signal src1_cols_out_blk_n : STD_LOGIC;
    signal descriptors0_length_out_blk_n : STD_LOGIC;
    signal descriptors1_length_out_blk_n : STD_LOGIC;
    signal matches_length_out_blk_n : STD_LOGIC;
    signal thresh_out_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
                ap_block_state1 <= ((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    descriptors0_length_out_blk_n_assign_proc : process(ap_CS_fsm_state1, descriptors0_length_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            descriptors0_length_out_blk_n <= descriptors0_length_out_full_n;
        else 
            descriptors0_length_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    descriptors0_length_out_din <= ap_const_lv1_0;

    descriptors0_length_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            descriptors0_length_out_write <= ap_const_logic_1;
        else 
            descriptors0_length_out_write <= ap_const_logic_0;
        end if; 
    end process;


    descriptors1_length_out_blk_n_assign_proc : process(ap_CS_fsm_state1, descriptors1_length_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            descriptors1_length_out_blk_n <= descriptors1_length_out_full_n;
        else 
            descriptors1_length_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    descriptors1_length_out_din <= ap_const_lv1_0;

    descriptors1_length_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            descriptors1_length_out_write <= ap_const_logic_1;
        else 
            descriptors1_length_out_write <= ap_const_logic_0;
        end if; 
    end process;


    matches_length_out_blk_n_assign_proc : process(ap_CS_fsm_state1, matches_length_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            matches_length_out_blk_n <= matches_length_out_full_n;
        else 
            matches_length_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    matches_length_out_din <= ap_const_lv1_0;

    matches_length_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            matches_length_out_write <= ap_const_logic_1;
        else 
            matches_length_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src0_cols_V_out_blk_n_assign_proc : process(ap_CS_fsm_state1, p_src0_cols_V_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_src0_cols_V_out_blk_n <= p_src0_cols_V_out_full_n;
        else 
            p_src0_cols_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_src0_cols_V_out_din <= cols0;

    p_src0_cols_V_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src0_cols_V_out_write <= ap_const_logic_1;
        else 
            p_src0_cols_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src0_rows_V_out_blk_n_assign_proc : process(ap_CS_fsm_state1, p_src0_rows_V_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_src0_rows_V_out_blk_n <= p_src0_rows_V_out_full_n;
        else 
            p_src0_rows_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_src0_rows_V_out_din <= rows0;

    p_src0_rows_V_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src0_rows_V_out_write <= ap_const_logic_1;
        else 
            p_src0_rows_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src1_cols_V_out_blk_n_assign_proc : process(ap_CS_fsm_state1, p_src1_cols_V_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_src1_cols_V_out_blk_n <= p_src1_cols_V_out_full_n;
        else 
            p_src1_cols_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_src1_cols_V_out_din <= cols1;

    p_src1_cols_V_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src1_cols_V_out_write <= ap_const_logic_1;
        else 
            p_src1_cols_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    p_src1_rows_V_out_blk_n_assign_proc : process(ap_CS_fsm_state1, p_src1_rows_V_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            p_src1_rows_V_out_blk_n <= p_src1_rows_V_out_full_n;
        else 
            p_src1_rows_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_src1_rows_V_out_din <= rows1;

    p_src1_rows_V_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_src1_rows_V_out_write <= ap_const_logic_1;
        else 
            p_src1_rows_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    src1_cols_out_blk_n_assign_proc : process(ap_CS_fsm_state1, src1_cols_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            src1_cols_out_blk_n <= src1_cols_out_full_n;
        else 
            src1_cols_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    src1_cols_out_din <= cols1;

    src1_cols_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            src1_cols_out_write <= ap_const_logic_1;
        else 
            src1_cols_out_write <= ap_const_logic_0;
        end if; 
    end process;


    src1_rows_out_blk_n_assign_proc : process(ap_CS_fsm_state1, src1_rows_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            src1_rows_out_blk_n <= src1_rows_out_full_n;
        else 
            src1_rows_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    src1_rows_out_din <= rows1;

    src1_rows_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            src1_rows_out_write <= ap_const_logic_1;
        else 
            src1_rows_out_write <= ap_const_logic_0;
        end if; 
    end process;


    thresh_out_blk_n_assign_proc : process(ap_CS_fsm_state1, thresh_out_full_n)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state1)) then 
            thresh_out_blk_n <= thresh_out_full_n;
        else 
            thresh_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    thresh_out_din <= thresh;

    thresh_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, p_src0_rows_V_out_full_n, p_src0_cols_V_out_full_n, p_src1_rows_V_out_full_n, p_src1_cols_V_out_full_n, src1_rows_out_full_n, src1_cols_out_full_n, descriptors0_length_out_full_n, descriptors1_length_out_full_n, matches_length_out_full_n, thresh_out_full_n)
    begin
        if ((not(((thresh_out_full_n = ap_const_logic_0) or (matches_length_out_full_n = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (descriptors1_length_out_full_n = ap_const_logic_0) or (descriptors0_length_out_full_n = ap_const_logic_0) or (src1_cols_out_full_n = ap_const_logic_0) or (src1_rows_out_full_n = ap_const_logic_0) or (p_src1_cols_V_out_full_n = ap_const_logic_0) or (p_src1_rows_V_out_full_n = ap_const_logic_0) or (p_src0_cols_V_out_full_n = ap_const_logic_0) or (p_src0_rows_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            thresh_out_write <= ap_const_logic_1;
        else 
            thresh_out_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
