// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_V_din,
        p_dst_data_stream_V_V_full_n,
        p_dst_data_stream_V_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_0_V_3_read,
        p_kernel_val_0_V_4_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_1_V_3_read,
        p_kernel_val_1_V_4_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read,
        p_kernel_val_2_V_3_read,
        p_kernel_val_2_V_4_read,
        p_kernel_val_3_V_0_read,
        p_kernel_val_3_V_1_read,
        p_kernel_val_3_V_2_read,
        p_kernel_val_3_V_4_read,
        p_kernel_val_4_V_0_read,
        p_kernel_val_4_V_1_read,
        p_kernel_val_4_V_2_read,
        p_kernel_val_4_V_3_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state8 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] p_src_rows_V_read;
input  [31:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [14:0] p_dst_data_stream_V_V_din;
input   p_dst_data_stream_V_V_full_n;
output   p_dst_data_stream_V_V_write;
input  [2:0] p_kernel_val_0_V_1_read;
input  [3:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_0_V_3_read;
input  [1:0] p_kernel_val_0_V_4_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [4:0] p_kernel_val_1_V_2_read;
input  [4:0] p_kernel_val_1_V_3_read;
input  [3:0] p_kernel_val_1_V_4_read;
input  [4:0] p_kernel_val_2_V_0_read;
input  [5:0] p_kernel_val_2_V_1_read;
input  [5:0] p_kernel_val_2_V_3_read;
input  [4:0] p_kernel_val_2_V_4_read;
input  [2:0] p_kernel_val_3_V_0_read;
input  [4:0] p_kernel_val_3_V_1_read;
input  [4:0] p_kernel_val_3_V_2_read;
input  [3:0] p_kernel_val_3_V_4_read;
input  [1:0] p_kernel_val_4_V_0_read;
input  [3:0] p_kernel_val_4_V_1_read;
input  [3:0] p_kernel_val_4_V_2_read;
input  [3:0] p_kernel_val_4_V_3_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] or_cond_i_i_reg_2426;
reg   [0:0] tmp_4_reg_2366;
reg   [0:0] tmp_3_reg_2357;
reg    p_dst_data_stream_V_V_blk_n;
reg    ap_enable_reg_pp0_iter4;
reg   [0:0] or_cond_i_reg_2478;
reg   [0:0] or_cond_i_reg_2478_pp0_iter3_reg;
reg   [31:0] t_V_7_reg_519;
wire   [31:0] tmp_s_fu_530_p2;
reg   [31:0] tmp_s_reg_2218;
wire   [31:0] tmp_1_fu_536_p2;
reg   [31:0] tmp_1_reg_2223;
wire   [31:0] tmp_2_fu_542_p2;
reg   [31:0] tmp_2_reg_2228;
wire   [31:0] p_neg397_i_fu_548_p2;
reg   [31:0] p_neg397_i_reg_2234;
wire  signed [10:0] OP2_V_0_1_cast_fu_554_p1;
reg  signed [10:0] OP2_V_0_1_cast_reg_2248;
wire  signed [11:0] OP2_V_0_2_cast_fu_558_p1;
reg  signed [11:0] OP2_V_0_2_cast_reg_2253;
wire  signed [10:0] OP2_V_0_3_cast_fu_562_p1;
reg  signed [10:0] OP2_V_0_3_cast_reg_2258;
wire  signed [9:0] OP2_V_0_4_cast_fu_566_p1;
reg  signed [9:0] OP2_V_0_4_cast_reg_2263;
wire  signed [10:0] OP2_V_1_cast_fu_570_p1;
reg  signed [10:0] OP2_V_1_cast_reg_2268;
wire  signed [12:0] OP2_V_1_2_cast_fu_574_p1;
reg  signed [12:0] OP2_V_1_2_cast_reg_2273;
wire  signed [12:0] OP2_V_1_3_cast_fu_578_p1;
reg  signed [12:0] OP2_V_1_3_cast_reg_2278;
wire  signed [11:0] OP2_V_1_4_cast_fu_582_p1;
reg  signed [11:0] OP2_V_1_4_cast_reg_2283;
wire  signed [11:0] OP2_V_2_cast_fu_586_p1;
reg  signed [11:0] OP2_V_2_cast_reg_2288;
wire  signed [13:0] OP2_V_2_1_cast_fu_590_p1;
reg  signed [13:0] OP2_V_2_1_cast_reg_2293;
wire   [13:0] OP2_V_2_3_cast_fu_594_p1;
reg   [13:0] OP2_V_2_3_cast_reg_2298;
wire   [12:0] OP2_V_2_4_cast_fu_598_p1;
reg   [12:0] OP2_V_2_4_cast_reg_2303;
wire  signed [10:0] OP2_V_3_cast_fu_602_p1;
reg  signed [10:0] OP2_V_3_cast_reg_2308;
wire  signed [12:0] OP2_V_3_1_cast_fu_606_p1;
reg  signed [12:0] OP2_V_3_1_cast_reg_2313;
wire   [12:0] OP2_V_3_2_cast_fu_610_p1;
reg   [12:0] OP2_V_3_2_cast_reg_2318;
wire   [11:0] OP2_V_3_4_cast_fu_614_p1;
reg   [11:0] OP2_V_3_4_cast_reg_2323;
wire  signed [9:0] OP2_V_4_cast_fu_618_p1;
reg  signed [9:0] OP2_V_4_cast_reg_2328;
wire  signed [11:0] OP2_V_4_1_cast_fu_622_p1;
reg  signed [11:0] OP2_V_4_1_cast_reg_2333;
wire   [11:0] OP2_V_4_2_cast_fu_626_p1;
reg   [11:0] OP2_V_4_2_cast_reg_2338;
wire   [11:0] OP2_V_4_3_cast_fu_630_p1;
reg   [11:0] OP2_V_4_3_cast_reg_2343;
wire   [0:0] exitcond393_i_fu_634_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] i_V_fu_639_p2;
reg   [31:0] i_V_reg_2352;
wire   [0:0] tmp_3_fu_645_p2;
wire   [0:0] tmp_274_not_fu_650_p2;
reg   [0:0] tmp_274_not_reg_2361;
wire   [0:0] tmp_4_fu_656_p2;
wire   [0:0] tmp_7_fu_662_p2;
reg   [0:0] tmp_7_reg_2371;
wire   [0:0] tmp_304_3_fu_668_p2;
reg   [0:0] tmp_304_3_reg_2375;
wire   [0:0] tmp_304_4_fu_674_p2;
reg   [0:0] tmp_304_4_reg_2379;
wire   [0:0] tmp_8_fu_680_p2;
reg   [0:0] tmp_8_reg_2383;
wire   [2:0] tmp_85_fu_928_p1;
reg   [2:0] tmp_85_reg_2392;
wire   [2:0] tmp_86_fu_945_p1;
reg   [2:0] tmp_86_reg_2397;
wire   [2:0] tmp_87_fu_962_p1;
reg   [2:0] tmp_87_reg_2402;
wire   [2:0] tmp_88_fu_979_p1;
reg   [2:0] tmp_88_reg_2407;
wire   [2:0] tmp_89_fu_996_p1;
reg   [2:0] tmp_89_reg_2412;
wire   [0:0] exitcond392_i_fu_1000_p2;
reg   [0:0] exitcond392_i_reg_2417;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_predicate_op218_read_state4;
reg    ap_predicate_op231_read_state4;
reg    ap_block_state4_pp0_stage0_iter1;
wire    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
reg    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond392_i_reg_2417_pp0_iter1_reg;
reg   [0:0] exitcond392_i_reg_2417_pp0_iter2_reg;
wire   [31:0] j_V_fu_1005_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_1052_p2;
wire   [0:0] brmerge_fu_1086_p2;
reg   [0:0] brmerge_reg_2430;
reg   [7:0] k_buf_0_val_5_addr_reg_2439;
wire   [2:0] tmp_93_fu_1100_p1;
reg   [2:0] tmp_93_reg_2445;
reg   [7:0] k_buf_0_val_6_addr_reg_2454;
reg   [7:0] k_buf_0_val_7_addr_reg_2460;
reg   [7:0] k_buf_0_val_8_addr_reg_2466;
reg   [7:0] k_buf_0_val_9_addr_reg_2472;
wire   [0:0] or_cond_i_fu_1104_p2;
reg   [0:0] or_cond_i_reg_2478_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_2478_pp0_iter2_reg;
wire   [7:0] src_kernel_win_0_va_20_fu_1274_p3;
reg   [7:0] src_kernel_win_0_va_20_reg_2482;
wire   [7:0] src_kernel_win_0_va_21_fu_1296_p3;
reg   [7:0] src_kernel_win_0_va_21_reg_2488;
wire   [7:0] src_kernel_win_0_va_22_fu_1318_p3;
reg   [7:0] src_kernel_win_0_va_22_reg_2494;
reg   [7:0] src_kernel_win_0_va_22_reg_2494_pp0_iter2_reg;
wire   [7:0] src_kernel_win_0_va_23_fu_1340_p3;
reg   [7:0] src_kernel_win_0_va_23_reg_2500;
reg   [7:0] src_kernel_win_0_va_23_reg_2500_pp0_iter2_reg;
wire   [7:0] src_kernel_win_0_va_24_fu_1362_p3;
reg   [7:0] src_kernel_win_0_va_24_reg_2505;
reg   [7:0] src_kernel_win_0_va_38_reg_2511;
wire   [10:0] r_V_8_1_fu_1385_p2;
reg  signed [10:0] r_V_8_1_reg_2516;
wire  signed [13:0] grp_fu_1926_p3;
reg  signed [13:0] tmp9_reg_2521;
reg  signed [13:0] tmp9_reg_2521_pp0_iter2_reg;
reg   [7:0] src_kernel_win_0_va_31_reg_2526;
wire   [13:0] p_Val2_19_1_1_fu_1543_p2;
reg   [13:0] p_Val2_19_1_1_reg_2531;
wire  signed [13:0] grp_fu_1965_p3;
reg  signed [13:0] tmp16_reg_2536;
reg    ap_enable_reg_pp0_iter2;
wire  signed [13:0] tmp23_fu_1622_p2;
reg  signed [13:0] tmp23_reg_2542;
reg   [0:0] isneg_reg_2548;
wire   [14:0] p_Val2_6_fu_1837_p2;
reg   [14:0] p_Val2_6_reg_2555;
reg   [0:0] newsignbit_reg_2561;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter3;
wire   [7:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
wire   [7:0] k_buf_0_val_6_address0;
reg    k_buf_0_val_6_ce0;
wire   [7:0] k_buf_0_val_6_q0;
reg    k_buf_0_val_6_ce1;
reg    k_buf_0_val_6_we1;
reg   [7:0] k_buf_0_val_6_d1;
wire   [7:0] k_buf_0_val_7_address0;
reg    k_buf_0_val_7_ce0;
wire   [7:0] k_buf_0_val_7_q0;
reg    k_buf_0_val_7_ce1;
reg    k_buf_0_val_7_we1;
reg   [7:0] k_buf_0_val_7_d1;
wire   [7:0] k_buf_0_val_8_address0;
reg    k_buf_0_val_8_ce0;
wire   [7:0] k_buf_0_val_8_q0;
reg    k_buf_0_val_8_ce1;
reg    k_buf_0_val_8_we1;
reg   [7:0] k_buf_0_val_8_d1;
wire   [7:0] k_buf_0_val_9_address0;
reg    k_buf_0_val_9_ce0;
wire   [7:0] k_buf_0_val_9_q0;
reg    k_buf_0_val_9_ce1;
reg    k_buf_0_val_9_we1;
reg   [7:0] k_buf_0_val_9_d1;
reg   [31:0] t_V_reg_508;
wire    ap_CS_fsm_state8;
wire   [63:0] tmp_18_fu_1091_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_154;
reg   [7:0] src_kernel_win_0_va_1_fu_158;
reg   [7:0] src_kernel_win_0_va_2_fu_162;
reg   [7:0] src_kernel_win_0_va_3_fu_166;
reg   [7:0] src_kernel_win_0_va_4_fu_170;
reg   [7:0] src_kernel_win_0_va_5_fu_174;
reg   [7:0] src_kernel_win_0_va_6_fu_178;
reg   [7:0] src_kernel_win_0_va_7_fu_182;
reg   [7:0] src_kernel_win_0_va_8_fu_186;
reg   [7:0] src_kernel_win_0_va_9_fu_190;
reg   [7:0] src_kernel_win_0_va_10_fu_194;
reg   [7:0] src_kernel_win_0_va_11_fu_198;
reg   [7:0] src_kernel_win_0_va_12_fu_202;
reg   [7:0] src_kernel_win_0_va_13_fu_206;
reg   [7:0] src_kernel_win_0_va_14_fu_210;
reg   [7:0] src_kernel_win_0_va_15_fu_214;
reg   [7:0] src_kernel_win_0_va_16_fu_218;
reg   [7:0] src_kernel_win_0_va_17_fu_222;
reg   [7:0] src_kernel_win_0_va_18_fu_226;
reg   [7:0] src_kernel_win_0_va_19_fu_230;
reg   [7:0] right_border_buf_0_s_fu_234;
wire   [7:0] col_buf_0_val_0_0_fu_1139_p3;
reg   [7:0] right_border_buf_0_1_fu_238;
wire   [7:0] col_buf_0_val_4_0_fu_1227_p3;
reg   [7:0] right_border_buf_0_2_fu_242;
wire   [7:0] col_buf_0_val_3_0_fu_1205_p3;
reg   [7:0] right_border_buf_0_3_fu_246;
wire   [7:0] col_buf_0_val_2_0_fu_1183_p3;
reg   [7:0] right_border_buf_0_4_fu_250;
wire   [7:0] col_buf_0_val_1_0_fu_1161_p3;
wire   [31:0] tmp_9_fu_685_p2;
wire   [0:0] tmp_75_fu_691_p3;
wire   [0:0] tmp_11_fu_705_p2;
wire   [0:0] rev_fu_699_p2;
wire   [0:0] tmp_76_fu_716_p3;
wire   [31:0] p_assign_8_1_fu_731_p2;
wire   [0:0] tmp_77_fu_737_p3;
wire   [0:0] tmp_331_1_fu_751_p2;
wire   [0:0] rev8_fu_745_p2;
wire   [0:0] tmp_78_fu_762_p3;
wire   [31:0] p_assign_8_2_fu_777_p2;
wire   [0:0] tmp_79_fu_783_p3;
wire   [0:0] tmp_331_2_fu_797_p2;
wire   [0:0] rev9_fu_791_p2;
wire   [0:0] tmp_80_fu_808_p3;
wire   [31:0] p_assign_8_3_fu_823_p2;
wire   [0:0] tmp_81_fu_829_p3;
wire   [0:0] tmp_331_3_fu_843_p2;
wire   [0:0] rev10_fu_837_p2;
wire   [0:0] tmp_82_fu_854_p3;
wire   [31:0] p_assign_8_4_fu_869_p2;
wire   [0:0] tmp_83_fu_875_p3;
wire   [0:0] tmp_331_4_fu_889_p2;
wire   [0:0] rev11_fu_883_p2;
wire   [0:0] tmp_84_fu_900_p3;
wire   [0:0] or_cond_i427_i_fu_710_p2;
wire   [31:0] p_assign_9_fu_724_p3;
wire   [31:0] y_2_fu_915_p3;
wire   [31:0] row_assign_s_fu_923_p2;
wire   [0:0] or_cond_i427_i_1_fu_756_p2;
wire   [31:0] p_assign_9_1_fu_770_p3;
wire   [31:0] y_2_1_fu_932_p3;
wire   [31:0] row_assign_14_1_fu_940_p2;
wire   [0:0] or_cond_i427_i_2_fu_802_p2;
wire   [31:0] p_assign_9_2_fu_816_p3;
wire   [31:0] y_2_2_fu_949_p3;
wire   [31:0] row_assign_14_2_fu_957_p2;
wire   [0:0] or_cond_i427_i_3_fu_848_p2;
wire   [31:0] p_assign_9_3_fu_862_p3;
wire   [31:0] y_2_3_fu_966_p3;
wire   [31:0] row_assign_14_3_fu_974_p2;
wire   [0:0] or_cond_i427_i_4_fu_894_p2;
wire   [31:0] p_assign_9_4_fu_908_p3;
wire   [31:0] y_2_4_fu_983_p3;
wire   [31:0] row_assign_14_4_fu_991_p2;
wire   [29:0] tmp_90_fu_1011_p4;
wire   [31:0] ImagLoc_x_fu_1027_p2;
wire   [0:0] tmp_91_fu_1033_p3;
wire   [0:0] tmp_16_fu_1047_p2;
wire   [0:0] rev12_fu_1041_p2;
wire   [0:0] tmp_92_fu_1058_p3;
wire   [31:0] p_assign_1_fu_1066_p3;
wire   [31:0] x_fu_1073_p3;
wire   [31:0] col_assign_2_fu_1081_p2;
wire   [0:0] icmp_fu_1021_p2;
wire   [7:0] tmp_50_fu_1124_p7;
wire   [7:0] tmp_51_fu_1146_p7;
wire   [7:0] tmp_52_fu_1168_p7;
wire   [7:0] tmp_53_fu_1190_p7;
wire   [7:0] tmp_54_fu_1212_p7;
wire   [7:0] tmp_55_fu_1259_p7;
wire   [7:0] tmp_56_fu_1281_p7;
wire   [7:0] tmp_57_fu_1303_p7;
wire   [7:0] tmp_58_fu_1325_p7;
wire   [7:0] tmp_59_fu_1347_p7;
wire  signed [2:0] r_V_8_1_fu_1385_p0;
wire   [7:0] r_V_8_1_fu_1385_p1;
wire  signed [4:0] r_V_8_1_3_fu_1398_p0;
wire   [7:0] r_V_8_1_3_fu_1398_p1;
wire  signed [12:0] r_V_8_1_3_fu_1398_p2;
wire   [8:0] OP1_V_0_cast_fu_1472_p1;
wire  signed [8:0] r_V_8_fu_1476_p2;
wire  signed [11:0] grp_fu_1933_p3;
wire  signed [12:0] grp_fu_1941_p3;
wire   [10:0] p_shl_fu_1510_p3;
wire   [11:0] p_shl_cast_fu_1517_p1;
wire   [11:0] r_V_8_1_1_fu_1521_p2;
wire  signed [13:0] tmp_350_1_1_cast_cas_fu_1527_p1;
wire  signed [13:0] p_Val2_19_0_2_cast_fu_1497_p1;
wire  signed [11:0] grp_fu_1957_p3;
wire  signed [12:0] grp_fu_1949_p3;
wire   [13:0] tmp6_fu_1531_p2;
wire  signed [13:0] tmp7_cast_fu_1540_p1;
wire   [4:0] r_V_8_3_2_fu_1560_p0;
wire   [7:0] r_V_8_3_2_fu_1560_p1;
wire   [10:0] r_V_8_3_3_fu_1565_p3;
wire   [3:0] r_V_8_4_2_fu_1592_p0;
wire   [7:0] r_V_8_4_2_fu_1592_p1;
wire  signed [12:0] grp_fu_1995_p3;
wire   [11:0] grp_fu_1980_p3;
wire  signed [9:0] grp_fu_1987_p3;
wire  signed [12:0] grp_fu_1972_p3;
wire  signed [12:0] tmp43_cast_fu_1610_p1;
(* use_dsp48 = "no" *) wire   [12:0] tmp22_fu_1613_p2;
wire   [13:0] tmp39_cast_fu_1607_p1;
wire  signed [13:0] tmp41_cast_fu_1618_p1;
wire  signed [14:0] p_Val2_19_1_1_cast_fu_1721_p1;
wire  signed [14:0] tmp9_cast_fu_1724_p1;
wire  signed [3:0] r_V_8_1_4_fu_1736_p0;
wire   [7:0] r_V_8_1_4_fu_1736_p1;
wire  signed [14:0] grp_fu_2020_p3;
wire  signed [11:0] grp_fu_2011_p3;
wire  signed [15:0] tmp11_cast_fu_1749_p1;
wire  signed [15:0] tmp12_cast_fu_1752_p1;
wire   [5:0] r_V_8_2_3_fu_1768_p0;
wire   [7:0] r_V_8_2_3_fu_1768_p1;
wire  signed [14:0] tmp_60_fu_1755_p1;
wire  signed [13:0] grp_fu_2029_p3;
wire   [15:0] p_Val2_19_2_2_fu_1758_p2;
wire  signed [15:0] tmp35_cast_fu_1781_p1;
wire   [15:0] tmp14_fu_1784_p2;
wire  signed [15:0] tmp36_cast_fu_1790_p1;
wire   [15:0] tmp17_fu_1793_p2;
wire  signed [15:0] tmp38_cast_fu_1799_p1;
wire   [15:0] p_Val2_s_fu_1802_p2;
(* use_dsp48 = "no" *) wire   [14:0] tmp_61_fu_1773_p2;
wire  signed [14:0] tmp46_cast_fu_1816_p1;
wire   [14:0] tmp24_fu_1819_p2;
wire  signed [14:0] tmp47_cast_fu_1825_p1;
wire   [14:0] tmp25_fu_1828_p2;
wire  signed [14:0] tmp49_cast_fu_1834_p1;
wire   [0:0] tmp_26_fu_1884_p2;
wire   [0:0] tmp_2_i_i_fu_1879_p2;
wire   [0:0] brmerge_i_i_i_i_fu_1894_p2;
wire   [0:0] underflow_fu_1889_p2;
wire   [0:0] underflow_not_i_i_fu_1898_p2;
wire   [14:0] p_Val2_9_fu_1903_p3;
wire   [14:0] p_Val2_7_i_i_fu_1910_p3;
wire  signed [4:0] grp_fu_1926_p0;
wire   [7:0] grp_fu_1926_p1;
wire  signed [2:0] grp_fu_1933_p0;
wire   [7:0] grp_fu_1933_p1;
wire  signed [3:0] grp_fu_1941_p0;
wire   [7:0] grp_fu_1941_p1;
wire  signed [2:0] grp_fu_1949_p0;
wire   [7:0] grp_fu_1949_p1;
wire  signed [1:0] grp_fu_1957_p0;
wire   [7:0] grp_fu_1957_p1;
wire   [4:0] grp_fu_1965_p0;
wire   [7:0] grp_fu_1965_p1;
wire  signed [2:0] grp_fu_1972_p0;
wire   [7:0] grp_fu_1972_p1;
wire   [10:0] grp_fu_1972_p2;
wire   [3:0] grp_fu_1980_p0;
wire   [7:0] grp_fu_1980_p1;
wire   [11:0] grp_fu_2003_p3;
wire  signed [1:0] grp_fu_1987_p0;
wire   [7:0] grp_fu_1987_p1;
wire   [7:0] grp_fu_1987_p2;
wire  signed [3:0] grp_fu_1995_p0;
wire   [7:0] grp_fu_1995_p1;
wire   [12:0] grp_fu_1995_p2;
wire   [3:0] grp_fu_2003_p0;
wire   [7:0] grp_fu_2003_p1;
wire   [11:0] grp_fu_2003_p2;
wire  signed [4:0] grp_fu_2011_p0;
wire   [7:0] grp_fu_2011_p1;
wire   [11:0] grp_fu_2011_p2;
wire  signed [5:0] grp_fu_2020_p0;
wire   [7:0] grp_fu_2020_p1;
wire   [14:0] grp_fu_2020_p2;
wire  signed [4:0] grp_fu_2029_p0;
wire   [7:0] grp_fu_2029_p1;
wire   [13:0] grp_fu_2029_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [12:0] grp_fu_1926_p10;
wire   [10:0] grp_fu_1933_p10;
wire   [11:0] grp_fu_1941_p10;
wire   [10:0] grp_fu_1949_p10;
wire   [9:0] grp_fu_1957_p10;
wire   [12:0] grp_fu_1965_p10;
wire   [10:0] grp_fu_1972_p10;
wire   [12:0] grp_fu_1972_p20;
wire   [11:0] grp_fu_1980_p10;
wire   [9:0] grp_fu_1987_p10;
wire   [9:0] grp_fu_1987_p20;
wire   [11:0] grp_fu_1995_p10;
wire   [11:0] grp_fu_2003_p10;
wire   [11:0] grp_fu_2011_p10;
wire   [13:0] grp_fu_2020_p10;
wire   [12:0] grp_fu_2029_p10;
wire   [12:0] r_V_8_1_3_fu_1398_p10;
wire   [11:0] r_V_8_1_4_fu_1736_p10;
wire   [10:0] r_V_8_1_fu_1385_p10;
wire   [13:0] r_V_8_2_3_fu_1768_p10;
wire   [12:0] r_V_8_3_2_fu_1560_p10;
wire   [11:0] r_V_8_4_2_fu_1592_p10;
reg    ap_condition_526;
reg    ap_condition_67;
reg    ap_condition_532;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2439),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
k_buf_0_val_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_6_address0),
    .ce0(k_buf_0_val_6_ce0),
    .q0(k_buf_0_val_6_q0),
    .address1(k_buf_0_val_6_addr_reg_2454),
    .ce1(k_buf_0_val_6_ce1),
    .we1(k_buf_0_val_6_we1),
    .d1(k_buf_0_val_6_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
k_buf_0_val_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_7_address0),
    .ce0(k_buf_0_val_7_ce0),
    .q0(k_buf_0_val_7_q0),
    .address1(k_buf_0_val_7_addr_reg_2460),
    .ce1(k_buf_0_val_7_ce1),
    .we1(k_buf_0_val_7_we1),
    .d1(k_buf_0_val_7_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
k_buf_0_val_8_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_8_address0),
    .ce0(k_buf_0_val_8_ce0),
    .q0(k_buf_0_val_8_q0),
    .address1(k_buf_0_val_8_addr_reg_2466),
    .ce1(k_buf_0_val_8_ce1),
    .we1(k_buf_0_val_8_we1),
    .d1(k_buf_0_val_8_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
k_buf_0_val_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_9_address0),
    .ce0(k_buf_0_val_9_ce0),
    .q0(k_buf_0_val_9_q0),
    .address1(k_buf_0_val_9_addr_reg_2472),
    .ce1(k_buf_0_val_9_ce1),
    .we1(k_buf_0_val_9_we1),
    .d1(k_buf_0_val_9_d1)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U82(
    .din0(right_border_buf_0_s_fu_234),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(tmp_93_reg_2445),
    .dout(tmp_50_fu_1124_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U83(
    .din0(right_border_buf_0_4_fu_250),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(tmp_93_reg_2445),
    .dout(tmp_51_fu_1146_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U84(
    .din0(right_border_buf_0_3_fu_246),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(tmp_93_reg_2445),
    .dout(tmp_52_fu_1168_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U85(
    .din0(right_border_buf_0_2_fu_242),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(tmp_93_reg_2445),
    .dout(tmp_53_fu_1190_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U86(
    .din0(right_border_buf_0_1_fu_238),
    .din1(8'd0),
    .din2(8'd0),
    .din3(8'd0),
    .din4(8'd0),
    .din5(tmp_93_reg_2445),
    .dout(tmp_54_fu_1212_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U87(
    .din0(col_buf_0_val_0_0_fu_1139_p3),
    .din1(col_buf_0_val_1_0_fu_1161_p3),
    .din2(col_buf_0_val_2_0_fu_1183_p3),
    .din3(col_buf_0_val_3_0_fu_1205_p3),
    .din4(col_buf_0_val_4_0_fu_1227_p3),
    .din5(tmp_85_reg_2392),
    .dout(tmp_55_fu_1259_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U88(
    .din0(col_buf_0_val_0_0_fu_1139_p3),
    .din1(col_buf_0_val_1_0_fu_1161_p3),
    .din2(col_buf_0_val_2_0_fu_1183_p3),
    .din3(col_buf_0_val_3_0_fu_1205_p3),
    .din4(col_buf_0_val_4_0_fu_1227_p3),
    .din5(tmp_86_reg_2397),
    .dout(tmp_56_fu_1281_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U89(
    .din0(col_buf_0_val_0_0_fu_1139_p3),
    .din1(col_buf_0_val_1_0_fu_1161_p3),
    .din2(col_buf_0_val_2_0_fu_1183_p3),
    .din3(col_buf_0_val_3_0_fu_1205_p3),
    .din4(col_buf_0_val_4_0_fu_1227_p3),
    .din5(tmp_87_reg_2402),
    .dout(tmp_57_fu_1303_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U90(
    .din0(col_buf_0_val_0_0_fu_1139_p3),
    .din1(col_buf_0_val_1_0_fu_1161_p3),
    .din2(col_buf_0_val_2_0_fu_1183_p3),
    .din3(col_buf_0_val_3_0_fu_1205_p3),
    .din4(col_buf_0_val_4_0_fu_1227_p3),
    .din5(tmp_88_reg_2407),
    .dout(tmp_58_fu_1325_p7)
);

Haaris_Core_mux_5jbC #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
Haaris_Core_mux_5jbC_U91(
    .din0(col_buf_0_val_0_0_fu_1139_p3),
    .din1(col_buf_0_val_1_0_fu_1161_p3),
    .din2(col_buf_0_val_2_0_fu_1183_p3),
    .din3(col_buf_0_val_3_0_fu_1205_p3),
    .din4(col_buf_0_val_4_0_fu_1227_p3),
    .din5(tmp_89_reg_2412),
    .dout(tmp_59_fu_1347_p7)
);

Haaris_Core_mac_mkbM #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 14 ))
Haaris_Core_mac_mkbM_U92(
    .din0(grp_fu_1926_p0),
    .din1(grp_fu_1926_p1),
    .din2(r_V_8_1_3_fu_1398_p2),
    .dout(grp_fu_1926_p3)
);

Haaris_Core_mac_mlbW #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 12 ))
Haaris_Core_mac_mlbW_U93(
    .din0(grp_fu_1933_p0),
    .din1(grp_fu_1933_p1),
    .din2(r_V_8_fu_1476_p2),
    .dout(grp_fu_1933_p3)
);

Haaris_Core_mac_mmb6 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 13 ))
Haaris_Core_mac_mmb6_U94(
    .din0(grp_fu_1941_p0),
    .din1(grp_fu_1941_p1),
    .din2(grp_fu_1933_p3),
    .dout(grp_fu_1941_p3)
);

Haaris_Core_mac_mncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 13 ))
Haaris_Core_mac_mncg_U95(
    .din0(grp_fu_1949_p0),
    .din1(grp_fu_1949_p1),
    .din2(grp_fu_1957_p3),
    .dout(grp_fu_1949_p3)
);

Haaris_Core_mac_mocq #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 12 ))
Haaris_Core_mac_mocq_U96(
    .din0(grp_fu_1957_p0),
    .din1(grp_fu_1957_p1),
    .din2(r_V_8_1_reg_2516),
    .dout(grp_fu_1957_p3)
);

Haaris_Core_mac_mpcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 14 ))
Haaris_Core_mac_mpcA_U97(
    .din0(grp_fu_1965_p0),
    .din1(grp_fu_1965_p1),
    .din2(grp_fu_1995_p3),
    .dout(grp_fu_1965_p3)
);

Haaris_Core_mac_mqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 3 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 13 ))
Haaris_Core_mac_mqcK_U98(
    .din0(grp_fu_1972_p0),
    .din1(grp_fu_1972_p1),
    .din2(grp_fu_1972_p2),
    .dout(grp_fu_1972_p3)
);

Haaris_Core_mac_mrcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
Haaris_Core_mac_mrcU_U99(
    .din0(grp_fu_1980_p0),
    .din1(grp_fu_1980_p1),
    .din2(grp_fu_2003_p3),
    .dout(grp_fu_1980_p3)
);

Haaris_Core_mac_msc4 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .dout_WIDTH( 10 ))
Haaris_Core_mac_msc4_U100(
    .din0(grp_fu_1987_p0),
    .din1(grp_fu_1987_p1),
    .din2(grp_fu_1987_p2),
    .dout(grp_fu_1987_p3)
);

Haaris_Core_mac_mtde #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 13 ),
    .dout_WIDTH( 13 ))
Haaris_Core_mac_mtde_U101(
    .din0(grp_fu_1995_p0),
    .din1(grp_fu_1995_p1),
    .din2(grp_fu_1995_p2),
    .dout(grp_fu_1995_p3)
);

Haaris_Core_mac_mrcU #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
Haaris_Core_mac_mrcU_U102(
    .din0(grp_fu_2003_p0),
    .din1(grp_fu_2003_p1),
    .din2(grp_fu_2003_p2),
    .dout(grp_fu_2003_p3)
);

Haaris_Core_mac_mudo #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 12 ))
Haaris_Core_mac_mudo_U103(
    .din0(grp_fu_2011_p0),
    .din1(grp_fu_2011_p1),
    .din2(grp_fu_2011_p2),
    .dout(grp_fu_2011_p3)
);

Haaris_Core_mac_mvdy #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 6 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 15 ),
    .dout_WIDTH( 15 ))
Haaris_Core_mac_mvdy_U104(
    .din0(grp_fu_2020_p0),
    .din1(grp_fu_2020_p1),
    .din2(grp_fu_2020_p2),
    .dout(grp_fu_2020_p3)
);

Haaris_Core_mac_mwdI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
Haaris_Core_mac_mwdI_U105(
    .din0(grp_fu_2029_p0),
    .din1(grp_fu_2029_p1),
    .din2(grp_fu_2029_p2),
    .dout(grp_fu_2029_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond393_i_fu_634_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state3)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((exitcond393_i_fu_634_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond392_i_fu_1000_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        t_V_7_reg_519 <= j_V_fu_1005_p2;
    end else if (((exitcond393_i_fu_634_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_7_reg_519 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        t_V_reg_508 <= i_V_reg_2352;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_508 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        OP2_V_0_1_cast_reg_2248 <= OP2_V_0_1_cast_fu_554_p1;
        OP2_V_0_2_cast_reg_2253 <= OP2_V_0_2_cast_fu_558_p1;
        OP2_V_0_3_cast_reg_2258 <= OP2_V_0_3_cast_fu_562_p1;
        OP2_V_0_4_cast_reg_2263 <= OP2_V_0_4_cast_fu_566_p1;
        OP2_V_1_2_cast_reg_2273 <= OP2_V_1_2_cast_fu_574_p1;
        OP2_V_1_3_cast_reg_2278 <= OP2_V_1_3_cast_fu_578_p1;
        OP2_V_1_4_cast_reg_2283 <= OP2_V_1_4_cast_fu_582_p1;
        OP2_V_1_cast_reg_2268 <= OP2_V_1_cast_fu_570_p1;
        OP2_V_2_1_cast_reg_2293 <= OP2_V_2_1_cast_fu_590_p1;
        OP2_V_2_3_cast_reg_2298[5 : 0] <= OP2_V_2_3_cast_fu_594_p1[5 : 0];
        OP2_V_2_4_cast_reg_2303[4 : 0] <= OP2_V_2_4_cast_fu_598_p1[4 : 0];
        OP2_V_2_cast_reg_2288 <= OP2_V_2_cast_fu_586_p1;
        OP2_V_3_1_cast_reg_2313 <= OP2_V_3_1_cast_fu_606_p1;
        OP2_V_3_2_cast_reg_2318[4 : 0] <= OP2_V_3_2_cast_fu_610_p1[4 : 0];
        OP2_V_3_4_cast_reg_2323[3 : 0] <= OP2_V_3_4_cast_fu_614_p1[3 : 0];
        OP2_V_3_cast_reg_2308 <= OP2_V_3_cast_fu_602_p1;
        OP2_V_4_1_cast_reg_2333 <= OP2_V_4_1_cast_fu_622_p1;
        OP2_V_4_2_cast_reg_2338[3 : 0] <= OP2_V_4_2_cast_fu_626_p1[3 : 0];
        OP2_V_4_3_cast_reg_2343[3 : 0] <= OP2_V_4_3_cast_fu_630_p1[3 : 0];
        OP2_V_4_cast_reg_2328 <= OP2_V_4_cast_fu_618_p1;
        p_neg397_i_reg_2234 <= p_neg397_i_fu_548_p2;
        tmp_1_reg_2223 <= tmp_1_fu_536_p2;
        tmp_2_reg_2228 <= tmp_2_fu_542_p2;
        tmp_s_reg_2218 <= tmp_s_fu_530_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond392_i_fu_1000_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        brmerge_reg_2430 <= brmerge_fu_1086_p2;
        k_buf_0_val_5_addr_reg_2439 <= tmp_18_fu_1091_p1;
        k_buf_0_val_6_addr_reg_2454 <= tmp_18_fu_1091_p1;
        k_buf_0_val_7_addr_reg_2460 <= tmp_18_fu_1091_p1;
        k_buf_0_val_8_addr_reg_2466 <= tmp_18_fu_1091_p1;
        k_buf_0_val_9_addr_reg_2472 <= tmp_18_fu_1091_p1;
        or_cond_i_i_reg_2426 <= or_cond_i_i_fu_1052_p2;
        or_cond_i_reg_2478 <= or_cond_i_fu_1104_p2;
        tmp_93_reg_2445 <= tmp_93_fu_1100_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond392_i_reg_2417 <= exitcond392_i_fu_1000_p2;
        exitcond392_i_reg_2417_pp0_iter1_reg <= exitcond392_i_reg_2417;
        or_cond_i_reg_2478_pp0_iter1_reg <= or_cond_i_reg_2478;
        src_kernel_win_0_va_20_reg_2482 <= src_kernel_win_0_va_20_fu_1274_p3;
        src_kernel_win_0_va_21_reg_2488 <= src_kernel_win_0_va_21_fu_1296_p3;
        src_kernel_win_0_va_22_reg_2494 <= src_kernel_win_0_va_22_fu_1318_p3;
        src_kernel_win_0_va_23_reg_2500 <= src_kernel_win_0_va_23_fu_1340_p3;
        src_kernel_win_0_va_24_reg_2505 <= src_kernel_win_0_va_24_fu_1362_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond392_i_reg_2417_pp0_iter2_reg <= exitcond392_i_reg_2417_pp0_iter1_reg;
        or_cond_i_reg_2478_pp0_iter2_reg <= or_cond_i_reg_2478_pp0_iter1_reg;
        or_cond_i_reg_2478_pp0_iter3_reg <= or_cond_i_reg_2478_pp0_iter2_reg;
        src_kernel_win_0_va_22_reg_2494_pp0_iter2_reg <= src_kernel_win_0_va_22_reg_2494;
        src_kernel_win_0_va_23_reg_2500_pp0_iter2_reg <= src_kernel_win_0_va_23_reg_2500;
        tmp9_reg_2521_pp0_iter2_reg <= tmp9_reg_2521;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_2352 <= i_V_fu_639_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2478_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        isneg_reg_2548 <= p_Val2_s_fu_1802_p2[32'd15];
        newsignbit_reg_2561 <= p_Val2_s_fu_1802_p2[32'd14];
        p_Val2_6_reg_2555 <= p_Val2_6_fu_1837_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2478_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_19_1_1_reg_2531 <= p_Val2_19_1_1_fu_1543_p2;
        src_kernel_win_0_va_31_reg_2526 <= src_kernel_win_0_va_6_fu_178;
        tmp23_reg_2542 <= tmp23_fu_1622_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2478 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_V_8_1_reg_2516 <= r_V_8_1_fu_1385_p2;
        src_kernel_win_0_va_38_reg_2511 <= src_kernel_win_0_va_14_fu_210;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1))) begin
        right_border_buf_0_1_fu_238 <= col_buf_0_val_4_0_fu_1227_p3;
        right_border_buf_0_2_fu_242 <= col_buf_0_val_3_0_fu_1205_p3;
        right_border_buf_0_3_fu_246 <= col_buf_0_val_2_0_fu_1183_p3;
        right_border_buf_0_4_fu_250 <= col_buf_0_val_1_0_fu_1161_p3;
        right_border_buf_0_s_fu_234 <= col_buf_0_val_0_0_fu_1139_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond392_i_reg_2417_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        src_kernel_win_0_va_10_fu_194 <= src_kernel_win_0_va_9_fu_190;
        src_kernel_win_0_va_11_fu_198 <= src_kernel_win_0_va_10_fu_194;
        src_kernel_win_0_va_8_fu_186 <= src_kernel_win_0_va_22_reg_2494_pp0_iter2_reg;
        src_kernel_win_0_va_9_fu_190 <= src_kernel_win_0_va_8_fu_186;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond392_i_reg_2417 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        src_kernel_win_0_va_12_fu_202 <= src_kernel_win_0_va_23_fu_1340_p3;
        src_kernel_win_0_va_13_fu_206 <= src_kernel_win_0_va_12_fu_202;
        src_kernel_win_0_va_14_fu_210 <= src_kernel_win_0_va_13_fu_206;
        src_kernel_win_0_va_15_fu_214 <= src_kernel_win_0_va_14_fu_210;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond392_i_reg_2417_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        src_kernel_win_0_va_16_fu_218 <= src_kernel_win_0_va_24_reg_2505;
        src_kernel_win_0_va_17_fu_222 <= src_kernel_win_0_va_16_fu_218;
        src_kernel_win_0_va_18_fu_226 <= src_kernel_win_0_va_17_fu_222;
        src_kernel_win_0_va_19_fu_230 <= src_kernel_win_0_va_18_fu_226;
        src_kernel_win_0_va_1_fu_158 <= src_kernel_win_0_va_fu_154;
        src_kernel_win_0_va_2_fu_162 <= src_kernel_win_0_va_1_fu_158;
        src_kernel_win_0_va_3_fu_166 <= src_kernel_win_0_va_2_fu_162;
        src_kernel_win_0_va_4_fu_170 <= src_kernel_win_0_va_21_reg_2488;
        src_kernel_win_0_va_5_fu_174 <= src_kernel_win_0_va_4_fu_170;
        src_kernel_win_0_va_6_fu_178 <= src_kernel_win_0_va_5_fu_174;
        src_kernel_win_0_va_7_fu_182 <= src_kernel_win_0_va_6_fu_178;
        src_kernel_win_0_va_fu_154 <= src_kernel_win_0_va_20_reg_2482;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2478_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        tmp16_reg_2536 <= grp_fu_1965_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2478 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp9_reg_2521 <= grp_fu_1926_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond393_i_fu_634_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_274_not_reg_2361 <= tmp_274_not_fu_650_p2;
        tmp_304_3_reg_2375 <= tmp_304_3_fu_668_p2;
        tmp_304_4_reg_2379 <= tmp_304_4_fu_674_p2;
        tmp_3_reg_2357 <= tmp_3_fu_645_p2;
        tmp_4_reg_2366 <= tmp_4_fu_656_p2;
        tmp_7_reg_2371 <= tmp_7_fu_662_p2;
        tmp_85_reg_2392 <= tmp_85_fu_928_p1;
        tmp_86_reg_2397 <= tmp_86_fu_945_p1;
        tmp_87_reg_2402 <= tmp_87_fu_962_p1;
        tmp_88_reg_2407 <= tmp_88_fu_979_p1;
        tmp_89_reg_2412 <= tmp_89_fu_996_p1;
        tmp_8_reg_2383 <= tmp_8_fu_680_p2;
    end
end

always @ (*) begin
    if ((exitcond392_i_fu_1000_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond393_i_fu_634_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond393_i_fu_634_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_304_4_reg_2379 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_304_4_reg_2379 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_buf_0_val_6_ce0 = 1'b1;
    end else begin
        k_buf_0_val_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_304_3_reg_2375 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_6_ce1 = 1'b1;
    end else begin
        k_buf_0_val_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_67)) begin
        if ((ap_predicate_op231_read_state4 == 1'b1)) begin
            k_buf_0_val_6_d1 = k_buf_0_val_5_q0;
        end else if ((1'b1 == ap_condition_526)) begin
            k_buf_0_val_6_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_6_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_6_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_304_3_reg_2375 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_6_we1 = 1'b1;
    end else begin
        k_buf_0_val_6_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_buf_0_val_7_ce0 = 1'b1;
    end else begin
        k_buf_0_val_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_7_ce1 = 1'b1;
    end else begin
        k_buf_0_val_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_67)) begin
        if ((ap_predicate_op231_read_state4 == 1'b1)) begin
            k_buf_0_val_7_d1 = k_buf_0_val_6_q0;
        end else if ((1'b1 == ap_condition_532)) begin
            k_buf_0_val_7_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_7_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_7_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_7_we1 = 1'b1;
    end else begin
        k_buf_0_val_7_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_buf_0_val_8_ce0 = 1'b1;
    end else begin
        k_buf_0_val_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_8_ce1 = 1'b1;
    end else begin
        k_buf_0_val_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_67)) begin
        if ((ap_predicate_op231_read_state4 == 1'b1)) begin
            k_buf_0_val_8_d1 = k_buf_0_val_7_q0;
        end else if ((1'b1 == ap_condition_532)) begin
            k_buf_0_val_8_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_8_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_8_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_8_we1 = 1'b1;
    end else begin
        k_buf_0_val_8_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        k_buf_0_val_9_ce0 = 1'b1;
    end else begin
        k_buf_0_val_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_9_ce1 = 1'b1;
    end else begin
        k_buf_0_val_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_67)) begin
        if ((ap_predicate_op231_read_state4 == 1'b1)) begin
            k_buf_0_val_9_d1 = k_buf_0_val_8_q0;
        end else if ((1'b1 == ap_condition_532)) begin
            k_buf_0_val_9_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_9_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_9_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)))) begin
        k_buf_0_val_9_we1 = 1'b1;
    end else begin
        k_buf_0_val_9_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_V_V_blk_n = p_dst_data_stream_V_V_full_n;
    end else begin
        p_dst_data_stream_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        p_dst_data_stream_V_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_reg_2357 == 1'd1) & (tmp_4_reg_2366 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_4_reg_2366 == 1'd0) & (or_cond_i_i_reg_2426 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op231_read_state4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_predicate_op218_read_state4 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond393_i_fu_634_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((exitcond392_i_fu_1000_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((exitcond392_i_fu_1000_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_1027_p2 = ($signed(32'd4294967294) + $signed(t_V_7_reg_519));

assign OP1_V_0_cast_fu_1472_p1 = src_kernel_win_0_va_19_fu_230;

assign OP2_V_0_1_cast_fu_554_p1 = $signed(p_kernel_val_0_V_1_read);

assign OP2_V_0_2_cast_fu_558_p1 = $signed(p_kernel_val_0_V_2_read);

assign OP2_V_0_3_cast_fu_562_p1 = $signed(p_kernel_val_0_V_3_read);

assign OP2_V_0_4_cast_fu_566_p1 = $signed(p_kernel_val_0_V_4_read);

assign OP2_V_1_2_cast_fu_574_p1 = $signed(p_kernel_val_1_V_2_read);

assign OP2_V_1_3_cast_fu_578_p1 = $signed(p_kernel_val_1_V_3_read);

assign OP2_V_1_4_cast_fu_582_p1 = $signed(p_kernel_val_1_V_4_read);

assign OP2_V_1_cast_fu_570_p1 = $signed(p_kernel_val_1_V_0_read);

assign OP2_V_2_1_cast_fu_590_p1 = $signed(p_kernel_val_2_V_1_read);

assign OP2_V_2_3_cast_fu_594_p1 = p_kernel_val_2_V_3_read;

assign OP2_V_2_4_cast_fu_598_p1 = p_kernel_val_2_V_4_read;

assign OP2_V_2_cast_fu_586_p1 = $signed(p_kernel_val_2_V_0_read);

assign OP2_V_3_1_cast_fu_606_p1 = $signed(p_kernel_val_3_V_1_read);

assign OP2_V_3_2_cast_fu_610_p1 = p_kernel_val_3_V_2_read;

assign OP2_V_3_4_cast_fu_614_p1 = p_kernel_val_3_V_4_read;

assign OP2_V_3_cast_fu_602_p1 = $signed(p_kernel_val_3_V_0_read);

assign OP2_V_4_1_cast_fu_622_p1 = $signed(p_kernel_val_4_V_1_read);

assign OP2_V_4_2_cast_fu_626_p1 = p_kernel_val_4_V_2_read;

assign OP2_V_4_3_cast_fu_630_p1 = p_kernel_val_4_V_3_read;

assign OP2_V_4_cast_fu_618_p1 = $signed(p_kernel_val_4_V_0_read);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op231_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op218_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op231_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op218_read_state4 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_V_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op231_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op218_read_state4 == 1'b1)))));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op231_read_state4 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op218_read_state4 == 1'b1)));
end

assign ap_block_state5_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter4 = ((or_cond_i_reg_2478_pp0_iter3_reg == 1'd1) & (p_dst_data_stream_V_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_526 = ((tmp_4_reg_2366 == 1'd0) & (tmp_304_3_reg_2375 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1));
end

always @ (*) begin
    ap_condition_532 = ((tmp_4_reg_2366 == 1'd0) & (tmp_7_reg_2371 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1));
end

always @ (*) begin
    ap_condition_67 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op218_read_state4 = ((tmp_4_reg_2366 == 1'd0) & (or_cond_i_i_reg_2426 == 1'd1));
end

always @ (*) begin
    ap_predicate_op231_read_state4 = ((tmp_3_reg_2357 == 1'd1) & (tmp_4_reg_2366 == 1'd1) & (or_cond_i_i_reg_2426 == 1'd1));
end

assign brmerge_fu_1086_p2 = (tmp_274_not_reg_2361 | tmp_16_fu_1047_p2);

assign brmerge_i_i_i_i_fu_1894_p2 = (newsignbit_reg_2561 ^ isneg_reg_2548);

assign col_assign_2_fu_1081_p2 = (tmp_2_reg_2228 - x_fu_1073_p3);

assign col_buf_0_val_0_0_fu_1139_p3 = ((brmerge_reg_2430[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_50_fu_1124_p7);

assign col_buf_0_val_1_0_fu_1161_p3 = ((brmerge_reg_2430[0:0] === 1'b1) ? k_buf_0_val_6_q0 : tmp_51_fu_1146_p7);

assign col_buf_0_val_2_0_fu_1183_p3 = ((brmerge_reg_2430[0:0] === 1'b1) ? k_buf_0_val_7_q0 : tmp_52_fu_1168_p7);

assign col_buf_0_val_3_0_fu_1205_p3 = ((brmerge_reg_2430[0:0] === 1'b1) ? k_buf_0_val_8_q0 : tmp_53_fu_1190_p7);

assign col_buf_0_val_4_0_fu_1227_p3 = ((brmerge_reg_2430[0:0] === 1'b1) ? k_buf_0_val_9_q0 : tmp_54_fu_1212_p7);

assign exitcond392_i_fu_1000_p2 = ((t_V_7_reg_519 == tmp_s_reg_2218) ? 1'b1 : 1'b0);

assign exitcond393_i_fu_634_p2 = ((t_V_reg_508 == tmp_1_reg_2223) ? 1'b1 : 1'b0);

assign grp_fu_1926_p0 = OP2_V_1_2_cast_reg_2273;

assign grp_fu_1926_p1 = grp_fu_1926_p10;

assign grp_fu_1926_p10 = src_kernel_win_0_va_13_fu_206;

assign grp_fu_1933_p0 = OP2_V_0_1_cast_reg_2248;

assign grp_fu_1933_p1 = grp_fu_1933_p10;

assign grp_fu_1933_p10 = src_kernel_win_0_va_18_fu_226;

assign grp_fu_1941_p0 = OP2_V_0_2_cast_reg_2253;

assign grp_fu_1941_p1 = grp_fu_1941_p10;

assign grp_fu_1941_p10 = src_kernel_win_0_va_17_fu_222;

assign grp_fu_1949_p0 = OP2_V_0_3_cast_reg_2258;

assign grp_fu_1949_p1 = grp_fu_1949_p10;

assign grp_fu_1949_p10 = src_kernel_win_0_va_16_fu_218;

assign grp_fu_1957_p0 = OP2_V_0_4_cast_reg_2263;

assign grp_fu_1957_p1 = grp_fu_1957_p10;

assign grp_fu_1957_p10 = src_kernel_win_0_va_24_reg_2505;

assign grp_fu_1965_p0 = OP2_V_2_4_cast_reg_2303;

assign grp_fu_1965_p1 = grp_fu_1965_p10;

assign grp_fu_1965_p10 = src_kernel_win_0_va_22_reg_2494;

assign grp_fu_1972_p0 = OP2_V_3_cast_reg_2308;

assign grp_fu_1972_p1 = grp_fu_1972_p10;

assign grp_fu_1972_p10 = src_kernel_win_0_va_7_fu_182;

assign grp_fu_1972_p2 = grp_fu_1972_p20;

assign grp_fu_1972_p20 = r_V_8_3_3_fu_1565_p3;

assign grp_fu_1980_p0 = OP2_V_3_4_cast_reg_2323;

assign grp_fu_1980_p1 = grp_fu_1980_p10;

assign grp_fu_1980_p10 = src_kernel_win_0_va_21_reg_2488;

assign grp_fu_1987_p0 = OP2_V_4_cast_reg_2328;

assign grp_fu_1987_p1 = grp_fu_1987_p10;

assign grp_fu_1987_p10 = src_kernel_win_0_va_3_fu_166;

assign grp_fu_1987_p2 = grp_fu_1987_p20;

assign grp_fu_1987_p20 = src_kernel_win_0_va_20_reg_2482;

assign grp_fu_1995_p0 = OP2_V_4_1_cast_reg_2333;

assign grp_fu_1995_p1 = grp_fu_1995_p10;

assign grp_fu_1995_p10 = src_kernel_win_0_va_2_fu_162;

assign grp_fu_1995_p2 = (r_V_8_3_2_fu_1560_p0 * r_V_8_3_2_fu_1560_p1);

assign grp_fu_2003_p0 = OP2_V_4_3_cast_reg_2343;

assign grp_fu_2003_p1 = grp_fu_2003_p10;

assign grp_fu_2003_p10 = src_kernel_win_0_va_fu_154;

assign grp_fu_2003_p2 = (r_V_8_4_2_fu_1592_p0 * r_V_8_4_2_fu_1592_p1);

assign grp_fu_2011_p0 = OP2_V_2_cast_reg_2288;

assign grp_fu_2011_p1 = grp_fu_2011_p10;

assign grp_fu_2011_p10 = src_kernel_win_0_va_11_fu_198;

assign grp_fu_2011_p2 = ($signed(r_V_8_1_4_fu_1736_p0) * $signed({{1'b0}, {r_V_8_1_4_fu_1736_p1}}));

assign grp_fu_2020_p0 = OP2_V_2_1_cast_reg_2293;

assign grp_fu_2020_p1 = grp_fu_2020_p10;

assign grp_fu_2020_p10 = src_kernel_win_0_va_10_fu_194;

assign grp_fu_2020_p2 = ($signed(p_Val2_19_1_1_cast_fu_1721_p1) + $signed(tmp9_cast_fu_1724_p1));

assign grp_fu_2029_p0 = OP2_V_3_1_cast_reg_2313;

assign grp_fu_2029_p1 = grp_fu_2029_p10;

assign grp_fu_2029_p10 = src_kernel_win_0_va_31_reg_2526;

assign grp_fu_2029_p2 = (r_V_8_2_3_fu_1768_p0 * r_V_8_2_3_fu_1768_p1);

assign i_V_fu_639_p2 = (t_V_reg_508 + 32'd1);

assign icmp_fu_1021_p2 = ((tmp_90_fu_1011_p4 != 30'd0) ? 1'b1 : 1'b0);

assign j_V_fu_1005_p2 = (t_V_7_reg_519 + 32'd1);

assign k_buf_0_val_5_address0 = tmp_18_fu_1091_p1;

assign k_buf_0_val_6_address0 = tmp_18_fu_1091_p1;

assign k_buf_0_val_7_address0 = tmp_18_fu_1091_p1;

assign k_buf_0_val_8_address0 = tmp_18_fu_1091_p1;

assign k_buf_0_val_9_address0 = tmp_18_fu_1091_p1;

assign or_cond_i427_i_1_fu_756_p2 = (tmp_331_1_fu_751_p2 & rev8_fu_745_p2);

assign or_cond_i427_i_2_fu_802_p2 = (tmp_331_2_fu_797_p2 & rev9_fu_791_p2);

assign or_cond_i427_i_3_fu_848_p2 = (tmp_331_3_fu_843_p2 & rev10_fu_837_p2);

assign or_cond_i427_i_4_fu_894_p2 = (tmp_331_4_fu_889_p2 & rev11_fu_883_p2);

assign or_cond_i427_i_fu_710_p2 = (tmp_11_fu_705_p2 & rev_fu_699_p2);

assign or_cond_i_fu_1104_p2 = (tmp_4_reg_2366 & icmp_fu_1021_p2);

assign or_cond_i_i_fu_1052_p2 = (tmp_16_fu_1047_p2 & rev12_fu_1041_p2);

assign p_Val2_19_0_2_cast_fu_1497_p1 = grp_fu_1941_p3;

assign p_Val2_19_1_1_cast_fu_1721_p1 = $signed(p_Val2_19_1_1_reg_2531);

assign p_Val2_19_1_1_fu_1543_p2 = ($signed(tmp6_fu_1531_p2) + $signed(tmp7_cast_fu_1540_p1));

assign p_Val2_19_2_2_fu_1758_p2 = ($signed(tmp11_cast_fu_1749_p1) + $signed(tmp12_cast_fu_1752_p1));

assign p_Val2_6_fu_1837_p2 = ($signed(tmp25_fu_1828_p2) + $signed(tmp49_cast_fu_1834_p1));

assign p_Val2_7_i_i_fu_1910_p3 = ((underflow_fu_1889_p2[0:0] === 1'b1) ? 15'd16384 : p_Val2_6_reg_2555);

assign p_Val2_9_fu_1903_p3 = ((brmerge_i_i_i_i_fu_1894_p2[0:0] === 1'b1) ? 15'd16383 : p_Val2_6_reg_2555);

assign p_Val2_s_fu_1802_p2 = ($signed(tmp17_fu_1793_p2) + $signed(tmp38_cast_fu_1799_p1));

assign p_assign_1_fu_1066_p3 = ((tmp_92_fu_1058_p3[0:0] === 1'b1) ? 32'd0 : tmp_2_reg_2228);

assign p_assign_8_1_fu_731_p2 = ($signed(32'd4294967294) + $signed(t_V_reg_508));

assign p_assign_8_2_fu_777_p2 = ($signed(32'd4294967293) + $signed(t_V_reg_508));

assign p_assign_8_3_fu_823_p2 = ($signed(32'd4294967292) + $signed(t_V_reg_508));

assign p_assign_8_4_fu_869_p2 = ($signed(32'd4294967291) + $signed(t_V_reg_508));

assign p_assign_9_1_fu_770_p3 = ((tmp_78_fu_762_p3[0:0] === 1'b1) ? 32'd0 : p_neg397_i_reg_2234);

assign p_assign_9_2_fu_816_p3 = ((tmp_80_fu_808_p3[0:0] === 1'b1) ? 32'd0 : p_neg397_i_reg_2234);

assign p_assign_9_3_fu_862_p3 = ((tmp_82_fu_854_p3[0:0] === 1'b1) ? 32'd0 : p_neg397_i_reg_2234);

assign p_assign_9_4_fu_908_p3 = ((tmp_84_fu_900_p3[0:0] === 1'b1) ? 32'd0 : p_neg397_i_reg_2234);

assign p_assign_9_fu_724_p3 = ((tmp_76_fu_716_p3[0:0] === 1'b1) ? 32'd0 : p_neg397_i_reg_2234);

assign p_dst_data_stream_V_V_din = ((underflow_not_i_i_fu_1898_p2[0:0] === 1'b1) ? p_Val2_9_fu_1903_p3 : p_Val2_7_i_i_fu_1910_p3);

assign p_neg397_i_fu_548_p2 = ($signed(p_src_rows_V_read) + $signed(32'd4294967295));

assign p_shl_cast_fu_1517_p1 = p_shl_fu_1510_p3;

assign p_shl_fu_1510_p3 = {{src_kernel_win_0_va_38_reg_2511}, {3'd0}};

assign r_V_8_1_1_fu_1521_p2 = (12'd0 - p_shl_cast_fu_1517_p1);

assign r_V_8_1_3_fu_1398_p0 = OP2_V_1_3_cast_reg_2278;

assign r_V_8_1_3_fu_1398_p1 = r_V_8_1_3_fu_1398_p10;

assign r_V_8_1_3_fu_1398_p10 = src_kernel_win_0_va_12_fu_202;

assign r_V_8_1_3_fu_1398_p2 = ($signed(r_V_8_1_3_fu_1398_p0) * $signed({{1'b0}, {r_V_8_1_3_fu_1398_p1}}));

assign r_V_8_1_4_fu_1736_p0 = OP2_V_1_4_cast_reg_2283;

assign r_V_8_1_4_fu_1736_p1 = r_V_8_1_4_fu_1736_p10;

assign r_V_8_1_4_fu_1736_p10 = src_kernel_win_0_va_23_reg_2500_pp0_iter2_reg;

assign r_V_8_1_fu_1385_p0 = OP2_V_1_cast_reg_2268;

assign r_V_8_1_fu_1385_p1 = r_V_8_1_fu_1385_p10;

assign r_V_8_1_fu_1385_p10 = src_kernel_win_0_va_15_fu_214;

assign r_V_8_1_fu_1385_p2 = ($signed(r_V_8_1_fu_1385_p0) * $signed({{1'b0}, {r_V_8_1_fu_1385_p1}}));

assign r_V_8_2_3_fu_1768_p0 = OP2_V_2_3_cast_reg_2298;

assign r_V_8_2_3_fu_1768_p1 = r_V_8_2_3_fu_1768_p10;

assign r_V_8_2_3_fu_1768_p10 = src_kernel_win_0_va_8_fu_186;

assign r_V_8_3_2_fu_1560_p0 = OP2_V_3_2_cast_reg_2318;

assign r_V_8_3_2_fu_1560_p1 = r_V_8_3_2_fu_1560_p10;

assign r_V_8_3_2_fu_1560_p10 = src_kernel_win_0_va_5_fu_174;

assign r_V_8_3_3_fu_1565_p3 = {{src_kernel_win_0_va_4_fu_170}, {3'd0}};

assign r_V_8_4_2_fu_1592_p0 = OP2_V_4_2_cast_reg_2338;

assign r_V_8_4_2_fu_1592_p1 = r_V_8_4_2_fu_1592_p10;

assign r_V_8_4_2_fu_1592_p10 = src_kernel_win_0_va_1_fu_158;

assign r_V_8_fu_1476_p2 = (9'd0 - OP1_V_0_cast_fu_1472_p1);

assign rev10_fu_837_p2 = (tmp_81_fu_829_p3 ^ 1'd1);

assign rev11_fu_883_p2 = (tmp_83_fu_875_p3 ^ 1'd1);

assign rev12_fu_1041_p2 = (tmp_91_fu_1033_p3 ^ 1'd1);

assign rev8_fu_745_p2 = (tmp_77_fu_737_p3 ^ 1'd1);

assign rev9_fu_791_p2 = (tmp_79_fu_783_p3 ^ 1'd1);

assign rev_fu_699_p2 = (tmp_75_fu_691_p3 ^ 1'd1);

assign row_assign_14_1_fu_940_p2 = (p_neg397_i_reg_2234 - y_2_1_fu_932_p3);

assign row_assign_14_2_fu_957_p2 = (p_neg397_i_reg_2234 - y_2_2_fu_949_p3);

assign row_assign_14_3_fu_974_p2 = (p_neg397_i_reg_2234 - y_2_3_fu_966_p3);

assign row_assign_14_4_fu_991_p2 = (p_neg397_i_reg_2234 - y_2_4_fu_983_p3);

assign row_assign_s_fu_923_p2 = (p_neg397_i_reg_2234 - y_2_fu_915_p3);

assign src_kernel_win_0_va_20_fu_1274_p3 = ((tmp_8_reg_2383[0:0] === 1'b1) ? tmp_55_fu_1259_p7 : col_buf_0_val_0_0_fu_1139_p3);

assign src_kernel_win_0_va_21_fu_1296_p3 = ((tmp_8_reg_2383[0:0] === 1'b1) ? tmp_56_fu_1281_p7 : col_buf_0_val_1_0_fu_1161_p3);

assign src_kernel_win_0_va_22_fu_1318_p3 = ((tmp_8_reg_2383[0:0] === 1'b1) ? tmp_57_fu_1303_p7 : col_buf_0_val_2_0_fu_1183_p3);

assign src_kernel_win_0_va_23_fu_1340_p3 = ((tmp_8_reg_2383[0:0] === 1'b1) ? tmp_58_fu_1325_p7 : col_buf_0_val_3_0_fu_1205_p3);

assign src_kernel_win_0_va_24_fu_1362_p3 = ((tmp_8_reg_2383[0:0] === 1'b1) ? tmp_59_fu_1347_p7 : col_buf_0_val_4_0_fu_1227_p3);

assign tmp11_cast_fu_1749_p1 = grp_fu_2020_p3;

assign tmp12_cast_fu_1752_p1 = grp_fu_2011_p3;

assign tmp14_fu_1784_p2 = ($signed(p_Val2_19_2_2_fu_1758_p2) + $signed(tmp35_cast_fu_1781_p1));

assign tmp17_fu_1793_p2 = ($signed(tmp14_fu_1784_p2) + $signed(tmp36_cast_fu_1790_p1));

assign tmp22_fu_1613_p2 = ($signed(grp_fu_1972_p3) + $signed(tmp43_cast_fu_1610_p1));

assign tmp23_fu_1622_p2 = ($signed(tmp39_cast_fu_1607_p1) + $signed(tmp41_cast_fu_1618_p1));

assign tmp24_fu_1819_p2 = ($signed(tmp_61_fu_1773_p2) + $signed(tmp46_cast_fu_1816_p1));

assign tmp25_fu_1828_p2 = ($signed(tmp24_fu_1819_p2) + $signed(tmp47_cast_fu_1825_p1));

assign tmp35_cast_fu_1781_p1 = grp_fu_2029_p3;

assign tmp36_cast_fu_1790_p1 = tmp16_reg_2536;

assign tmp38_cast_fu_1799_p1 = tmp23_reg_2542;

assign tmp39_cast_fu_1607_p1 = grp_fu_1980_p3;

assign tmp41_cast_fu_1618_p1 = $signed(tmp22_fu_1613_p2);

assign tmp43_cast_fu_1610_p1 = grp_fu_1987_p3;

assign tmp46_cast_fu_1816_p1 = grp_fu_2029_p3;

assign tmp47_cast_fu_1825_p1 = tmp16_reg_2536;

assign tmp49_cast_fu_1834_p1 = tmp23_reg_2542;

assign tmp6_fu_1531_p2 = ($signed(tmp_350_1_1_cast_cas_fu_1527_p1) + $signed(p_Val2_19_0_2_cast_fu_1497_p1));

assign tmp7_cast_fu_1540_p1 = grp_fu_1949_p3;

assign tmp9_cast_fu_1724_p1 = tmp9_reg_2521_pp0_iter2_reg;

assign tmp_11_fu_705_p2 = (($signed(tmp_9_fu_685_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_16_fu_1047_p2 = (($signed(ImagLoc_x_fu_1027_p2) < $signed(p_src_cols_V_read)) ? 1'b1 : 1'b0);

assign tmp_18_fu_1091_p1 = x_fu_1073_p3;

assign tmp_1_fu_536_p2 = (p_src_rows_V_read + 32'd3);

assign tmp_26_fu_1884_p2 = (newsignbit_reg_2561 ^ 1'd1);

assign tmp_274_not_fu_650_p2 = (tmp_3_fu_645_p2 ^ 1'd1);

assign tmp_2_fu_542_p2 = ($signed(p_src_cols_V_read) + $signed(32'd4294967295));

assign tmp_2_i_i_fu_1879_p2 = (isneg_reg_2548 ^ 1'd1);

assign tmp_304_3_fu_668_p2 = ((t_V_reg_508 == 32'd1) ? 1'b1 : 1'b0);

assign tmp_304_4_fu_674_p2 = ((t_V_reg_508 == 32'd2) ? 1'b1 : 1'b0);

assign tmp_331_1_fu_751_p2 = (($signed(p_assign_8_1_fu_731_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_331_2_fu_797_p2 = (($signed(p_assign_8_2_fu_777_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_331_3_fu_843_p2 = (($signed(p_assign_8_3_fu_823_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_331_4_fu_889_p2 = (($signed(p_assign_8_4_fu_869_p2) < $signed(p_src_rows_V_read)) ? 1'b1 : 1'b0);

assign tmp_350_1_1_cast_cas_fu_1527_p1 = $signed(r_V_8_1_1_fu_1521_p2);

assign tmp_3_fu_645_p2 = ((t_V_reg_508 < p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_4_fu_656_p2 = ((t_V_reg_508 > 32'd2) ? 1'b1 : 1'b0);

assign tmp_60_fu_1755_p1 = grp_fu_2011_p3;

assign tmp_61_fu_1773_p2 = ($signed(tmp_60_fu_1755_p1) + $signed(grp_fu_2020_p3));

assign tmp_75_fu_691_p3 = tmp_9_fu_685_p2[32'd31];

assign tmp_76_fu_716_p3 = tmp_9_fu_685_p2[32'd31];

assign tmp_77_fu_737_p3 = p_assign_8_1_fu_731_p2[32'd31];

assign tmp_78_fu_762_p3 = p_assign_8_1_fu_731_p2[32'd31];

assign tmp_79_fu_783_p3 = p_assign_8_2_fu_777_p2[32'd31];

assign tmp_7_fu_662_p2 = ((t_V_reg_508 == 32'd0) ? 1'b1 : 1'b0);

assign tmp_80_fu_808_p3 = p_assign_8_2_fu_777_p2[32'd31];

assign tmp_81_fu_829_p3 = p_assign_8_3_fu_823_p2[32'd31];

assign tmp_82_fu_854_p3 = p_assign_8_3_fu_823_p2[32'd31];

assign tmp_83_fu_875_p3 = p_assign_8_4_fu_869_p2[32'd31];

assign tmp_84_fu_900_p3 = p_assign_8_4_fu_869_p2[32'd31];

assign tmp_85_fu_928_p1 = row_assign_s_fu_923_p2[2:0];

assign tmp_86_fu_945_p1 = row_assign_14_1_fu_940_p2[2:0];

assign tmp_87_fu_962_p1 = row_assign_14_2_fu_957_p2[2:0];

assign tmp_88_fu_979_p1 = row_assign_14_3_fu_974_p2[2:0];

assign tmp_89_fu_996_p1 = row_assign_14_4_fu_991_p2[2:0];

assign tmp_8_fu_680_p2 = ((t_V_reg_508 > p_src_rows_V_read) ? 1'b1 : 1'b0);

assign tmp_90_fu_1011_p4 = {{t_V_7_reg_519[31:2]}};

assign tmp_91_fu_1033_p3 = ImagLoc_x_fu_1027_p2[32'd31];

assign tmp_92_fu_1058_p3 = ImagLoc_x_fu_1027_p2[32'd31];

assign tmp_93_fu_1100_p1 = col_assign_2_fu_1081_p2[2:0];

assign tmp_9_fu_685_p2 = ($signed(32'd4294967295) + $signed(t_V_reg_508));

assign tmp_s_fu_530_p2 = (p_src_cols_V_read + 32'd4);

assign underflow_fu_1889_p2 = (tmp_26_fu_1884_p2 & isneg_reg_2548);

assign underflow_not_i_i_fu_1898_p2 = (tmp_2_i_i_fu_1879_p2 | newsignbit_reg_2561);

assign x_fu_1073_p3 = ((or_cond_i_i_fu_1052_p2[0:0] === 1'b1) ? ImagLoc_x_fu_1027_p2 : p_assign_1_fu_1066_p3);

assign y_2_1_fu_932_p3 = ((or_cond_i427_i_1_fu_756_p2[0:0] === 1'b1) ? p_assign_8_1_fu_731_p2 : p_assign_9_1_fu_770_p3);

assign y_2_2_fu_949_p3 = ((or_cond_i427_i_2_fu_802_p2[0:0] === 1'b1) ? p_assign_8_2_fu_777_p2 : p_assign_9_2_fu_816_p3);

assign y_2_3_fu_966_p3 = ((or_cond_i427_i_3_fu_848_p2[0:0] === 1'b1) ? p_assign_8_3_fu_823_p2 : p_assign_9_3_fu_862_p3);

assign y_2_4_fu_983_p3 = ((or_cond_i427_i_4_fu_894_p2[0:0] === 1'b1) ? p_assign_8_4_fu_869_p2 : p_assign_9_4_fu_908_p3);

assign y_2_fu_915_p3 = ((or_cond_i427_i_fu_710_p2[0:0] === 1'b1) ? tmp_9_fu_685_p2 : p_assign_9_fu_724_p3);

always @ (posedge ap_clk) begin
    OP2_V_2_3_cast_reg_2298[13:6] <= 8'b00000000;
    OP2_V_2_4_cast_reg_2303[12:5] <= 8'b00000000;
    OP2_V_3_2_cast_reg_2318[12:5] <= 8'b00000000;
    OP2_V_3_4_cast_reg_2323[11:4] <= 8'b00000000;
    OP2_V_4_2_cast_reg_2338[11:4] <= 8'b00000000;
    OP2_V_4_3_cast_reg_2343[11:4] <= 8'b00000000;
end

endmodule //Filter2D
