// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "row_filter.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic row_filter::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic row_filter::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> row_filter::ap_ST_fsm_state1 = "1";
const sc_lv<4> row_filter::ap_ST_fsm_state2 = "10";
const sc_lv<4> row_filter::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> row_filter::ap_ST_fsm_state9 = "1000";
const sc_lv<32> row_filter::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool row_filter::ap_const_boolean_1 = true;
const sc_lv<32> row_filter::ap_const_lv32_2 = "10";
const bool row_filter::ap_const_boolean_0 = false;
const sc_lv<1> row_filter::ap_const_lv1_1 = "1";
const sc_lv<32> row_filter::ap_const_lv32_1 = "1";
const sc_lv<1> row_filter::ap_const_lv1_0 = "0";
const sc_lv<32> row_filter::ap_const_lv32_3 = "11";
const sc_lv<64> row_filter::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> row_filter::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<32> row_filter::ap_const_lv32_7 = "111";
const sc_lv<32> row_filter::ap_const_lv32_FFFFFFFC = "11111111111111111111111111111100";
const sc_lv<32> row_filter::ap_const_lv32_6 = "110";
const sc_lv<32> row_filter::ap_const_lv32_1F = "11111";
const sc_lv<32> row_filter::ap_const_lv32_2A = "101010";
const sc_lv<32> row_filter::ap_const_lv32_22 = "100010";
const sc_lv<32> row_filter::ap_const_lv32_23 = "100011";
const sc_lv<8> row_filter::ap_const_lv8_0 = "00000000";
const sc_lv<8> row_filter::ap_const_lv8_FF = "11111111";
const sc_lv<35> row_filter::ap_const_lv35_3FFFFFFFF = "1111111111111111111111111111111111";
const sc_lv<35> row_filter::ap_const_lv35_400000000 = "10000000000000000000000000000000000";

row_filter::row_filter(sc_module_name name) : sc_module(name), mVcdFile(0) {
    l_border_buf_0_val_s_U = new row_filter_l_bordGfk("l_border_buf_0_val_s_U");
    l_border_buf_0_val_s_U->clk(ap_clk);
    l_border_buf_0_val_s_U->reset(ap_rst);
    l_border_buf_0_val_s_U->address0(l_border_buf_0_val_s_address0);
    l_border_buf_0_val_s_U->ce0(l_border_buf_0_val_s_ce0);
    l_border_buf_0_val_s_U->we0(l_border_buf_0_val_s_we0);
    l_border_buf_0_val_s_U->d0(row_buf_0_val_0_V_s_fu_94);
    l_border_buf_0_val_s_U->address1(l_border_buf_0_val_s_address1);
    l_border_buf_0_val_s_U->ce1(l_border_buf_0_val_s_ce1);
    l_border_buf_0_val_s_U->q1(l_border_buf_0_val_s_q1);
    r_border_buf_0_val_s_U = new row_filter_l_bordGfk("r_border_buf_0_val_s_U");
    r_border_buf_0_val_s_U->clk(ap_clk);
    r_border_buf_0_val_s_U->reset(ap_rst);
    r_border_buf_0_val_s_U->address0(r_border_buf_0_val_s_address0);
    r_border_buf_0_val_s_U->ce0(r_border_buf_0_val_s_ce0);
    r_border_buf_0_val_s_U->we0(r_border_buf_0_val_s_we0);
    r_border_buf_0_val_s_U->d0(row_buf_0_val_0_V_s_fu_94);
    r_border_buf_0_val_s_U->address1(r_border_buf_0_val_s_address1);
    r_border_buf_0_val_s_U->ce1(r_border_buf_0_val_s_ce1);
    r_border_buf_0_val_s_U->q1(r_border_buf_0_val_s_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_OP1_V_1_0_0_1_i_fu_539_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_4_fu_114 );

    SC_METHOD(thread_OP1_V_1_0_0_1_i_fu_539_p1);
    sensitive << ( OP1_V_1_0_0_1_i_fu_539_p0 );

    SC_METHOD(thread_OP1_V_1_0_0_i_fu_535_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_5_fu_118 );

    SC_METHOD(thread_OP1_V_1_0_0_i_fu_535_p1);
    sensitive << ( OP1_V_1_0_0_i_fu_535_p0 );

    SC_METHOD(thread_addconv_i_fu_549_p2);
    sensitive << ( OP1_V_1_0_0_i_fu_535_p1 );
    sensitive << ( OP1_V_1_0_0_1_i_fu_539_p1 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_V_V_empty_n );
    sensitive << ( p_dst_data_stream_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_i_reg_979 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_V_V_empty_n );
    sensitive << ( p_dst_data_stream_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_i_reg_979 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_V_V_empty_n );
    sensitive << ( p_dst_data_stream_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_i_reg_979 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( p_anchor_x_empty_n );
    sensitive << ( rows_empty_n );
    sensitive << ( cols_empty_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_V_V_empty_n );
    sensitive << ( tmp_4_i_reg_979 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter5);
    sensitive << ( p_dst_data_stream_V_V_full_n );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( exitcond2_i_fu_291_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( exitcond1_i_fu_280_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond1_i_fu_280_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_brmerge39_i_i_i_i_fu_733_p2);
    sensitive << ( p_not38_i_i_i_i_fu_727_p2 );
    sensitive << ( newsignbit_0_not_i_i_fu_721_p2 );

    SC_METHOD(thread_brmerge_i_i_i_fu_757_p2);
    sensitive << ( overflow_fu_715_p2 );
    sensitive << ( underflow_not_i_i_i_fu_751_p2 );

    SC_METHOD(thread_brmerge_i_i_i_i_fu_703_p2);
    sensitive << ( newsignbit_fu_679_p3 );
    sensitive << ( p_not_i_i_i_i_fu_697_p2 );

    SC_METHOD(thread_brmerge_i_i_i_i_i_fu_745_p2);
    sensitive << ( underflow_fu_739_p2 );
    sensitive << ( overflow_fu_715_p2 );

    SC_METHOD(thread_col_assign_2_i_fu_486_p2);
    sensitive << ( right_border_reg_933 );
    sensitive << ( x_i_reg_1011_pp0_iter2_reg );

    SC_METHOD(thread_col_assign_fu_335_p2);
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( right_border_reg_933 );

    SC_METHOD(thread_cols_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( cols_empty_n );

    SC_METHOD(thread_cols_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_anchor_x_empty_n );
    sensitive << ( rows_empty_n );
    sensitive << ( cols_empty_n );

    SC_METHOD(thread_exitcond1_i_fu_280_p2);
    sensitive << ( heightloop_reg_909 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( t_V_reg_224 );

    SC_METHOD(thread_exitcond2_i_fu_291_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( tmp_1_i_reg_946 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_i_V_fu_285_p2);
    sensitive << ( t_V_reg_224 );

    SC_METHOD(thread_index_cast_i1_cast_fu_246_p3);
    sensitive << ( p_anchor_x_dout );

    SC_METHOD(thread_isneg_fu_653_p3);
    sensitive << ( p_Val2_11_0_0_6_i_fu_647_p2 );

    SC_METHOD(thread_j_V_fu_296_p2);
    sensitive << ( t_V_1_reg_235 );

    SC_METHOD(thread_l_border_buf_0_val_s_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_l_border_buf_0_val_s_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_50_i_fu_482_p1 );

    SC_METHOD(thread_l_border_buf_0_val_s_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_l_border_buf_0_val_s_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_l_border_buf_0_val_s_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_5_i_reg_983_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_newsignbit_0_not_i_i_fu_721_p2);
    sensitive << ( newsignbit_fu_679_p3 );

    SC_METHOD(thread_newsignbit_fu_679_p3);
    sensitive << ( p_Val2_11_0_0_6_i_fu_647_p2 );

    SC_METHOD(thread_or_cond1_i_fu_345_p2);
    sensitive << ( tmp_5_i_fu_312_p2 );
    sensitive << ( tmp_7_i_fu_340_p2 );

    SC_METHOD(thread_or_cond_i_fu_329_p2);
    sensitive << ( tmp_4_i_fu_307_p2 );
    sensitive << ( rev_fu_323_p2 );

    SC_METHOD(thread_or_cond_i_i_fu_381_p2);
    sensitive << ( tmp_38_i_fu_376_p2 );
    sensitive << ( rev1_fu_370_p2 );

    SC_METHOD(thread_overflow_fu_715_p2);
    sensitive << ( brmerge_i_i_i_i_fu_703_p2 );
    sensitive << ( tmp_1_i_i_i_fu_709_p2 );

    SC_METHOD(thread_p_Val2_11_0_0_1_ca_fu_555_p1);
    sensitive << ( addconv_i_fu_549_p2 );

    SC_METHOD(thread_p_Val2_11_0_0_3_ca_fu_597_p1);
    sensitive << ( p_Val2_11_0_0_3_i_fu_591_p2 );

    SC_METHOD(thread_p_Val2_11_0_0_3_i_fu_591_p2);
    sensitive << ( tmp_cast_fu_579_p1 );
    sensitive << ( p_Val2_11_0_0_1_ca_fu_555_p1 );

    SC_METHOD(thread_p_Val2_11_0_0_6_i_fu_647_p2);
    sensitive << ( tmp112_cast_fu_643_p1 );
    sensitive << ( tmp7_fu_631_p2 );

    SC_METHOD(thread_p_Val2_2_fu_763_p3);
    sensitive << ( brmerge_i_i_i_i_i_fu_745_p2 );
    sensitive << ( p_Val2_s_fu_673_p2 );

    SC_METHOD(thread_p_Val2_4_i_i_i_fu_771_p3);
    sensitive << ( underflow_fu_739_p2 );
    sensitive << ( p_Val2_s_fu_673_p2 );

    SC_METHOD(thread_p_Val2_s_fu_673_p2);
    sensitive << ( tmp10_fu_667_p2 );
    sensitive << ( tmp9_fu_661_p2 );

    SC_METHOD(thread_p_anchor_x_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_anchor_x_empty_n );

    SC_METHOD(thread_p_anchor_x_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_anchor_x_empty_n );
    sensitive << ( rows_empty_n );
    sensitive << ( cols_empty_n );

    SC_METHOD(thread_p_assign_1_i_fu_395_p3);
    sensitive << ( right_border_reg_933 );
    sensitive << ( tmp_2_fu_387_p3 );

    SC_METHOD(thread_p_assign_fu_302_p2);
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( tmp_2_cast_i_cast_reg_951 );

    SC_METHOD(thread_p_dst_data_stream_V_V_blk_n);
    sensitive << ( p_dst_data_stream_V_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );

    SC_METHOD(thread_p_dst_data_stream_V_V_din);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );
    sensitive << ( tmp_V_1_reg_1032 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_p_dst_data_stream_V_V_write);
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter4_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_not38_i_i_i_i_fu_727_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_s_fu_687_p4 );

    SC_METHOD(thread_p_not_i_i_i_i_fu_697_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( tmp_9_i_reg_1007_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( tmp_s_fu_687_p4 );

    SC_METHOD(thread_p_src_V_V_blk_n);
    sensitive << ( p_src_V_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_4_i_reg_979 );

    SC_METHOD(thread_p_src_V_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_4_i_reg_979 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_r_border_buf_0_val_s_address0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( tmp_45_i_fu_423_p1 );

    SC_METHOD(thread_r_border_buf_0_val_s_address1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( tmp_51_i_fu_490_p1 );

    SC_METHOD(thread_r_border_buf_0_val_s_ce0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_r_border_buf_0_val_s_ce1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_r_border_buf_0_val_s_we0);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( or_cond_i_reg_987_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_rev1_fu_370_p2);
    sensitive << ( tmp_1_fu_362_p3 );

    SC_METHOD(thread_rev_fu_323_p2);
    sensitive << ( ult_fu_318_p2 );

    SC_METHOD(thread_right_border_fu_254_p2);
    sensitive << ( cols_dout );

    SC_METHOD(thread_row_buf_0_val_0_V_10_fu_446_p3);
    sensitive << ( index_reg_920 );
    sensitive << ( row_buf_0_val_0_V_3_fu_130 );
    sensitive << ( row_buf_0_val_0_V_4_fu_134 );

    SC_METHOD(thread_row_buf_0_val_0_V_11_fu_453_p3);
    sensitive << ( index_reg_920 );
    sensitive << ( row_buf_0_val_0_V_s_fu_94 );
    sensitive << ( row_buf_0_val_0_V_4_fu_134 );

    SC_METHOD(thread_row_buf_0_val_0_V_12_fu_460_p3);
    sensitive << ( index_reg_920 );
    sensitive << ( row_buf_0_val_0_V_s_fu_94 );
    sensitive << ( row_buf_0_val_0_V_2_fu_126 );

    SC_METHOD(thread_row_buf_val_V_0_0_2_1_fu_439_p3);
    sensitive << ( index_reg_920 );
    sensitive << ( row_buf_0_val_0_V_2_fu_126 );
    sensitive << ( row_buf_0_val_0_V_3_fu_130 );

    SC_METHOD(thread_rows_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( rows_empty_n );

    SC_METHOD(thread_rows_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_anchor_x_empty_n );
    sensitive << ( rows_empty_n );
    sensitive << ( cols_empty_n );

    SC_METHOD(thread_sel_tmp3_fu_498_p3);
    sensitive << ( or_cond1_i_reg_996_pp0_iter3_reg );
    sensitive << ( l_border_buf_0_val_s_q1 );
    sensitive << ( row_buf_0_val_0_V_1_fu_122 );

    SC_METHOD(thread_sel_tmp4_fu_505_p2);
    sensitive << ( or_cond1_i_reg_996_pp0_iter3_reg );
    sensitive << ( tmp_8_i_reg_1002_pp0_iter3_reg );

    SC_METHOD(thread_src_kernel_winX_temp_11_fu_509_p3);
    sensitive << ( r_border_buf_0_val_s_q1 );
    sensitive << ( sel_tmp4_fu_505_p2 );
    sensitive << ( sel_tmp3_fu_498_p3 );

    SC_METHOD(thread_stop_fu_260_p2);
    sensitive << ( cols_dout );
    sensitive << ( index_cast_i1_cast_fu_246_p3 );

    SC_METHOD(thread_tmp10_fu_667_p2);
    sensitive << ( tmp_6_fu_605_p1 );
    sensitive << ( tmp_10_fu_627_p1 );

    SC_METHOD(thread_tmp112_cast_fu_643_p1);
    sensitive << ( tmp8_fu_637_p2 );

    SC_METHOD(thread_tmp7_fu_631_p2);
    sensitive << ( p_Val2_11_0_0_3_ca_fu_597_p1 );
    sensitive << ( tmp_73_0_0_4_cast_i_fu_601_p1 );

    SC_METHOD(thread_tmp8_fu_637_p2);
    sensitive << ( tmp_73_0_0_5_cast_i_s_fu_615_p1 );
    sensitive << ( tmp_73_0_0_6_cast_i_s_fu_623_p1 );

    SC_METHOD(thread_tmp9_fu_661_p2);
    sensitive << ( tmp_4_fu_609_p2 );
    sensitive << ( tmp_9_fu_619_p1 );

    SC_METHOD(thread_tmp_10_fu_627_p1);
    sensitive << ( src_kernel_winX_temp_11_fu_509_p3 );

    SC_METHOD(thread_tmp_1_fu_362_p3);
    sensitive << ( p_assign_fu_302_p2 );

    SC_METHOD(thread_tmp_1_i_fu_266_p2);
    sensitive << ( cols_dout );

    SC_METHOD(thread_tmp_1_i_i_i_fu_709_p2);
    sensitive << ( isneg_fu_653_p3 );

    SC_METHOD(thread_tmp_2_cast_i_cast_fu_272_p3);
    sensitive << ( p_anchor_x_dout );

    SC_METHOD(thread_tmp_2_fu_387_p3);
    sensitive << ( p_assign_fu_302_p2 );

    SC_METHOD(thread_tmp_38_i_fu_376_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( cols_read_reg_914 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( p_assign_fu_302_p2 );

    SC_METHOD(thread_tmp_3_fu_583_p1);
    sensitive << ( tmp_7_fu_543_p2 );

    SC_METHOD(thread_tmp_45_i_fu_423_p1);
    sensitive << ( col_assign_reg_991_pp0_iter1_reg );

    SC_METHOD(thread_tmp_4_fu_609_p2);
    sensitive << ( tmp_3_fu_583_p1 );
    sensitive << ( tmp_5_fu_587_p1 );

    SC_METHOD(thread_tmp_4_i_fu_307_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( cols_read_reg_914 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_50_i_fu_482_p1);
    sensitive << ( x_i_reg_1011_pp0_iter2_reg );

    SC_METHOD(thread_tmp_51_i_fu_490_p1);
    sensitive << ( col_assign_2_i_fu_486_p2 );

    SC_METHOD(thread_tmp_5_fu_587_p1);
    sensitive << ( tmp_8_fu_567_p2 );

    SC_METHOD(thread_tmp_5_i_fu_312_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_6_fu_605_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_1_fu_102 );

    SC_METHOD(thread_tmp_6_fu_605_p1);
    sensitive << ( tmp_6_fu_605_p0 );

    SC_METHOD(thread_tmp_73_0_0_2_cast_i_s_fu_559_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_3_fu_110 );

    SC_METHOD(thread_tmp_73_0_0_2_cast_i_s_fu_559_p1);
    sensitive << ( tmp_73_0_0_2_cast_i_s_fu_559_p0 );

    SC_METHOD(thread_tmp_73_0_0_3_cast_i_s_fu_563_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_2_fu_106 );

    SC_METHOD(thread_tmp_73_0_0_3_cast_i_s_fu_563_p1);
    sensitive << ( tmp_73_0_0_3_cast_i_s_fu_563_p0 );

    SC_METHOD(thread_tmp_73_0_0_4_cast_i_fu_601_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_1_fu_102 );

    SC_METHOD(thread_tmp_73_0_0_4_cast_i_fu_601_p1);
    sensitive << ( tmp_73_0_0_4_cast_i_fu_601_p0 );

    SC_METHOD(thread_tmp_73_0_0_5_cast_i_s_fu_615_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_fu_98 );

    SC_METHOD(thread_tmp_73_0_0_5_cast_i_s_fu_615_p1);
    sensitive << ( tmp_73_0_0_5_cast_i_s_fu_615_p0 );

    SC_METHOD(thread_tmp_73_0_0_6_cast_i_s_fu_623_p1);
    sensitive << ( src_kernel_winX_temp_11_fu_509_p3 );

    SC_METHOD(thread_tmp_7_fu_543_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_4_fu_114 );

    SC_METHOD(thread_tmp_7_fu_543_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_5_fu_118 );

    SC_METHOD(thread_tmp_7_fu_543_p2);
    sensitive << ( tmp_7_fu_543_p0 );
    sensitive << ( tmp_7_fu_543_p1 );

    SC_METHOD(thread_tmp_7_i_fu_340_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( index_cast_i1_cast_reg_928 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_8_fu_567_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_2_fu_106 );

    SC_METHOD(thread_tmp_8_fu_567_p1);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_3_fu_110 );

    SC_METHOD(thread_tmp_8_fu_567_p2);
    sensitive << ( tmp_8_fu_567_p0 );
    sensitive << ( tmp_8_fu_567_p1 );

    SC_METHOD(thread_tmp_8_i_fu_351_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( stop_reg_941 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_9_fu_619_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( src_kernel_winX_temp_fu_98 );

    SC_METHOD(thread_tmp_9_fu_619_p1);
    sensitive << ( tmp_9_fu_619_p0 );

    SC_METHOD(thread_tmp_9_i_fu_356_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_tmp_V_1_fu_779_p3);
    sensitive << ( brmerge_i_i_i_fu_757_p2 );
    sensitive << ( p_Val2_2_fu_763_p3 );
    sensitive << ( p_Val2_4_i_i_i_fu_771_p3 );

    SC_METHOD(thread_tmp_cast_fu_579_p1);
    sensitive << ( tmp_fu_573_p2 );

    SC_METHOD(thread_tmp_fu_573_p2);
    sensitive << ( tmp_73_0_0_2_cast_i_s_fu_559_p1 );
    sensitive << ( tmp_73_0_0_3_cast_i_s_fu_563_p1 );

    SC_METHOD(thread_tmp_s_fu_687_p4);
    sensitive << ( p_Val2_11_0_0_6_i_fu_647_p2 );

    SC_METHOD(thread_ult_fu_318_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( t_V_1_reg_235 );
    sensitive << ( right_border_reg_933 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_underflow_fu_739_p2);
    sensitive << ( isneg_fu_653_p3 );
    sensitive << ( brmerge39_i_i_i_i_fu_733_p2 );

    SC_METHOD(thread_underflow_not_i_i_i_fu_751_p2);
    sensitive << ( underflow_fu_739_p2 );

    SC_METHOD(thread_x_i_fu_402_p3);
    sensitive << ( p_assign_fu_302_p2 );
    sensitive << ( or_cond_i_i_fu_381_p2 );
    sensitive << ( p_assign_1_i_fu_395_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_anchor_x_empty_n );
    sensitive << ( rows_empty_n );
    sensitive << ( cols_empty_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( exitcond1_i_fu_280_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond2_i_fu_291_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter4 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "row_filter_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_V_V_dout, "(port)p_src_V_V_dout");
    sc_trace(mVcdFile, p_src_V_V_empty_n, "(port)p_src_V_V_empty_n");
    sc_trace(mVcdFile, p_src_V_V_read, "(port)p_src_V_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_V_din, "(port)p_dst_data_stream_V_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_V_full_n, "(port)p_dst_data_stream_V_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_V_write, "(port)p_dst_data_stream_V_V_write");
    sc_trace(mVcdFile, p_anchor_x_dout, "(port)p_anchor_x_dout");
    sc_trace(mVcdFile, p_anchor_x_empty_n, "(port)p_anchor_x_empty_n");
    sc_trace(mVcdFile, p_anchor_x_read, "(port)p_anchor_x_read");
    sc_trace(mVcdFile, rows_dout, "(port)rows_dout");
    sc_trace(mVcdFile, rows_empty_n, "(port)rows_empty_n");
    sc_trace(mVcdFile, rows_read, "(port)rows_read");
    sc_trace(mVcdFile, cols_dout, "(port)cols_dout");
    sc_trace(mVcdFile, cols_empty_n, "(port)cols_empty_n");
    sc_trace(mVcdFile, cols_read, "(port)cols_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_V_V_blk_n, "p_src_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_4_i_reg_979, "tmp_4_i_reg_979");
    sc_trace(mVcdFile, p_dst_data_stream_V_V_blk_n, "p_dst_data_stream_V_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, tmp_9_i_reg_1007, "tmp_9_i_reg_1007");
    sc_trace(mVcdFile, tmp_9_i_reg_1007_pp0_iter4_reg, "tmp_9_i_reg_1007_pp0_iter4_reg");
    sc_trace(mVcdFile, p_anchor_x_blk_n, "p_anchor_x_blk_n");
    sc_trace(mVcdFile, rows_blk_n, "rows_blk_n");
    sc_trace(mVcdFile, cols_blk_n, "cols_blk_n");
    sc_trace(mVcdFile, t_V_1_reg_235, "t_V_1_reg_235");
    sc_trace(mVcdFile, heightloop_reg_909, "heightloop_reg_909");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, cols_read_reg_914, "cols_read_reg_914");
    sc_trace(mVcdFile, index_reg_920, "index_reg_920");
    sc_trace(mVcdFile, index_cast_i1_cast_fu_246_p3, "index_cast_i1_cast_fu_246_p3");
    sc_trace(mVcdFile, index_cast_i1_cast_reg_928, "index_cast_i1_cast_reg_928");
    sc_trace(mVcdFile, right_border_fu_254_p2, "right_border_fu_254_p2");
    sc_trace(mVcdFile, right_border_reg_933, "right_border_reg_933");
    sc_trace(mVcdFile, stop_fu_260_p2, "stop_fu_260_p2");
    sc_trace(mVcdFile, stop_reg_941, "stop_reg_941");
    sc_trace(mVcdFile, tmp_1_i_fu_266_p2, "tmp_1_i_fu_266_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_946, "tmp_1_i_reg_946");
    sc_trace(mVcdFile, tmp_2_cast_i_cast_fu_272_p3, "tmp_2_cast_i_cast_fu_272_p3");
    sc_trace(mVcdFile, tmp_2_cast_i_cast_reg_951, "tmp_2_cast_i_cast_reg_951");
    sc_trace(mVcdFile, exitcond1_i_fu_280_p2, "exitcond1_i_fu_280_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_V_fu_285_p2, "i_V_fu_285_p2");
    sc_trace(mVcdFile, i_V_reg_965, "i_V_reg_965");
    sc_trace(mVcdFile, exitcond2_i_fu_291_p2, "exitcond2_i_fu_291_p2");
    sc_trace(mVcdFile, exitcond2_i_reg_970, "exitcond2_i_reg_970");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter5, "ap_block_state8_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond2_i_reg_970_pp0_iter1_reg, "exitcond2_i_reg_970_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond2_i_reg_970_pp0_iter2_reg, "exitcond2_i_reg_970_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond2_i_reg_970_pp0_iter3_reg, "exitcond2_i_reg_970_pp0_iter3_reg");
    sc_trace(mVcdFile, j_V_fu_296_p2, "j_V_fu_296_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_4_i_fu_307_p2, "tmp_4_i_fu_307_p2");
    sc_trace(mVcdFile, tmp_5_i_fu_312_p2, "tmp_5_i_fu_312_p2");
    sc_trace(mVcdFile, tmp_5_i_reg_983, "tmp_5_i_reg_983");
    sc_trace(mVcdFile, tmp_5_i_reg_983_pp0_iter1_reg, "tmp_5_i_reg_983_pp0_iter1_reg");
    sc_trace(mVcdFile, or_cond_i_fu_329_p2, "or_cond_i_fu_329_p2");
    sc_trace(mVcdFile, or_cond_i_reg_987, "or_cond_i_reg_987");
    sc_trace(mVcdFile, or_cond_i_reg_987_pp0_iter1_reg, "or_cond_i_reg_987_pp0_iter1_reg");
    sc_trace(mVcdFile, col_assign_fu_335_p2, "col_assign_fu_335_p2");
    sc_trace(mVcdFile, col_assign_reg_991, "col_assign_reg_991");
    sc_trace(mVcdFile, col_assign_reg_991_pp0_iter1_reg, "col_assign_reg_991_pp0_iter1_reg");
    sc_trace(mVcdFile, or_cond1_i_fu_345_p2, "or_cond1_i_fu_345_p2");
    sc_trace(mVcdFile, or_cond1_i_reg_996, "or_cond1_i_reg_996");
    sc_trace(mVcdFile, or_cond1_i_reg_996_pp0_iter1_reg, "or_cond1_i_reg_996_pp0_iter1_reg");
    sc_trace(mVcdFile, or_cond1_i_reg_996_pp0_iter2_reg, "or_cond1_i_reg_996_pp0_iter2_reg");
    sc_trace(mVcdFile, or_cond1_i_reg_996_pp0_iter3_reg, "or_cond1_i_reg_996_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_8_i_fu_351_p2, "tmp_8_i_fu_351_p2");
    sc_trace(mVcdFile, tmp_8_i_reg_1002, "tmp_8_i_reg_1002");
    sc_trace(mVcdFile, tmp_8_i_reg_1002_pp0_iter1_reg, "tmp_8_i_reg_1002_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_8_i_reg_1002_pp0_iter2_reg, "tmp_8_i_reg_1002_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_8_i_reg_1002_pp0_iter3_reg, "tmp_8_i_reg_1002_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_9_i_fu_356_p2, "tmp_9_i_fu_356_p2");
    sc_trace(mVcdFile, tmp_9_i_reg_1007_pp0_iter1_reg, "tmp_9_i_reg_1007_pp0_iter1_reg");
    sc_trace(mVcdFile, tmp_9_i_reg_1007_pp0_iter2_reg, "tmp_9_i_reg_1007_pp0_iter2_reg");
    sc_trace(mVcdFile, tmp_9_i_reg_1007_pp0_iter3_reg, "tmp_9_i_reg_1007_pp0_iter3_reg");
    sc_trace(mVcdFile, x_i_fu_402_p3, "x_i_fu_402_p3");
    sc_trace(mVcdFile, x_i_reg_1011, "x_i_reg_1011");
    sc_trace(mVcdFile, x_i_reg_1011_pp0_iter1_reg, "x_i_reg_1011_pp0_iter1_reg");
    sc_trace(mVcdFile, x_i_reg_1011_pp0_iter2_reg, "x_i_reg_1011_pp0_iter2_reg");
    sc_trace(mVcdFile, row_buf_0_val_0_V_12_fu_460_p3, "row_buf_0_val_0_V_12_fu_460_p3");
    sc_trace(mVcdFile, row_buf_0_val_0_V_12_reg_1017, "row_buf_0_val_0_V_12_reg_1017");
    sc_trace(mVcdFile, row_buf_0_val_0_V_12_reg_1017_pp0_iter3_reg, "row_buf_0_val_0_V_12_reg_1017_pp0_iter3_reg");
    sc_trace(mVcdFile, tmp_V_1_fu_779_p3, "tmp_V_1_fu_779_p3");
    sc_trace(mVcdFile, tmp_V_1_reg_1032, "tmp_V_1_reg_1032");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, l_border_buf_0_val_s_address0, "l_border_buf_0_val_s_address0");
    sc_trace(mVcdFile, l_border_buf_0_val_s_ce0, "l_border_buf_0_val_s_ce0");
    sc_trace(mVcdFile, l_border_buf_0_val_s_we0, "l_border_buf_0_val_s_we0");
    sc_trace(mVcdFile, l_border_buf_0_val_s_address1, "l_border_buf_0_val_s_address1");
    sc_trace(mVcdFile, l_border_buf_0_val_s_ce1, "l_border_buf_0_val_s_ce1");
    sc_trace(mVcdFile, l_border_buf_0_val_s_q1, "l_border_buf_0_val_s_q1");
    sc_trace(mVcdFile, r_border_buf_0_val_s_address0, "r_border_buf_0_val_s_address0");
    sc_trace(mVcdFile, r_border_buf_0_val_s_ce0, "r_border_buf_0_val_s_ce0");
    sc_trace(mVcdFile, r_border_buf_0_val_s_we0, "r_border_buf_0_val_s_we0");
    sc_trace(mVcdFile, r_border_buf_0_val_s_address1, "r_border_buf_0_val_s_address1");
    sc_trace(mVcdFile, r_border_buf_0_val_s_ce1, "r_border_buf_0_val_s_ce1");
    sc_trace(mVcdFile, r_border_buf_0_val_s_q1, "r_border_buf_0_val_s_q1");
    sc_trace(mVcdFile, t_V_reg_224, "t_V_reg_224");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_45_i_fu_423_p1, "tmp_45_i_fu_423_p1");
    sc_trace(mVcdFile, tmp_50_i_fu_482_p1, "tmp_50_i_fu_482_p1");
    sc_trace(mVcdFile, tmp_51_i_fu_490_p1, "tmp_51_i_fu_490_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, row_buf_0_val_0_V_s_fu_94, "row_buf_0_val_0_V_s_fu_94");
    sc_trace(mVcdFile, src_kernel_winX_temp_fu_98, "src_kernel_winX_temp_fu_98");
    sc_trace(mVcdFile, src_kernel_winX_temp_11_fu_509_p3, "src_kernel_winX_temp_11_fu_509_p3");
    sc_trace(mVcdFile, src_kernel_winX_temp_1_fu_102, "src_kernel_winX_temp_1_fu_102");
    sc_trace(mVcdFile, src_kernel_winX_temp_2_fu_106, "src_kernel_winX_temp_2_fu_106");
    sc_trace(mVcdFile, src_kernel_winX_temp_3_fu_110, "src_kernel_winX_temp_3_fu_110");
    sc_trace(mVcdFile, src_kernel_winX_temp_4_fu_114, "src_kernel_winX_temp_4_fu_114");
    sc_trace(mVcdFile, src_kernel_winX_temp_5_fu_118, "src_kernel_winX_temp_5_fu_118");
    sc_trace(mVcdFile, row_buf_0_val_0_V_1_fu_122, "row_buf_0_val_0_V_1_fu_122");
    sc_trace(mVcdFile, row_buf_0_val_0_V_2_fu_126, "row_buf_0_val_0_V_2_fu_126");
    sc_trace(mVcdFile, row_buf_val_V_0_0_2_1_fu_439_p3, "row_buf_val_V_0_0_2_1_fu_439_p3");
    sc_trace(mVcdFile, row_buf_0_val_0_V_3_fu_130, "row_buf_0_val_0_V_3_fu_130");
    sc_trace(mVcdFile, row_buf_0_val_0_V_10_fu_446_p3, "row_buf_0_val_0_V_10_fu_446_p3");
    sc_trace(mVcdFile, row_buf_0_val_0_V_4_fu_134, "row_buf_0_val_0_V_4_fu_134");
    sc_trace(mVcdFile, row_buf_0_val_0_V_11_fu_453_p3, "row_buf_0_val_0_V_11_fu_453_p3");
    sc_trace(mVcdFile, ult_fu_318_p2, "ult_fu_318_p2");
    sc_trace(mVcdFile, rev_fu_323_p2, "rev_fu_323_p2");
    sc_trace(mVcdFile, tmp_7_i_fu_340_p2, "tmp_7_i_fu_340_p2");
    sc_trace(mVcdFile, p_assign_fu_302_p2, "p_assign_fu_302_p2");
    sc_trace(mVcdFile, tmp_1_fu_362_p3, "tmp_1_fu_362_p3");
    sc_trace(mVcdFile, tmp_38_i_fu_376_p2, "tmp_38_i_fu_376_p2");
    sc_trace(mVcdFile, rev1_fu_370_p2, "rev1_fu_370_p2");
    sc_trace(mVcdFile, tmp_2_fu_387_p3, "tmp_2_fu_387_p3");
    sc_trace(mVcdFile, or_cond_i_i_fu_381_p2, "or_cond_i_i_fu_381_p2");
    sc_trace(mVcdFile, p_assign_1_i_fu_395_p3, "p_assign_1_i_fu_395_p3");
    sc_trace(mVcdFile, col_assign_2_i_fu_486_p2, "col_assign_2_i_fu_486_p2");
    sc_trace(mVcdFile, sel_tmp4_fu_505_p2, "sel_tmp4_fu_505_p2");
    sc_trace(mVcdFile, sel_tmp3_fu_498_p3, "sel_tmp3_fu_498_p3");
    sc_trace(mVcdFile, OP1_V_1_0_0_i_fu_535_p0, "OP1_V_1_0_0_i_fu_535_p0");
    sc_trace(mVcdFile, OP1_V_1_0_0_1_i_fu_539_p0, "OP1_V_1_0_0_1_i_fu_539_p0");
    sc_trace(mVcdFile, tmp_7_fu_543_p0, "tmp_7_fu_543_p0");
    sc_trace(mVcdFile, tmp_7_fu_543_p1, "tmp_7_fu_543_p1");
    sc_trace(mVcdFile, OP1_V_1_0_0_i_fu_535_p1, "OP1_V_1_0_0_i_fu_535_p1");
    sc_trace(mVcdFile, OP1_V_1_0_0_1_i_fu_539_p1, "OP1_V_1_0_0_1_i_fu_539_p1");
    sc_trace(mVcdFile, addconv_i_fu_549_p2, "addconv_i_fu_549_p2");
    sc_trace(mVcdFile, tmp_73_0_0_2_cast_i_s_fu_559_p0, "tmp_73_0_0_2_cast_i_s_fu_559_p0");
    sc_trace(mVcdFile, tmp_73_0_0_3_cast_i_s_fu_563_p0, "tmp_73_0_0_3_cast_i_s_fu_563_p0");
    sc_trace(mVcdFile, tmp_8_fu_567_p0, "tmp_8_fu_567_p0");
    sc_trace(mVcdFile, tmp_8_fu_567_p1, "tmp_8_fu_567_p1");
    sc_trace(mVcdFile, tmp_73_0_0_2_cast_i_s_fu_559_p1, "tmp_73_0_0_2_cast_i_s_fu_559_p1");
    sc_trace(mVcdFile, tmp_73_0_0_3_cast_i_s_fu_563_p1, "tmp_73_0_0_3_cast_i_s_fu_563_p1");
    sc_trace(mVcdFile, tmp_fu_573_p2, "tmp_fu_573_p2");
    sc_trace(mVcdFile, tmp_7_fu_543_p2, "tmp_7_fu_543_p2");
    sc_trace(mVcdFile, tmp_8_fu_567_p2, "tmp_8_fu_567_p2");
    sc_trace(mVcdFile, tmp_cast_fu_579_p1, "tmp_cast_fu_579_p1");
    sc_trace(mVcdFile, p_Val2_11_0_0_1_ca_fu_555_p1, "p_Val2_11_0_0_1_ca_fu_555_p1");
    sc_trace(mVcdFile, p_Val2_11_0_0_3_i_fu_591_p2, "p_Val2_11_0_0_3_i_fu_591_p2");
    sc_trace(mVcdFile, tmp_73_0_0_4_cast_i_fu_601_p0, "tmp_73_0_0_4_cast_i_fu_601_p0");
    sc_trace(mVcdFile, tmp_6_fu_605_p0, "tmp_6_fu_605_p0");
    sc_trace(mVcdFile, tmp_3_fu_583_p1, "tmp_3_fu_583_p1");
    sc_trace(mVcdFile, tmp_5_fu_587_p1, "tmp_5_fu_587_p1");
    sc_trace(mVcdFile, tmp_73_0_0_5_cast_i_s_fu_615_p0, "tmp_73_0_0_5_cast_i_s_fu_615_p0");
    sc_trace(mVcdFile, tmp_9_fu_619_p0, "tmp_9_fu_619_p0");
    sc_trace(mVcdFile, p_Val2_11_0_0_3_ca_fu_597_p1, "p_Val2_11_0_0_3_ca_fu_597_p1");
    sc_trace(mVcdFile, tmp_73_0_0_4_cast_i_fu_601_p1, "tmp_73_0_0_4_cast_i_fu_601_p1");
    sc_trace(mVcdFile, tmp_73_0_0_5_cast_i_s_fu_615_p1, "tmp_73_0_0_5_cast_i_s_fu_615_p1");
    sc_trace(mVcdFile, tmp_73_0_0_6_cast_i_s_fu_623_p1, "tmp_73_0_0_6_cast_i_s_fu_623_p1");
    sc_trace(mVcdFile, tmp8_fu_637_p2, "tmp8_fu_637_p2");
    sc_trace(mVcdFile, tmp112_cast_fu_643_p1, "tmp112_cast_fu_643_p1");
    sc_trace(mVcdFile, tmp7_fu_631_p2, "tmp7_fu_631_p2");
    sc_trace(mVcdFile, p_Val2_11_0_0_6_i_fu_647_p2, "p_Val2_11_0_0_6_i_fu_647_p2");
    sc_trace(mVcdFile, tmp_4_fu_609_p2, "tmp_4_fu_609_p2");
    sc_trace(mVcdFile, tmp_9_fu_619_p1, "tmp_9_fu_619_p1");
    sc_trace(mVcdFile, tmp_6_fu_605_p1, "tmp_6_fu_605_p1");
    sc_trace(mVcdFile, tmp_10_fu_627_p1, "tmp_10_fu_627_p1");
    sc_trace(mVcdFile, tmp10_fu_667_p2, "tmp10_fu_667_p2");
    sc_trace(mVcdFile, tmp9_fu_661_p2, "tmp9_fu_661_p2");
    sc_trace(mVcdFile, tmp_s_fu_687_p4, "tmp_s_fu_687_p4");
    sc_trace(mVcdFile, newsignbit_fu_679_p3, "newsignbit_fu_679_p3");
    sc_trace(mVcdFile, p_not_i_i_i_i_fu_697_p2, "p_not_i_i_i_i_fu_697_p2");
    sc_trace(mVcdFile, isneg_fu_653_p3, "isneg_fu_653_p3");
    sc_trace(mVcdFile, brmerge_i_i_i_i_fu_703_p2, "brmerge_i_i_i_i_fu_703_p2");
    sc_trace(mVcdFile, tmp_1_i_i_i_fu_709_p2, "tmp_1_i_i_i_fu_709_p2");
    sc_trace(mVcdFile, p_not38_i_i_i_i_fu_727_p2, "p_not38_i_i_i_i_fu_727_p2");
    sc_trace(mVcdFile, newsignbit_0_not_i_i_fu_721_p2, "newsignbit_0_not_i_i_fu_721_p2");
    sc_trace(mVcdFile, brmerge39_i_i_i_i_fu_733_p2, "brmerge39_i_i_i_i_fu_733_p2");
    sc_trace(mVcdFile, underflow_fu_739_p2, "underflow_fu_739_p2");
    sc_trace(mVcdFile, overflow_fu_715_p2, "overflow_fu_715_p2");
    sc_trace(mVcdFile, underflow_not_i_i_i_fu_751_p2, "underflow_not_i_i_i_fu_751_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_i_i_fu_745_p2, "brmerge_i_i_i_i_i_fu_745_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_673_p2, "p_Val2_s_fu_673_p2");
    sc_trace(mVcdFile, brmerge_i_i_i_fu_757_p2, "brmerge_i_i_i_fu_757_p2");
    sc_trace(mVcdFile, p_Val2_2_fu_763_p3, "p_Val2_2_fu_763_p3");
    sc_trace(mVcdFile, p_Val2_4_i_i_i_fu_771_p3, "p_Val2_4_i_i_i_fu_771_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

row_filter::~row_filter() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete l_border_buf_0_val_s_U;
    delete r_border_buf_0_val_s_U;
}

void row_filter::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_0))) {
            ap_enable_reg_pp0_iter5 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(exitcond2_i_fu_291_p2.read(), ap_const_lv1_0))) {
        t_V_1_reg_235 = j_V_fu_296_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_0))) {
        t_V_1_reg_235 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        t_V_reg_224 = i_V_reg_965.read();
    } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        t_V_reg_224 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond2_i_fu_291_p2.read(), ap_const_lv1_0))) {
        col_assign_reg_991 = col_assign_fu_335_p2.read();
        or_cond1_i_reg_996 = or_cond1_i_fu_345_p2.read();
        or_cond_i_reg_987 = or_cond_i_fu_329_p2.read();
        tmp_4_i_reg_979 = tmp_4_i_fu_307_p2.read();
        tmp_5_i_reg_983 = tmp_5_i_fu_312_p2.read();
        tmp_8_i_reg_1002 = tmp_8_i_fu_351_p2.read();
        tmp_9_i_reg_1007 = tmp_9_i_fu_356_p2.read();
        x_i_reg_1011 = x_i_fu_402_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        col_assign_reg_991_pp0_iter1_reg = col_assign_reg_991.read();
        exitcond2_i_reg_970 = exitcond2_i_fu_291_p2.read();
        exitcond2_i_reg_970_pp0_iter1_reg = exitcond2_i_reg_970.read();
        or_cond1_i_reg_996_pp0_iter1_reg = or_cond1_i_reg_996.read();
        or_cond_i_reg_987_pp0_iter1_reg = or_cond_i_reg_987.read();
        tmp_5_i_reg_983_pp0_iter1_reg = tmp_5_i_reg_983.read();
        tmp_8_i_reg_1002_pp0_iter1_reg = tmp_8_i_reg_1002.read();
        tmp_9_i_reg_1007_pp0_iter1_reg = tmp_9_i_reg_1007.read();
        x_i_reg_1011_pp0_iter1_reg = x_i_reg_1011.read();
    }
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        cols_read_reg_914 = cols_dout.read();
        heightloop_reg_909 = rows_dout.read();
        index_cast_i1_cast_reg_928 = index_cast_i1_cast_fu_246_p3.read();
        index_reg_920 = p_anchor_x_dout.read();
        right_border_reg_933 = right_border_fu_254_p2.read();
        stop_reg_941 = stop_fu_260_p2.read();
        tmp_1_i_reg_946 = tmp_1_i_fu_266_p2.read();
        tmp_2_cast_i_cast_reg_951 = tmp_2_cast_i_cast_fu_272_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond2_i_reg_970_pp0_iter2_reg = exitcond2_i_reg_970_pp0_iter1_reg.read();
        exitcond2_i_reg_970_pp0_iter3_reg = exitcond2_i_reg_970_pp0_iter2_reg.read();
        or_cond1_i_reg_996_pp0_iter2_reg = or_cond1_i_reg_996_pp0_iter1_reg.read();
        or_cond1_i_reg_996_pp0_iter3_reg = or_cond1_i_reg_996_pp0_iter2_reg.read();
        row_buf_0_val_0_V_12_reg_1017 = row_buf_0_val_0_V_12_fu_460_p3.read();
        row_buf_0_val_0_V_12_reg_1017_pp0_iter3_reg = row_buf_0_val_0_V_12_reg_1017.read();
        tmp_8_i_reg_1002_pp0_iter2_reg = tmp_8_i_reg_1002_pp0_iter1_reg.read();
        tmp_8_i_reg_1002_pp0_iter3_reg = tmp_8_i_reg_1002_pp0_iter2_reg.read();
        tmp_9_i_reg_1007_pp0_iter2_reg = tmp_9_i_reg_1007_pp0_iter1_reg.read();
        tmp_9_i_reg_1007_pp0_iter3_reg = tmp_9_i_reg_1007_pp0_iter2_reg.read();
        tmp_9_i_reg_1007_pp0_iter4_reg = tmp_9_i_reg_1007_pp0_iter3_reg.read();
        x_i_reg_1011_pp0_iter2_reg = x_i_reg_1011_pp0_iter1_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_V_reg_965 = i_V_fu_285_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(exitcond2_i_reg_970_pp0_iter3_reg.read(), ap_const_lv1_0))) {
        row_buf_0_val_0_V_1_fu_122 = row_buf_0_val_0_V_12_reg_1017_pp0_iter3_reg.read();
        src_kernel_winX_temp_1_fu_102 = src_kernel_winX_temp_fu_98.read();
        src_kernel_winX_temp_2_fu_106 = src_kernel_winX_temp_1_fu_102.read();
        src_kernel_winX_temp_3_fu_110 = src_kernel_winX_temp_2_fu_106.read();
        src_kernel_winX_temp_4_fu_114 = src_kernel_winX_temp_3_fu_110.read();
        src_kernel_winX_temp_5_fu_118 = src_kernel_winX_temp_4_fu_114.read();
        src_kernel_winX_temp_fu_98 = src_kernel_winX_temp_11_fu_509_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(exitcond2_i_reg_970_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        row_buf_0_val_0_V_2_fu_126 = row_buf_val_V_0_0_2_1_fu_439_p3.read();
        row_buf_0_val_0_V_3_fu_130 = row_buf_0_val_0_V_10_fu_446_p3.read();
        row_buf_0_val_0_V_4_fu_134 = row_buf_0_val_0_V_11_fu_453_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        row_buf_0_val_0_V_s_fu_94 = p_src_V_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter3_reg.read()))) {
        tmp_V_1_reg_1032 = tmp_V_1_fu_779_p3.read();
    }
}

void row_filter::thread_OP1_V_1_0_0_1_i_fu_539_p0() {
    OP1_V_1_0_0_1_i_fu_539_p0 = src_kernel_winX_temp_4_fu_114.read();
}

void row_filter::thread_OP1_V_1_0_0_1_i_fu_539_p1() {
    OP1_V_1_0_0_1_i_fu_539_p1 = esl_sext<41,40>(OP1_V_1_0_0_1_i_fu_539_p0.read());
}

void row_filter::thread_OP1_V_1_0_0_i_fu_535_p0() {
    OP1_V_1_0_0_i_fu_535_p0 = src_kernel_winX_temp_5_fu_118.read();
}

void row_filter::thread_OP1_V_1_0_0_i_fu_535_p1() {
    OP1_V_1_0_0_i_fu_535_p1 = esl_sext<41,40>(OP1_V_1_0_0_i_fu_535_p0.read());
}

void row_filter::thread_addconv_i_fu_549_p2() {
    addconv_i_fu_549_p2 = (!OP1_V_1_0_0_i_fu_535_p1.read().is_01() || !OP1_V_1_0_0_1_i_fu_539_p1.read().is_01())? sc_lv<41>(): (sc_bigint<41>(OP1_V_1_0_0_i_fu_535_p1.read()) + sc_bigint<41>(OP1_V_1_0_0_1_i_fu_539_p1.read()));
}

void row_filter::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void row_filter::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void row_filter::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void row_filter::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[3];
}

void row_filter::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void row_filter::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_V_full_n.read())));
}

void row_filter::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_V_full_n.read())));
}

void row_filter::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_V_full_n.read())));
}

void row_filter::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void row_filter::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void row_filter::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_empty_n.read()));
}

void row_filter::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void row_filter::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void row_filter::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void row_filter::thread_ap_block_state8_pp0_stage0_iter5() {
    ap_block_state8_pp0_stage0_iter5 = (esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_V_full_n.read()));
}

void row_filter::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(exitcond2_i_fu_291_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void row_filter::thread_ap_done() {
    if ((esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void row_filter::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void row_filter::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void row_filter::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void row_filter::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void row_filter::thread_brmerge39_i_i_i_i_fu_733_p2() {
    brmerge39_i_i_i_i_fu_733_p2 = (p_not38_i_i_i_i_fu_727_p2.read() | newsignbit_0_not_i_i_fu_721_p2.read());
}

void row_filter::thread_brmerge_i_i_i_fu_757_p2() {
    brmerge_i_i_i_fu_757_p2 = (overflow_fu_715_p2.read() | underflow_not_i_i_i_fu_751_p2.read());
}

void row_filter::thread_brmerge_i_i_i_i_fu_703_p2() {
    brmerge_i_i_i_i_fu_703_p2 = (newsignbit_fu_679_p3.read() | p_not_i_i_i_i_fu_697_p2.read());
}

void row_filter::thread_brmerge_i_i_i_i_i_fu_745_p2() {
    brmerge_i_i_i_i_i_fu_745_p2 = (underflow_fu_739_p2.read() | overflow_fu_715_p2.read());
}

void row_filter::thread_col_assign_2_i_fu_486_p2() {
    col_assign_2_i_fu_486_p2 = (!right_border_reg_933.read().is_01() || !x_i_reg_1011_pp0_iter2_reg.read().is_01())? sc_lv<32>(): (sc_biguint<32>(right_border_reg_933.read()) - sc_biguint<32>(x_i_reg_1011_pp0_iter2_reg.read()));
}

void row_filter::thread_col_assign_fu_335_p2() {
    col_assign_fu_335_p2 = (!right_border_reg_933.read().is_01() || !t_V_1_reg_235.read().is_01())? sc_lv<32>(): (sc_biguint<32>(right_border_reg_933.read()) - sc_biguint<32>(t_V_1_reg_235.read()));
}

void row_filter::thread_cols_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        cols_blk_n = cols_empty_n.read();
    } else {
        cols_blk_n = ap_const_logic_1;
    }
}

void row_filter::thread_cols_read() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        cols_read = ap_const_logic_1;
    } else {
        cols_read = ap_const_logic_0;
    }
}

void row_filter::thread_exitcond1_i_fu_280_p2() {
    exitcond1_i_fu_280_p2 = (!t_V_reg_224.read().is_01() || !heightloop_reg_909.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_reg_224.read() == heightloop_reg_909.read());
}

void row_filter::thread_exitcond2_i_fu_291_p2() {
    exitcond2_i_fu_291_p2 = (!t_V_1_reg_235.read().is_01() || !tmp_1_i_reg_946.read().is_01())? sc_lv<1>(): sc_lv<1>(t_V_1_reg_235.read() == tmp_1_i_reg_946.read());
}

void row_filter::thread_i_V_fu_285_p2() {
    i_V_fu_285_p2 = (!t_V_reg_224.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_reg_224.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void row_filter::thread_index_cast_i1_cast_fu_246_p3() {
    index_cast_i1_cast_fu_246_p3 = (!p_anchor_x_dout.read()[0].is_01())? sc_lv<32>(): ((p_anchor_x_dout.read()[0].to_bool())? ap_const_lv32_3: ap_const_lv32_0);
}

void row_filter::thread_isneg_fu_653_p3() {
    isneg_fu_653_p3 = p_Val2_11_0_0_6_i_fu_647_p2.read().range(42, 42);
}

void row_filter::thread_j_V_fu_296_p2() {
    j_V_fu_296_p2 = (!t_V_1_reg_235.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_1_reg_235.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void row_filter::thread_l_border_buf_0_val_s_address0() {
    l_border_buf_0_val_s_address0 =  (sc_lv<3>) (ap_const_lv64_0);
}

void row_filter::thread_l_border_buf_0_val_s_address1() {
    l_border_buf_0_val_s_address1 =  (sc_lv<3>) (tmp_50_i_fu_482_p1.read());
}

void row_filter::thread_l_border_buf_0_val_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        l_border_buf_0_val_s_ce0 = ap_const_logic_1;
    } else {
        l_border_buf_0_val_s_ce0 = ap_const_logic_0;
    }
}

void row_filter::thread_l_border_buf_0_val_s_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        l_border_buf_0_val_s_ce1 = ap_const_logic_1;
    } else {
        l_border_buf_0_val_s_ce1 = ap_const_logic_0;
    }
}

void row_filter::thread_l_border_buf_0_val_s_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_5_i_reg_983_pp0_iter1_reg.read()))) {
        l_border_buf_0_val_s_we0 = ap_const_logic_1;
    } else {
        l_border_buf_0_val_s_we0 = ap_const_logic_0;
    }
}

void row_filter::thread_newsignbit_0_not_i_i_fu_721_p2() {
    newsignbit_0_not_i_i_fu_721_p2 = (newsignbit_fu_679_p3.read() ^ ap_const_lv1_1);
}

void row_filter::thread_newsignbit_fu_679_p3() {
    newsignbit_fu_679_p3 = p_Val2_11_0_0_6_i_fu_647_p2.read().range(34, 34);
}

void row_filter::thread_or_cond1_i_fu_345_p2() {
    or_cond1_i_fu_345_p2 = (tmp_5_i_fu_312_p2.read() | tmp_7_i_fu_340_p2.read());
}

void row_filter::thread_or_cond_i_fu_329_p2() {
    or_cond_i_fu_329_p2 = (rev_fu_323_p2.read() & tmp_4_i_fu_307_p2.read());
}

void row_filter::thread_or_cond_i_i_fu_381_p2() {
    or_cond_i_i_fu_381_p2 = (tmp_38_i_fu_376_p2.read() & rev1_fu_370_p2.read());
}

void row_filter::thread_overflow_fu_715_p2() {
    overflow_fu_715_p2 = (brmerge_i_i_i_i_fu_703_p2.read() & tmp_1_i_i_i_fu_709_p2.read());
}

void row_filter::thread_p_Val2_11_0_0_1_ca_fu_555_p1() {
    p_Val2_11_0_0_1_ca_fu_555_p1 = esl_sext<42,41>(addconv_i_fu_549_p2.read());
}

void row_filter::thread_p_Val2_11_0_0_3_ca_fu_597_p1() {
    p_Val2_11_0_0_3_ca_fu_597_p1 = esl_sext<43,42>(p_Val2_11_0_0_3_i_fu_591_p2.read());
}

void row_filter::thread_p_Val2_11_0_0_3_i_fu_591_p2() {
    p_Val2_11_0_0_3_i_fu_591_p2 = (!tmp_cast_fu_579_p1.read().is_01() || !p_Val2_11_0_0_1_ca_fu_555_p1.read().is_01())? sc_lv<42>(): (sc_bigint<42>(tmp_cast_fu_579_p1.read()) + sc_bigint<42>(p_Val2_11_0_0_1_ca_fu_555_p1.read()));
}

void row_filter::thread_p_Val2_11_0_0_6_i_fu_647_p2() {
    p_Val2_11_0_0_6_i_fu_647_p2 = (!tmp112_cast_fu_643_p1.read().is_01() || !tmp7_fu_631_p2.read().is_01())? sc_lv<43>(): (sc_bigint<43>(tmp112_cast_fu_643_p1.read()) + sc_biguint<43>(tmp7_fu_631_p2.read()));
}

void row_filter::thread_p_Val2_2_fu_763_p3() {
    p_Val2_2_fu_763_p3 = (!brmerge_i_i_i_i_i_fu_745_p2.read()[0].is_01())? sc_lv<35>(): ((brmerge_i_i_i_i_i_fu_745_p2.read()[0].to_bool())? ap_const_lv35_3FFFFFFFF: p_Val2_s_fu_673_p2.read());
}

void row_filter::thread_p_Val2_4_i_i_i_fu_771_p3() {
    p_Val2_4_i_i_i_fu_771_p3 = (!underflow_fu_739_p2.read()[0].is_01())? sc_lv<35>(): ((underflow_fu_739_p2.read()[0].to_bool())? ap_const_lv35_400000000: p_Val2_s_fu_673_p2.read());
}

void row_filter::thread_p_Val2_s_fu_673_p2() {
    p_Val2_s_fu_673_p2 = (!tmp10_fu_667_p2.read().is_01() || !tmp9_fu_661_p2.read().is_01())? sc_lv<35>(): (sc_biguint<35>(tmp10_fu_667_p2.read()) + sc_biguint<35>(tmp9_fu_661_p2.read()));
}

void row_filter::thread_p_anchor_x_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_anchor_x_blk_n = p_anchor_x_empty_n.read();
    } else {
        p_anchor_x_blk_n = ap_const_logic_1;
    }
}

void row_filter::thread_p_anchor_x_read() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_anchor_x_read = ap_const_logic_1;
    } else {
        p_anchor_x_read = ap_const_logic_0;
    }
}

void row_filter::thread_p_assign_1_i_fu_395_p3() {
    p_assign_1_i_fu_395_p3 = (!tmp_2_fu_387_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_2_fu_387_p3.read()[0].to_bool())? ap_const_lv32_0: right_border_reg_933.read());
}

void row_filter::thread_p_assign_fu_302_p2() {
    p_assign_fu_302_p2 = (!t_V_1_reg_235.read().is_01() || !tmp_2_cast_i_cast_reg_951.read().is_01())? sc_lv<32>(): (sc_biguint<32>(t_V_1_reg_235.read()) + sc_biguint<32>(tmp_2_cast_i_cast_reg_951.read()));
}

void row_filter::thread_p_dst_data_stream_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()))) {
        p_dst_data_stream_V_V_blk_n = p_dst_data_stream_V_V_full_n.read();
    } else {
        p_dst_data_stream_V_V_blk_n = ap_const_logic_1;
    }
}

void row_filter::thread_p_dst_data_stream_V_V_din() {
    p_dst_data_stream_V_V_din = tmp_V_1_reg_1032.read();
}

void row_filter::thread_p_dst_data_stream_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_9_i_reg_1007_pp0_iter4_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_V_write = ap_const_logic_0;
    }
}

void row_filter::thread_p_not38_i_i_i_i_fu_727_p2() {
    p_not38_i_i_i_i_fu_727_p2 = (!tmp_s_fu_687_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_fu_687_p4.read() != ap_const_lv8_FF);
}

void row_filter::thread_p_not_i_i_i_i_fu_697_p2() {
    p_not_i_i_i_i_fu_697_p2 = (!tmp_s_fu_687_p4.read().is_01() || !ap_const_lv8_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_s_fu_687_p4.read() != ap_const_lv8_0);
}

void row_filter::thread_p_src_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1))) {
        p_src_V_V_blk_n = p_src_V_V_empty_n.read();
    } else {
        p_src_V_V_blk_n = ap_const_logic_1;
    }
}

void row_filter::thread_p_src_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_4_i_reg_979.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_V_V_read = ap_const_logic_1;
    } else {
        p_src_V_V_read = ap_const_logic_0;
    }
}

void row_filter::thread_r_border_buf_0_val_s_address0() {
    r_border_buf_0_val_s_address0 =  (sc_lv<3>) (tmp_45_i_fu_423_p1.read());
}

void row_filter::thread_r_border_buf_0_val_s_address1() {
    r_border_buf_0_val_s_address1 =  (sc_lv<3>) (tmp_51_i_fu_490_p1.read());
}

void row_filter::thread_r_border_buf_0_val_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        r_border_buf_0_val_s_ce0 = ap_const_logic_1;
    } else {
        r_border_buf_0_val_s_ce0 = ap_const_logic_0;
    }
}

void row_filter::thread_r_border_buf_0_val_s_ce1() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()))) {
        r_border_buf_0_val_s_ce1 = ap_const_logic_1;
    } else {
        r_border_buf_0_val_s_ce1 = ap_const_logic_0;
    }
}

void row_filter::thread_r_border_buf_0_val_s_we0() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, or_cond_i_reg_987_pp0_iter1_reg.read()))) {
        r_border_buf_0_val_s_we0 = ap_const_logic_1;
    } else {
        r_border_buf_0_val_s_we0 = ap_const_logic_0;
    }
}

void row_filter::thread_rev1_fu_370_p2() {
    rev1_fu_370_p2 = (tmp_1_fu_362_p3.read() ^ ap_const_lv1_1);
}

void row_filter::thread_rev_fu_323_p2() {
    rev_fu_323_p2 = (ult_fu_318_p2.read() ^ ap_const_lv1_1);
}

void row_filter::thread_right_border_fu_254_p2() {
    right_border_fu_254_p2 = (!cols_dout.read().is_01() || !ap_const_lv32_FFFFFFFF.is_01())? sc_lv<32>(): (sc_biguint<32>(cols_dout.read()) + sc_bigint<32>(ap_const_lv32_FFFFFFFF));
}

void row_filter::thread_row_buf_0_val_0_V_10_fu_446_p3() {
    row_buf_0_val_0_V_10_fu_446_p3 = (!index_reg_920.read()[0].is_01())? sc_lv<40>(): ((index_reg_920.read()[0].to_bool())? row_buf_0_val_0_V_4_fu_134.read(): row_buf_0_val_0_V_3_fu_130.read());
}

void row_filter::thread_row_buf_0_val_0_V_11_fu_453_p3() {
    row_buf_0_val_0_V_11_fu_453_p3 = (!index_reg_920.read()[0].is_01())? sc_lv<40>(): ((index_reg_920.read()[0].to_bool())? row_buf_0_val_0_V_s_fu_94.read(): row_buf_0_val_0_V_4_fu_134.read());
}

void row_filter::thread_row_buf_0_val_0_V_12_fu_460_p3() {
    row_buf_0_val_0_V_12_fu_460_p3 = (!index_reg_920.read()[0].is_01())? sc_lv<40>(): ((index_reg_920.read()[0].to_bool())? row_buf_0_val_0_V_2_fu_126.read(): row_buf_0_val_0_V_s_fu_94.read());
}

void row_filter::thread_row_buf_val_V_0_0_2_1_fu_439_p3() {
    row_buf_val_V_0_0_2_1_fu_439_p3 = (!index_reg_920.read()[0].is_01())? sc_lv<40>(): ((index_reg_920.read()[0].to_bool())? row_buf_0_val_0_V_3_fu_130.read(): row_buf_0_val_0_V_2_fu_126.read());
}

void row_filter::thread_rows_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        rows_blk_n = rows_empty_n.read();
    } else {
        rows_blk_n = ap_const_logic_1;
    }
}

void row_filter::thread_rows_read() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        rows_read = ap_const_logic_1;
    } else {
        rows_read = ap_const_logic_0;
    }
}

void row_filter::thread_sel_tmp3_fu_498_p3() {
    sel_tmp3_fu_498_p3 = (!or_cond1_i_reg_996_pp0_iter3_reg.read()[0].is_01())? sc_lv<40>(): ((or_cond1_i_reg_996_pp0_iter3_reg.read()[0].to_bool())? row_buf_0_val_0_V_1_fu_122.read(): l_border_buf_0_val_s_q1.read());
}

void row_filter::thread_sel_tmp4_fu_505_p2() {
    sel_tmp4_fu_505_p2 = (or_cond1_i_reg_996_pp0_iter3_reg.read() & tmp_8_i_reg_1002_pp0_iter3_reg.read());
}

void row_filter::thread_src_kernel_winX_temp_11_fu_509_p3() {
    src_kernel_winX_temp_11_fu_509_p3 = (!sel_tmp4_fu_505_p2.read()[0].is_01())? sc_lv<40>(): ((sel_tmp4_fu_505_p2.read()[0].to_bool())? r_border_buf_0_val_s_q1.read(): sel_tmp3_fu_498_p3.read());
}

void row_filter::thread_stop_fu_260_p2() {
    stop_fu_260_p2 = (!cols_dout.read().is_01() || !index_cast_i1_cast_fu_246_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(cols_dout.read()) + sc_biguint<32>(index_cast_i1_cast_fu_246_p3.read()));
}

void row_filter::thread_tmp10_fu_667_p2() {
    tmp10_fu_667_p2 = (!tmp_6_fu_605_p1.read().is_01() || !tmp_10_fu_627_p1.read().is_01())? sc_lv<35>(): (sc_biguint<35>(tmp_6_fu_605_p1.read()) + sc_biguint<35>(tmp_10_fu_627_p1.read()));
}

void row_filter::thread_tmp112_cast_fu_643_p1() {
    tmp112_cast_fu_643_p1 = esl_sext<43,41>(tmp8_fu_637_p2.read());
}

void row_filter::thread_tmp7_fu_631_p2() {
    tmp7_fu_631_p2 = (!p_Val2_11_0_0_3_ca_fu_597_p1.read().is_01() || !tmp_73_0_0_4_cast_i_fu_601_p1.read().is_01())? sc_lv<43>(): (sc_bigint<43>(p_Val2_11_0_0_3_ca_fu_597_p1.read()) + sc_bigint<43>(tmp_73_0_0_4_cast_i_fu_601_p1.read()));
}

void row_filter::thread_tmp8_fu_637_p2() {
    tmp8_fu_637_p2 = (!tmp_73_0_0_5_cast_i_s_fu_615_p1.read().is_01() || !tmp_73_0_0_6_cast_i_s_fu_623_p1.read().is_01())? sc_lv<41>(): (sc_bigint<41>(tmp_73_0_0_5_cast_i_s_fu_615_p1.read()) + sc_bigint<41>(tmp_73_0_0_6_cast_i_s_fu_623_p1.read()));
}

void row_filter::thread_tmp9_fu_661_p2() {
    tmp9_fu_661_p2 = (!tmp_4_fu_609_p2.read().is_01() || !tmp_9_fu_619_p1.read().is_01())? sc_lv<35>(): (sc_biguint<35>(tmp_4_fu_609_p2.read()) + sc_biguint<35>(tmp_9_fu_619_p1.read()));
}

void row_filter::thread_tmp_10_fu_627_p1() {
    tmp_10_fu_627_p1 = src_kernel_winX_temp_11_fu_509_p3.read().range(35-1, 0);
}

void row_filter::thread_tmp_1_fu_362_p3() {
    tmp_1_fu_362_p3 = p_assign_fu_302_p2.read().range(31, 31);
}

void row_filter::thread_tmp_1_i_fu_266_p2() {
    tmp_1_i_fu_266_p2 = (!cols_dout.read().is_01() || !ap_const_lv32_7.is_01())? sc_lv<32>(): (sc_biguint<32>(cols_dout.read()) + sc_biguint<32>(ap_const_lv32_7));
}

void row_filter::thread_tmp_1_i_i_i_fu_709_p2() {
    tmp_1_i_i_i_fu_709_p2 = (isneg_fu_653_p3.read() ^ ap_const_lv1_1);
}

void row_filter::thread_tmp_2_cast_i_cast_fu_272_p3() {
    tmp_2_cast_i_cast_fu_272_p3 = (!p_anchor_x_dout.read()[0].is_01())? sc_lv<32>(): ((p_anchor_x_dout.read()[0].to_bool())? ap_const_lv32_FFFFFFFC: ap_const_lv32_FFFFFFFF);
}

void row_filter::thread_tmp_2_fu_387_p3() {
    tmp_2_fu_387_p3 = p_assign_fu_302_p2.read().range(31, 31);
}

void row_filter::thread_tmp_38_i_fu_376_p2() {
    tmp_38_i_fu_376_p2 = (!p_assign_fu_302_p2.read().is_01() || !cols_read_reg_914.read().is_01())? sc_lv<1>(): (sc_bigint<32>(p_assign_fu_302_p2.read()) < sc_bigint<32>(cols_read_reg_914.read()));
}

void row_filter::thread_tmp_3_fu_583_p1() {
    tmp_3_fu_583_p1 = tmp_7_fu_543_p2.read().range(35-1, 0);
}

void row_filter::thread_tmp_45_i_fu_423_p1() {
    tmp_45_i_fu_423_p1 = esl_zext<64,32>(col_assign_reg_991_pp0_iter1_reg.read());
}

void row_filter::thread_tmp_4_fu_609_p2() {
    tmp_4_fu_609_p2 = (!tmp_3_fu_583_p1.read().is_01() || !tmp_5_fu_587_p1.read().is_01())? sc_lv<35>(): (sc_biguint<35>(tmp_3_fu_583_p1.read()) + sc_biguint<35>(tmp_5_fu_587_p1.read()));
}

void row_filter::thread_tmp_4_i_fu_307_p2() {
    tmp_4_i_fu_307_p2 = (!t_V_1_reg_235.read().is_01() || !cols_read_reg_914.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_1_reg_235.read()) < sc_biguint<32>(cols_read_reg_914.read()));
}

void row_filter::thread_tmp_50_i_fu_482_p1() {
    tmp_50_i_fu_482_p1 = esl_zext<64,32>(x_i_reg_1011_pp0_iter2_reg.read());
}

void row_filter::thread_tmp_51_i_fu_490_p1() {
    tmp_51_i_fu_490_p1 = esl_zext<64,32>(col_assign_2_i_fu_486_p2.read());
}

void row_filter::thread_tmp_5_fu_587_p1() {
    tmp_5_fu_587_p1 = tmp_8_fu_567_p2.read().range(35-1, 0);
}

void row_filter::thread_tmp_5_i_fu_312_p2() {
    tmp_5_i_fu_312_p2 = (!t_V_1_reg_235.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): sc_lv<1>(t_V_1_reg_235.read() == ap_const_lv32_0);
}

void row_filter::thread_tmp_6_fu_605_p0() {
    tmp_6_fu_605_p0 = src_kernel_winX_temp_1_fu_102.read();
}

void row_filter::thread_tmp_6_fu_605_p1() {
    tmp_6_fu_605_p1 = tmp_6_fu_605_p0.read().range(35-1, 0);
}

void row_filter::thread_tmp_73_0_0_2_cast_i_s_fu_559_p0() {
    tmp_73_0_0_2_cast_i_s_fu_559_p0 = src_kernel_winX_temp_3_fu_110.read();
}

void row_filter::thread_tmp_73_0_0_2_cast_i_s_fu_559_p1() {
    tmp_73_0_0_2_cast_i_s_fu_559_p1 = esl_sext<41,40>(tmp_73_0_0_2_cast_i_s_fu_559_p0.read());
}

void row_filter::thread_tmp_73_0_0_3_cast_i_s_fu_563_p0() {
    tmp_73_0_0_3_cast_i_s_fu_563_p0 = src_kernel_winX_temp_2_fu_106.read();
}

void row_filter::thread_tmp_73_0_0_3_cast_i_s_fu_563_p1() {
    tmp_73_0_0_3_cast_i_s_fu_563_p1 = esl_sext<41,40>(tmp_73_0_0_3_cast_i_s_fu_563_p0.read());
}

void row_filter::thread_tmp_73_0_0_4_cast_i_fu_601_p0() {
    tmp_73_0_0_4_cast_i_fu_601_p0 = src_kernel_winX_temp_1_fu_102.read();
}

void row_filter::thread_tmp_73_0_0_4_cast_i_fu_601_p1() {
    tmp_73_0_0_4_cast_i_fu_601_p1 = esl_sext<43,40>(tmp_73_0_0_4_cast_i_fu_601_p0.read());
}

void row_filter::thread_tmp_73_0_0_5_cast_i_s_fu_615_p0() {
    tmp_73_0_0_5_cast_i_s_fu_615_p0 = src_kernel_winX_temp_fu_98.read();
}

void row_filter::thread_tmp_73_0_0_5_cast_i_s_fu_615_p1() {
    tmp_73_0_0_5_cast_i_s_fu_615_p1 = esl_sext<41,40>(tmp_73_0_0_5_cast_i_s_fu_615_p0.read());
}

void row_filter::thread_tmp_73_0_0_6_cast_i_s_fu_623_p1() {
    tmp_73_0_0_6_cast_i_s_fu_623_p1 = esl_sext<41,40>(src_kernel_winX_temp_11_fu_509_p3.read());
}

void row_filter::thread_tmp_7_fu_543_p0() {
    tmp_7_fu_543_p0 = src_kernel_winX_temp_4_fu_114.read();
}

void row_filter::thread_tmp_7_fu_543_p1() {
    tmp_7_fu_543_p1 = src_kernel_winX_temp_5_fu_118.read();
}

void row_filter::thread_tmp_7_fu_543_p2() {
    tmp_7_fu_543_p2 = (!tmp_7_fu_543_p0.read().is_01() || !tmp_7_fu_543_p1.read().is_01())? sc_lv<40>(): (sc_bigint<40>(tmp_7_fu_543_p0.read()) + sc_bigint<40>(tmp_7_fu_543_p1.read()));
}

void row_filter::thread_tmp_7_i_fu_340_p2() {
    tmp_7_i_fu_340_p2 = (!t_V_1_reg_235.read().is_01() || !index_cast_i1_cast_reg_928.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_1_reg_235.read()) > sc_biguint<32>(index_cast_i1_cast_reg_928.read()));
}

void row_filter::thread_tmp_8_fu_567_p0() {
    tmp_8_fu_567_p0 = src_kernel_winX_temp_2_fu_106.read();
}

void row_filter::thread_tmp_8_fu_567_p1() {
    tmp_8_fu_567_p1 = src_kernel_winX_temp_3_fu_110.read();
}

void row_filter::thread_tmp_8_fu_567_p2() {
    tmp_8_fu_567_p2 = (!tmp_8_fu_567_p0.read().is_01() || !tmp_8_fu_567_p1.read().is_01())? sc_lv<40>(): (sc_bigint<40>(tmp_8_fu_567_p0.read()) + sc_bigint<40>(tmp_8_fu_567_p1.read()));
}

void row_filter::thread_tmp_8_i_fu_351_p2() {
    tmp_8_i_fu_351_p2 = (!t_V_1_reg_235.read().is_01() || !stop_reg_941.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_1_reg_235.read()) > sc_biguint<32>(stop_reg_941.read()));
}

void row_filter::thread_tmp_9_fu_619_p0() {
    tmp_9_fu_619_p0 = src_kernel_winX_temp_fu_98.read();
}

void row_filter::thread_tmp_9_fu_619_p1() {
    tmp_9_fu_619_p1 = tmp_9_fu_619_p0.read().range(35-1, 0);
}

void row_filter::thread_tmp_9_i_fu_356_p2() {
    tmp_9_i_fu_356_p2 = (!t_V_1_reg_235.read().is_01() || !ap_const_lv32_6.is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_1_reg_235.read()) > sc_biguint<32>(ap_const_lv32_6));
}

void row_filter::thread_tmp_V_1_fu_779_p3() {
    tmp_V_1_fu_779_p3 = (!brmerge_i_i_i_fu_757_p2.read()[0].is_01())? sc_lv<35>(): ((brmerge_i_i_i_fu_757_p2.read()[0].to_bool())? p_Val2_2_fu_763_p3.read(): p_Val2_4_i_i_i_fu_771_p3.read());
}

void row_filter::thread_tmp_cast_fu_579_p1() {
    tmp_cast_fu_579_p1 = esl_sext<42,41>(tmp_fu_573_p2.read());
}

void row_filter::thread_tmp_fu_573_p2() {
    tmp_fu_573_p2 = (!tmp_73_0_0_2_cast_i_s_fu_559_p1.read().is_01() || !tmp_73_0_0_3_cast_i_s_fu_563_p1.read().is_01())? sc_lv<41>(): (sc_bigint<41>(tmp_73_0_0_2_cast_i_s_fu_559_p1.read()) + sc_bigint<41>(tmp_73_0_0_3_cast_i_s_fu_563_p1.read()));
}

void row_filter::thread_tmp_s_fu_687_p4() {
    tmp_s_fu_687_p4 = p_Val2_11_0_0_6_i_fu_647_p2.read().range(42, 35);
}

void row_filter::thread_ult_fu_318_p2() {
    ult_fu_318_p2 = (!t_V_1_reg_235.read().is_01() || !right_border_reg_933.read().is_01())? sc_lv<1>(): (sc_biguint<32>(t_V_1_reg_235.read()) < sc_biguint<32>(right_border_reg_933.read()));
}

void row_filter::thread_underflow_fu_739_p2() {
    underflow_fu_739_p2 = (brmerge39_i_i_i_i_fu_733_p2.read() & isneg_fu_653_p3.read());
}

void row_filter::thread_underflow_not_i_i_i_fu_751_p2() {
    underflow_not_i_i_i_fu_751_p2 = (underflow_fu_739_p2.read() ^ ap_const_lv1_1);
}

void row_filter::thread_x_i_fu_402_p3() {
    x_i_fu_402_p3 = (!or_cond_i_i_fu_381_p2.read()[0].is_01())? sc_lv<32>(): ((or_cond_i_i_fu_381_p2.read()[0].to_bool())? p_assign_fu_302_p2.read(): p_assign_1_i_fu_395_p3.read());
}

void row_filter::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(cols_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(rows_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_anchor_x_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(exitcond1_i_fu_280_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(exitcond2_i_fu_291_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)) && !(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter4.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter5.read(), ap_const_logic_1)) || (esl_seteq<1,1,1>(exitcond2_i_fu_291_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0) && 
  esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

