// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhaaris_core.h"

extern XHaaris_core_Config XHaaris_core_ConfigTable[];

XHaaris_core_Config *XHaaris_core_LookupConfig(u16 DeviceId) {
	XHaaris_core_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHAARIS_CORE_NUM_INSTANCES; Index++) {
		if (XHaaris_core_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHaaris_core_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHaaris_core_Initialize(XHaaris_core *InstancePtr, u16 DeviceId) {
	XHaaris_core_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHaaris_core_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHaaris_core_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

