// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module scaled_fixed2ieee (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_V,
        prescale,
        ap_return
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    ap_const_lv32_0 = 32'd0;


input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [28:0] in_V;
input  [8:0] prescale;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[31:0] ap_return;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] i_fu_277_p2;
reg   [1:0] i_reg_486;
wire    ap_CS_fsm_state2;
wire   [63:0] tmp_4_fu_283_p1;
reg   [63:0] tmp_4_reg_491;
wire   [0:0] exitcond_fu_271_p2;
wire   [0:0] tmp_119_fu_307_p3;
reg   [0:0] tmp_119_reg_501;
wire    ap_CS_fsm_state4;
wire   [1:0] i_1_fu_315_p2;
reg   [1:0] i_1_reg_505;
wire   [31:0] shift_2_fu_326_p2;
wire    ap_CS_fsm_state5;
wire   [28:0] in_shift_V_fu_379_p3;
reg   [0:0] out_bits_V_address0;
reg    out_bits_V_ce0;
reg    out_bits_V_we0;
wire   [31:0] out_bits_V_d0;
wire   [31:0] out_bits_V_q0;
wire   [0:0] out_bits_V_address1;
reg    out_bits_V_ce1;
reg    out_bits_V_we1;
wire   [31:0] out_bits_V_d1;
reg   [0:0] c_address0;
reg    c_ce0;
reg    c_we0;
reg   [31:0] c_d0;
wire   [31:0] c_q0;
reg   [1:0] i1_reg_151;
wire    ap_CS_fsm_state3;
reg   [28:0] in_shift_reg_162;
wire   [0:0] tmp_11_fu_388_p2;
reg   [31:0] shift_reg_172;
reg   [1:0] i2_reg_184;
reg   [28:0] ap_phi_mux_p_Val2_in_phi_fu_198_p4;
reg   [28:0] p_Val2_in_reg_195;
reg   [31:0] ap_phi_mux_shift_1_phi_fu_208_p4;
reg   [31:0] shift_1_reg_205;
wire   [63:0] tmp_6_fu_321_p1;
wire   [15:0] p_Result_5_fu_215_p4;
wire   [16:0] tmp_fu_225_p3;
wire   [12:0] tmp_118_fu_246_p1;
wire   [13:0] tmp_60_fu_250_p3;
reg   [31:0] p_Result_s_fu_288_p4;
wire   [0:0] isNeg_fu_333_p3;
wire   [31:0] tmp_7_fu_341_p2;
wire   [31:0] tmp_8_fu_355_p1;
wire   [31:0] sh_assign_1_fu_347_p3;
wire   [31:0] tmp_10_fu_365_p2;
wire   [31:0] tmp_9_fu_359_p2;
wire   [28:0] tmp_121_fu_371_p1;
wire   [28:0] tmp_122_fu_375_p1;
wire   [8:0] tmp_12_fu_394_p2;
wire  signed [31:0] tmp_12_cast_fu_399_p1;
wire   [31:0] newexp_fu_403_p2;
wire   [0:0] tmp_124_fu_409_p3;
wire   [0:0] tmp_14_fu_417_p2;
wire   [0:0] or_cond_fu_422_p2;
wire   [22:0] phitmp5_fu_432_p4;
wire   [7:0] tmp_125_fu_428_p1;
wire   [7:0] out_exp_V_fu_450_p3;
wire   [22:0] p_Val2_36_fu_442_p3;
wire   [31:0] p_Result_32_fu_458_p4;
wire   [31:0] result_write_assign_fu_468_p1;
reg   [31:0] ap_return_preg;
reg   [4:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_return_preg = 32'd0;
end

scaled_fixed2ieeebck #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
out_bits_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(out_bits_V_address0),
    .ce0(out_bits_V_ce0),
    .we0(out_bits_V_we0),
    .d0(out_bits_V_d0),
    .q0(out_bits_V_q0),
    .address1(out_bits_V_address1),
    .ce1(out_bits_V_ce1),
    .we1(out_bits_V_we1),
    .d1(out_bits_V_d1)
);

scaled_fixed2ieee_c #(
    .DataWidth( 32 ),
    .AddressRange( 2 ),
    .AddressWidth( 1 ))
c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(c_address0),
    .ce0(c_ce0),
    .we0(c_we0),
    .d0(c_d0),
    .q0(c_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
                ap_return_preg[0] <= 1'b0;
        ap_return_preg[1] <= 1'b0;
        ap_return_preg[2] <= 1'b0;
        ap_return_preg[3] <= 1'b0;
        ap_return_preg[4] <= 1'b0;
        ap_return_preg[5] <= 1'b0;
        ap_return_preg[6] <= 1'b0;
        ap_return_preg[7] <= 1'b0;
        ap_return_preg[8] <= 1'b0;
        ap_return_preg[9] <= 1'b0;
        ap_return_preg[10] <= 1'b0;
        ap_return_preg[11] <= 1'b0;
        ap_return_preg[12] <= 1'b0;
        ap_return_preg[13] <= 1'b0;
        ap_return_preg[14] <= 1'b0;
        ap_return_preg[15] <= 1'b0;
        ap_return_preg[16] <= 1'b0;
        ap_return_preg[17] <= 1'b0;
        ap_return_preg[18] <= 1'b0;
        ap_return_preg[19] <= 1'b0;
        ap_return_preg[20] <= 1'b0;
        ap_return_preg[21] <= 1'b0;
        ap_return_preg[22] <= 1'b0;
        ap_return_preg[23] <= 1'b0;
        ap_return_preg[24] <= 1'b0;
        ap_return_preg[25] <= 1'b0;
        ap_return_preg[26] <= 1'b0;
        ap_return_preg[27] <= 1'b0;
        ap_return_preg[28] <= 1'b0;
        ap_return_preg[29] <= 1'b0;
        ap_return_preg[30] <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state5) & ((tmp_119_reg_501 == 1'd1) | (tmp_11_fu_388_p2 == 1'd0)))) begin
                        ap_return_preg[30 : 0] <= result_write_assign_fu_468_p1[30 : 0];
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i1_reg_151 <= i_reg_486;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i1_reg_151 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i2_reg_184 <= 2'd0;
    end else if (((tmp_119_reg_501 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_11_fu_388_p2 == 1'd1))) begin
        i2_reg_184 <= i_1_reg_505;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        in_shift_reg_162 <= in_V;
    end else if (((tmp_119_reg_501 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_11_fu_388_p2 == 1'd1))) begin
        in_shift_reg_162 <= in_shift_V_fu_379_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_119_reg_501 == 1'd0) & (tmp_11_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        p_Val2_in_reg_195 <= in_shift_V_fu_379_p3;
    end else if (((tmp_119_fu_307_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_Val2_in_reg_195 <= in_shift_reg_162;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_119_reg_501 == 1'd0) & (tmp_11_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        shift_1_reg_205 <= shift_2_fu_326_p2;
    end else if (((tmp_119_fu_307_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        shift_1_reg_205 <= shift_reg_172;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        shift_reg_172 <= 32'd0;
    end else if (((tmp_119_reg_501 == 1'd0) & (1'b1 == ap_CS_fsm_state5) & (tmp_11_fu_388_p2 == 1'd1))) begin
        shift_reg_172 <= shift_2_fu_326_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_1_reg_505 <= i_1_fu_315_p2;
        tmp_119_reg_501 <= i2_reg_184[32'd1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_486 <= i_fu_277_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_271_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_4_reg_491[1 : 0] <= tmp_4_fu_283_p1[1 : 0];
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state5) & ((tmp_119_reg_501 == 1'd1) | (tmp_11_fu_388_p2 == 1'd0))) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_119_reg_501 == 1'd0) & (tmp_11_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_p_Val2_in_phi_fu_198_p4 = in_shift_V_fu_379_p3;
    end else begin
        ap_phi_mux_p_Val2_in_phi_fu_198_p4 = p_Val2_in_reg_195;
    end
end

always @ (*) begin
    if (((tmp_119_reg_501 == 1'd0) & (tmp_11_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_shift_1_phi_fu_208_p4 = shift_2_fu_326_p2;
    end else begin
        ap_phi_mux_shift_1_phi_fu_208_p4 = shift_1_reg_205;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((tmp_119_reg_501 == 1'd1) | (tmp_11_fu_388_p2 == 1'd0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((tmp_119_reg_501 == 1'd1) | (tmp_11_fu_388_p2 == 1'd0)))) begin
        ap_return = result_write_assign_fu_468_p1;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        c_address0 = tmp_6_fu_321_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        c_address0 = tmp_4_reg_491;
    end else begin
        c_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        c_ce0 = 1'b1;
    end else begin
        c_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        c_we0 = 1'b1;
    end else begin
        c_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        out_bits_V_address0 = tmp_4_fu_283_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        out_bits_V_address0 = 64'd0;
    end else begin
        out_bits_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        out_bits_V_ce0 = 1'b1;
    end else begin
        out_bits_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_bits_V_ce1 = 1'b1;
    end else begin
        out_bits_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_bits_V_we0 = 1'b1;
    end else begin
        out_bits_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        out_bits_V_we1 = 1'b1;
    end else begin
        out_bits_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_fu_271_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((tmp_119_reg_501 == 1'd1) | (tmp_11_fu_388_p2 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];


always @ (p_Result_s_fu_288_p4) begin
    if (p_Result_s_fu_288_p4[0] == 1'b1) begin
        c_d0 = 32'd0;
    end else if (p_Result_s_fu_288_p4[1] == 1'b1) begin
        c_d0 = 32'd1;
    end else if (p_Result_s_fu_288_p4[2] == 1'b1) begin
        c_d0 = 32'd2;
    end else if (p_Result_s_fu_288_p4[3] == 1'b1) begin
        c_d0 = 32'd3;
    end else if (p_Result_s_fu_288_p4[4] == 1'b1) begin
        c_d0 = 32'd4;
    end else if (p_Result_s_fu_288_p4[5] == 1'b1) begin
        c_d0 = 32'd5;
    end else if (p_Result_s_fu_288_p4[6] == 1'b1) begin
        c_d0 = 32'd6;
    end else if (p_Result_s_fu_288_p4[7] == 1'b1) begin
        c_d0 = 32'd7;
    end else if (p_Result_s_fu_288_p4[8] == 1'b1) begin
        c_d0 = 32'd8;
    end else if (p_Result_s_fu_288_p4[9] == 1'b1) begin
        c_d0 = 32'd9;
    end else if (p_Result_s_fu_288_p4[10] == 1'b1) begin
        c_d0 = 32'd10;
    end else if (p_Result_s_fu_288_p4[11] == 1'b1) begin
        c_d0 = 32'd11;
    end else if (p_Result_s_fu_288_p4[12] == 1'b1) begin
        c_d0 = 32'd12;
    end else if (p_Result_s_fu_288_p4[13] == 1'b1) begin
        c_d0 = 32'd13;
    end else if (p_Result_s_fu_288_p4[14] == 1'b1) begin
        c_d0 = 32'd14;
    end else if (p_Result_s_fu_288_p4[15] == 1'b1) begin
        c_d0 = 32'd15;
    end else if (p_Result_s_fu_288_p4[16] == 1'b1) begin
        c_d0 = 32'd16;
    end else if (p_Result_s_fu_288_p4[17] == 1'b1) begin
        c_d0 = 32'd17;
    end else if (p_Result_s_fu_288_p4[18] == 1'b1) begin
        c_d0 = 32'd18;
    end else if (p_Result_s_fu_288_p4[19] == 1'b1) begin
        c_d0 = 32'd19;
    end else if (p_Result_s_fu_288_p4[20] == 1'b1) begin
        c_d0 = 32'd20;
    end else if (p_Result_s_fu_288_p4[21] == 1'b1) begin
        c_d0 = 32'd21;
    end else if (p_Result_s_fu_288_p4[22] == 1'b1) begin
        c_d0 = 32'd22;
    end else if (p_Result_s_fu_288_p4[23] == 1'b1) begin
        c_d0 = 32'd23;
    end else if (p_Result_s_fu_288_p4[24] == 1'b1) begin
        c_d0 = 32'd24;
    end else if (p_Result_s_fu_288_p4[25] == 1'b1) begin
        c_d0 = 32'd25;
    end else if (p_Result_s_fu_288_p4[26] == 1'b1) begin
        c_d0 = 32'd26;
    end else if (p_Result_s_fu_288_p4[27] == 1'b1) begin
        c_d0 = 32'd27;
    end else if (p_Result_s_fu_288_p4[28] == 1'b1) begin
        c_d0 = 32'd28;
    end else if (p_Result_s_fu_288_p4[29] == 1'b1) begin
        c_d0 = 32'd29;
    end else if (p_Result_s_fu_288_p4[30] == 1'b1) begin
        c_d0 = 32'd30;
    end else if (p_Result_s_fu_288_p4[31] == 1'b1) begin
        c_d0 = 32'd31;
    end else begin
        c_d0 = 32'd32;
    end
end

assign exitcond_fu_271_p2 = ((i1_reg_151 == 2'd2) ? 1'b1 : 1'b0);

assign i_1_fu_315_p2 = (i2_reg_184 + 2'd1);

assign i_fu_277_p2 = (i1_reg_151 + 2'd1);

assign in_shift_V_fu_379_p3 = ((isNeg_fu_333_p3[0:0] === 1'b1) ? tmp_121_fu_371_p1 : tmp_122_fu_375_p1);

assign isNeg_fu_333_p3 = c_q0[32'd31];

assign newexp_fu_403_p2 = ($signed(tmp_12_cast_fu_399_p1) - $signed(ap_phi_mux_shift_1_phi_fu_208_p4));

assign or_cond_fu_422_p2 = (tmp_14_fu_417_p2 | tmp_124_fu_409_p3);

assign out_bits_V_address1 = 64'd1;

assign out_bits_V_d0 = {{tmp_fu_225_p3}, {ap_const_lv32_0[14:0]}};

assign out_bits_V_d1 = {{tmp_60_fu_250_p3}, {ap_const_lv32_0[17:0]}};

assign out_exp_V_fu_450_p3 = ((or_cond_fu_422_p2[0:0] === 1'b1) ? 8'd0 : tmp_125_fu_428_p1);

assign p_Result_32_fu_458_p4 = {{{{1'd0}, {out_exp_V_fu_450_p3}}}, {p_Val2_36_fu_442_p3}};

assign p_Result_5_fu_215_p4 = {{in_V[28:13]}};

integer ap_tvar_int_0;

always @ (out_bits_V_q0) begin
    for (ap_tvar_int_0 = 32 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 31 - 0) begin
            p_Result_s_fu_288_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_288_p4[ap_tvar_int_0] = out_bits_V_q0[31 - ap_tvar_int_0];
        end
    end
end

assign p_Val2_36_fu_442_p3 = ((or_cond_fu_422_p2[0:0] === 1'b1) ? 23'd0 : phitmp5_fu_432_p4);

assign phitmp5_fu_432_p4 = {{ap_phi_mux_p_Val2_in_phi_fu_198_p4[27:5]}};

assign result_write_assign_fu_468_p1 = p_Result_32_fu_458_p4;

assign sh_assign_1_fu_347_p3 = ((isNeg_fu_333_p3[0:0] === 1'b1) ? tmp_7_fu_341_p2 : c_q0);

assign shift_2_fu_326_p2 = (shift_reg_172 + c_q0);

assign tmp_10_fu_365_p2 = tmp_8_fu_355_p1 >> sh_assign_1_fu_347_p3;

assign tmp_118_fu_246_p1 = in_V[12:0];

assign tmp_119_fu_307_p3 = i2_reg_184[32'd1];

assign tmp_11_fu_388_p2 = ((c_q0 == 32'd16) ? 1'b1 : 1'b0);

assign tmp_121_fu_371_p1 = tmp_10_fu_365_p2[28:0];

assign tmp_122_fu_375_p1 = tmp_9_fu_359_p2[28:0];

assign tmp_124_fu_409_p3 = newexp_fu_403_p2[32'd31];

assign tmp_125_fu_428_p1 = newexp_fu_403_p2[7:0];

assign tmp_12_cast_fu_399_p1 = $signed(tmp_12_fu_394_p2);

assign tmp_12_fu_394_p2 = (9'd127 - prescale);

assign tmp_14_fu_417_p2 = ((in_V == 29'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_283_p1 = i1_reg_151;

assign tmp_60_fu_250_p3 = {{tmp_118_fu_246_p1}, {1'd1}};

assign tmp_6_fu_321_p1 = i2_reg_184;

assign tmp_7_fu_341_p2 = (32'd0 - c_q0);

assign tmp_8_fu_355_p1 = in_shift_reg_162;

assign tmp_9_fu_359_p2 = tmp_8_fu_355_p1 << sh_assign_1_fu_347_p3;

assign tmp_fu_225_p3 = {{p_Result_5_fu_215_p4}, {1'd1}};

always @ (posedge ap_clk) begin
    tmp_4_reg_491[63:2] <= 62'b00000000000000000000000000000000000000000000000000000000000000;
    ap_return_preg[31] <= 1'b0;
end

endmodule //scaled_fixed2ieee
